/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.api;

import com.binance.connector.client.common.ApiException;
import com.binance.connector.client.common.ApiResponse;
import com.binance.connector.client.common.Pair;
import com.binance.connector.client.common.SystemUtil;
import com.binance.connector.client.common.configuration.ClientConfiguration;
import com.binance.connector.client.common.exception.ConstraintViolationException;
import com.binance.connector.client.web3.common.ApiClient;
import com.binance.connector.client.web3_wallet.rest.model.GetAddressPnLForSpecificTokenResponse;
import com.binance.connector.client.web3_wallet.rest.model.GetAddressPortfolioOverviewResponse;
import com.binance.connector.client.web3_wallet.rest.model.GetAddressRecentPnLResponse;
import com.binance.connector.client.web3_wallet.rest.model.GetDexTradeHistoryResponse;
import com.binance.connector.client.web3_wallet.rest.model.GetLeaderboardResponse;
import com.binance.connector.client.web3_wallet.rest.model.GetPortfolioSupportedChainsResponse;
import com.binance.connector.client.web3_wallet.rest.model.GetTrackedTradesResponse;
import com.binance.connector.client.web3_wallet.rest.model.OrderType;
import com.binance.connector.client.web3_wallet.rest.model.SortBy;
import com.binance.connector.client.web3_wallet.rest.model.TimeFrame;
import com.binance.connector.client.web3_wallet.rest.model.TrackerType;
import com.binance.connector.client.web3_wallet.rest.model.WalletType;
import com.google.gson.reflect.TypeToken;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.constraints.*;
import jakarta.validation.executable.ExecutableValidator;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator;

public class AddressPortfolioApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    private static final String USER_AGENT =
            String.format(
                    "binance-web3-wallet/4.0.0 (Java/%s; %s; %s)",
                    SystemUtil.getJavaVersion(), SystemUtil.getOs(), SystemUtil.getArch());
    private static final boolean HAS_TIME_UNIT = false;

    public AddressPortfolioApi(ClientConfiguration clientConfiguration) {
        this(new ApiClient(clientConfiguration));
    }

    public AddressPortfolioApi(ApiClient apiClient) {
        apiClient.setUserAgent(USER_AGENT);
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call getAddressPnLForSpecificTokenCall(
            String binanceChainId,
            String walletAddress,
            String tokenContractAddress,
            Long recvWindow,
            String nonce)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/dex/market/portfolio/token/latest-pnl";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (binanceChainId != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("binanceChainId", binanceChainId));
        }

        if (walletAddress != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("walletAddress", walletAddress));
        }

        if (tokenContractAddress != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair(
                            "tokenContractAddress", tokenContractAddress));
        }

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/x-www-form-urlencoded"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (!localVarFormParams.isEmpty() && localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (recvWindow != null) {
            localVarHeaderParams.put("recvWindow", localVarApiClient.parameterToString(recvWindow));
        }

        if (nonce != null) {
            localVarHeaderParams.put("nonce", localVarApiClient.parameterToString(nonce));
        }

        Set<String> localVarAuthNames = new HashSet<>();
        localVarAuthNames.add("binanceWeb3Signature");
        if (HAS_TIME_UNIT) {
            localVarAuthNames.add("timeUnit");
        }
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAddressPnLForSpecificTokenValidateBeforeCall(
            String binanceChainId,
            String walletAddress,
            String tokenContractAddress,
            Long recvWindow,
            String nonce)
            throws ApiException {
        try {
            Validator validator =
                    Validation.byDefaultProvider()
                            .configure()
                            .messageInterpolator(new ParameterMessageInterpolator())
                            .buildValidatorFactory()
                            .getValidator();
            ExecutableValidator executableValidator = validator.forExecutables();

            Object[] parameterValues = {
                binanceChainId, walletAddress, tokenContractAddress, recvWindow, nonce
            };
            Method method =
                    this.getClass()
                            .getMethod(
                                    "getAddressPnLForSpecificToken",
                                    String.class,
                                    String.class,
                                    String.class,
                                    Long.class,
                                    String.class);
            Set<ConstraintViolation<AddressPortfolioApi>> violations =
                    executableValidator.validateParameters(this, method, parameterValues);

            if (violations.size() == 0) {
                return getAddressPnLForSpecificTokenCall(
                        binanceChainId, walletAddress, tokenContractAddress, recvWindow, nonce);
            } else {
                throw new ConstraintViolationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    public ApiResponse<GetAddressPnLForSpecificTokenResponse> getAddressPnLForSpecificToken(
            @NotNull String binanceChainId,
            @NotNull String walletAddress,
            @NotNull String tokenContractAddress,
            Long recvWindow,
            String nonce)
            throws ApiException {
        okhttp3.Call localVarCall =
                getAddressPnLForSpecificTokenValidateBeforeCall(
                        binanceChainId, walletAddress, tokenContractAddress, recvWindow, nonce);
        java.lang.reflect.Type localVarReturnType =
                new TypeToken<GetAddressPnLForSpecificTokenResponse>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    public ApiResponse<GetAddressPnLForSpecificTokenResponse> getAddressPnLForSpecificToken(
            GetAddressPnLForSpecificTokenRequest request) {
        return getAddressPnLForSpecificToken(
                request.getBinanceChainId(),
                request.getWalletAddress(),
                request.getTokenContractAddress(),
                request.getRecvWindow(),
                request.getNonce());
    }

    public static class GetAddressPnLForSpecificTokenRequest {
        private final String binanceChainId;
        private final String walletAddress;
        private final String tokenContractAddress;
        private Long recvWindow;
        private String nonce;

        public String getBinanceChainId() {
            return binanceChainId;
        }

        public String getWalletAddress() {
            return walletAddress;
        }

        public String getTokenContractAddress() {
            return tokenContractAddress;
        }

        public Long getRecvWindow() {
            return recvWindow;
        }

        public String getNonce() {
            return nonce;
        }

        public GetAddressPnLForSpecificTokenRequest(
                String binanceChainId, String walletAddress, String tokenContractAddress) {
            this.binanceChainId = binanceChainId;
            this.walletAddress = walletAddress;
            this.tokenContractAddress = tokenContractAddress;
        }

        /**
         * Set recvWindow
         *
         * @param recvWindow Allowed time deviation in milliseconds (default: 5000, max: 60000).
         *     (optional)
         * @return GetAddressPnLForSpecificTokenRequest
         */
        public GetAddressPnLForSpecificTokenRequest recvWindow(Long recvWindow) {
            this.recvWindow = recvWindow;
            return this;
        }

        /**
         * Set nonce
         *
         * @param nonce Unique request identifier for anti-replay; falls back to X-OC-SIGN if
         *     omitted. (optional)
         * @return GetAddressPnLForSpecificTokenRequest
         */
        public GetAddressPnLForSpecificTokenRequest nonce(String nonce) {
            this.nonce = nonce;
            return this;
        }
    }

    private okhttp3.Call getAddressPortfolioOverviewCall(
            String binanceChainId,
            String walletAddress,
            TimeFrame timeFrame,
            Long recvWindow,
            String nonce)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/dex/market/portfolio/overview";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (binanceChainId != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("binanceChainId", binanceChainId));
        }

        if (walletAddress != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("walletAddress", walletAddress));
        }

        if (timeFrame != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("timeFrame", timeFrame));
        }

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/x-www-form-urlencoded"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (!localVarFormParams.isEmpty() && localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (recvWindow != null) {
            localVarHeaderParams.put("recvWindow", localVarApiClient.parameterToString(recvWindow));
        }

        if (nonce != null) {
            localVarHeaderParams.put("nonce", localVarApiClient.parameterToString(nonce));
        }

        Set<String> localVarAuthNames = new HashSet<>();
        localVarAuthNames.add("binanceWeb3Signature");
        if (HAS_TIME_UNIT) {
            localVarAuthNames.add("timeUnit");
        }
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAddressPortfolioOverviewValidateBeforeCall(
            String binanceChainId,
            String walletAddress,
            TimeFrame timeFrame,
            Long recvWindow,
            String nonce)
            throws ApiException {
        try {
            Validator validator =
                    Validation.byDefaultProvider()
                            .configure()
                            .messageInterpolator(new ParameterMessageInterpolator())
                            .buildValidatorFactory()
                            .getValidator();
            ExecutableValidator executableValidator = validator.forExecutables();

            Object[] parameterValues = {
                binanceChainId, walletAddress, timeFrame, recvWindow, nonce
            };
            Method method =
                    this.getClass()
                            .getMethod(
                                    "getAddressPortfolioOverview",
                                    String.class,
                                    String.class,
                                    TimeFrame.class,
                                    Long.class,
                                    String.class);
            Set<ConstraintViolation<AddressPortfolioApi>> violations =
                    executableValidator.validateParameters(this, method, parameterValues);

            if (violations.size() == 0) {
                return getAddressPortfolioOverviewCall(
                        binanceChainId, walletAddress, timeFrame, recvWindow, nonce);
            } else {
                throw new ConstraintViolationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    public ApiResponse<GetAddressPortfolioOverviewResponse> getAddressPortfolioOverview(
            @NotNull String binanceChainId,
            @NotNull String walletAddress,
            @NotNull TimeFrame timeFrame,
            Long recvWindow,
            String nonce)
            throws ApiException {
        okhttp3.Call localVarCall =
                getAddressPortfolioOverviewValidateBeforeCall(
                        binanceChainId, walletAddress, timeFrame, recvWindow, nonce);
        java.lang.reflect.Type localVarReturnType =
                new TypeToken<GetAddressPortfolioOverviewResponse>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    public ApiResponse<GetAddressPortfolioOverviewResponse> getAddressPortfolioOverview(
            GetAddressPortfolioOverviewRequest request) {
        return getAddressPortfolioOverview(
                request.getBinanceChainId(),
                request.getWalletAddress(),
                request.getTimeFrame(),
                request.getRecvWindow(),
                request.getNonce());
    }

    public static class GetAddressPortfolioOverviewRequest {
        private final String binanceChainId;
        private final String walletAddress;
        private final TimeFrame timeFrame;
        private Long recvWindow;
        private String nonce;

        public String getBinanceChainId() {
            return binanceChainId;
        }

        public String getWalletAddress() {
            return walletAddress;
        }

        public TimeFrame getTimeFrame() {
            return timeFrame;
        }

        public Long getRecvWindow() {
            return recvWindow;
        }

        public String getNonce() {
            return nonce;
        }

        public GetAddressPortfolioOverviewRequest(
                String binanceChainId, String walletAddress, TimeFrame timeFrame) {
            this.binanceChainId = binanceChainId;
            this.walletAddress = walletAddress;
            this.timeFrame = timeFrame;
        }

        /**
         * Set recvWindow
         *
         * @param recvWindow Allowed time deviation in milliseconds (default: 5000, max: 60000).
         *     (optional)
         * @return GetAddressPortfolioOverviewRequest
         */
        public GetAddressPortfolioOverviewRequest recvWindow(Long recvWindow) {
            this.recvWindow = recvWindow;
            return this;
        }

        /**
         * Set nonce
         *
         * @param nonce Unique request identifier for anti-replay; falls back to X-OC-SIGN if
         *     omitted. (optional)
         * @return GetAddressPortfolioOverviewRequest
         */
        public GetAddressPortfolioOverviewRequest nonce(String nonce) {
            this.nonce = nonce;
            return this;
        }
    }

    private okhttp3.Call getAddressRecentPnLCall(
            String binanceChainId,
            String walletAddress,
            Long recvWindow,
            String nonce,
            String cursor,
            String limit)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/dex/market/portfolio/recent-pnl";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (binanceChainId != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("binanceChainId", binanceChainId));
        }

        if (walletAddress != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("walletAddress", walletAddress));
        }

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/x-www-form-urlencoded"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (!localVarFormParams.isEmpty() && localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (recvWindow != null) {
            localVarHeaderParams.put("recvWindow", localVarApiClient.parameterToString(recvWindow));
        }

        if (nonce != null) {
            localVarHeaderParams.put("nonce", localVarApiClient.parameterToString(nonce));
        }

        Set<String> localVarAuthNames = new HashSet<>();
        localVarAuthNames.add("binanceWeb3Signature");
        if (HAS_TIME_UNIT) {
            localVarAuthNames.add("timeUnit");
        }
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAddressRecentPnLValidateBeforeCall(
            String binanceChainId,
            String walletAddress,
            Long recvWindow,
            String nonce,
            String cursor,
            String limit)
            throws ApiException {
        try {
            Validator validator =
                    Validation.byDefaultProvider()
                            .configure()
                            .messageInterpolator(new ParameterMessageInterpolator())
                            .buildValidatorFactory()
                            .getValidator();
            ExecutableValidator executableValidator = validator.forExecutables();

            Object[] parameterValues = {
                binanceChainId, walletAddress, recvWindow, nonce, cursor, limit
            };
            Method method =
                    this.getClass()
                            .getMethod(
                                    "getAddressRecentPnL",
                                    String.class,
                                    String.class,
                                    Long.class,
                                    String.class,
                                    String.class,
                                    String.class);
            Set<ConstraintViolation<AddressPortfolioApi>> violations =
                    executableValidator.validateParameters(this, method, parameterValues);

            if (violations.size() == 0) {
                return getAddressRecentPnLCall(
                        binanceChainId, walletAddress, recvWindow, nonce, cursor, limit);
            } else {
                throw new ConstraintViolationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    public ApiResponse<GetAddressRecentPnLResponse> getAddressRecentPnL(
            @NotNull String binanceChainId,
            @NotNull String walletAddress,
            Long recvWindow,
            String nonce,
            String cursor,
            String limit)
            throws ApiException {
        okhttp3.Call localVarCall =
                getAddressRecentPnLValidateBeforeCall(
                        binanceChainId, walletAddress, recvWindow, nonce, cursor, limit);
        java.lang.reflect.Type localVarReturnType =
                new TypeToken<GetAddressRecentPnLResponse>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    public ApiResponse<GetAddressRecentPnLResponse> getAddressRecentPnL(
            GetAddressRecentPnLRequest request) {
        return getAddressRecentPnL(
                request.getBinanceChainId(),
                request.getWalletAddress(),
                request.getRecvWindow(),
                request.getNonce(),
                request.getCursor(),
                request.getLimit());
    }

    public static class GetAddressRecentPnLRequest {
        private final String binanceChainId;
        private final String walletAddress;
        private Long recvWindow;
        private String nonce;
        private String cursor;
        private String limit;

        public String getBinanceChainId() {
            return binanceChainId;
        }

        public String getWalletAddress() {
            return walletAddress;
        }

        public Long getRecvWindow() {
            return recvWindow;
        }

        public String getNonce() {
            return nonce;
        }

        public String getCursor() {
            return cursor;
        }

        public String getLimit() {
            return limit;
        }

        public GetAddressRecentPnLRequest(String binanceChainId, String walletAddress) {
            this.binanceChainId = binanceChainId;
            this.walletAddress = walletAddress;
        }

        /**
         * Set recvWindow
         *
         * @param recvWindow Allowed time deviation in milliseconds (default: 5000, max: 60000).
         *     (optional)
         * @return GetAddressRecentPnLRequest
         */
        public GetAddressRecentPnLRequest recvWindow(Long recvWindow) {
            this.recvWindow = recvWindow;
            return this;
        }

        /**
         * Set nonce
         *
         * @param nonce Unique request identifier for anti-replay; falls back to X-OC-SIGN if
         *     omitted. (optional)
         * @return GetAddressRecentPnLRequest
         */
        public GetAddressRecentPnLRequest nonce(String nonce) {
            this.nonce = nonce;
            return this;
        }

        /**
         * Set cursor
         *
         * @param cursor Pagination cursor. Omit or pass empty string for the first page; pass the
         *     cursor from the previous response to get the next page. (optional)
         * @return GetAddressRecentPnLRequest
         */
        public GetAddressRecentPnLRequest cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }

        /**
         * Set limit
         *
         * @param limit Number of records per page. Default 20, max 100. (optional)
         * @return GetAddressRecentPnLRequest
         */
        public GetAddressRecentPnLRequest limit(String limit) {
            this.limit = limit;
            return this;
        }
    }

    private okhttp3.Call getDexTradeHistoryCall(
            String binanceChainId,
            String walletAddress,
            Long recvWindow,
            String nonce,
            String begin,
            String end,
            String tokenContractAddress,
            OrderType type,
            String cursor,
            String limit)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/dex/market/portfolio/dex-history";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (binanceChainId != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("binanceChainId", binanceChainId));
        }

        if (walletAddress != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("walletAddress", walletAddress));
        }

        if (begin != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("begin", begin));
        }

        if (end != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("end", end));
        }

        if (tokenContractAddress != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair(
                            "tokenContractAddress", tokenContractAddress));
        }

        if (type != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("type", type));
        }

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/x-www-form-urlencoded"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (!localVarFormParams.isEmpty() && localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (recvWindow != null) {
            localVarHeaderParams.put("recvWindow", localVarApiClient.parameterToString(recvWindow));
        }

        if (nonce != null) {
            localVarHeaderParams.put("nonce", localVarApiClient.parameterToString(nonce));
        }

        Set<String> localVarAuthNames = new HashSet<>();
        localVarAuthNames.add("binanceWeb3Signature");
        if (HAS_TIME_UNIT) {
            localVarAuthNames.add("timeUnit");
        }
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getDexTradeHistoryValidateBeforeCall(
            String binanceChainId,
            String walletAddress,
            Long recvWindow,
            String nonce,
            String begin,
            String end,
            String tokenContractAddress,
            OrderType type,
            String cursor,
            String limit)
            throws ApiException {
        try {
            Validator validator =
                    Validation.byDefaultProvider()
                            .configure()
                            .messageInterpolator(new ParameterMessageInterpolator())
                            .buildValidatorFactory()
                            .getValidator();
            ExecutableValidator executableValidator = validator.forExecutables();

            Object[] parameterValues = {
                binanceChainId,
                walletAddress,
                recvWindow,
                nonce,
                begin,
                end,
                tokenContractAddress,
                type,
                cursor,
                limit
            };
            Method method =
                    this.getClass()
                            .getMethod(
                                    "getDexTradeHistory",
                                    String.class,
                                    String.class,
                                    Long.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    OrderType.class,
                                    String.class,
                                    String.class);
            Set<ConstraintViolation<AddressPortfolioApi>> violations =
                    executableValidator.validateParameters(this, method, parameterValues);

            if (violations.size() == 0) {
                return getDexTradeHistoryCall(
                        binanceChainId,
                        walletAddress,
                        recvWindow,
                        nonce,
                        begin,
                        end,
                        tokenContractAddress,
                        type,
                        cursor,
                        limit);
            } else {
                throw new ConstraintViolationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    public ApiResponse<GetDexTradeHistoryResponse> getDexTradeHistory(
            @NotNull String binanceChainId,
            @NotNull String walletAddress,
            Long recvWindow,
            String nonce,
            String begin,
            String end,
            String tokenContractAddress,
            OrderType type,
            String cursor,
            String limit)
            throws ApiException {
        okhttp3.Call localVarCall =
                getDexTradeHistoryValidateBeforeCall(
                        binanceChainId,
                        walletAddress,
                        recvWindow,
                        nonce,
                        begin,
                        end,
                        tokenContractAddress,
                        type,
                        cursor,
                        limit);
        java.lang.reflect.Type localVarReturnType =
                new TypeToken<GetDexTradeHistoryResponse>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    public ApiResponse<GetDexTradeHistoryResponse> getDexTradeHistory(
            GetDexTradeHistoryRequest request) {
        return getDexTradeHistory(
                request.getBinanceChainId(),
                request.getWalletAddress(),
                request.getRecvWindow(),
                request.getNonce(),
                request.getBegin(),
                request.getEnd(),
                request.getTokenContractAddress(),
                request.getType(),
                request.getCursor(),
                request.getLimit());
    }

    public static class GetDexTradeHistoryRequest {
        private final String binanceChainId;
        private final String walletAddress;
        private Long recvWindow;
        private String nonce;
        private String begin;
        private String end;
        private String tokenContractAddress;
        private OrderType type;
        private String cursor;
        private String limit;

        public String getBinanceChainId() {
            return binanceChainId;
        }

        public String getWalletAddress() {
            return walletAddress;
        }

        public Long getRecvWindow() {
            return recvWindow;
        }

        public String getNonce() {
            return nonce;
        }

        public String getBegin() {
            return begin;
        }

        public String getEnd() {
            return end;
        }

        public String getTokenContractAddress() {
            return tokenContractAddress;
        }

        public OrderType getType() {
            return type;
        }

        public String getCursor() {
            return cursor;
        }

        public String getLimit() {
            return limit;
        }

        public GetDexTradeHistoryRequest(String binanceChainId, String walletAddress) {
            this.binanceChainId = binanceChainId;
            this.walletAddress = walletAddress;
        }

        /**
         * Set recvWindow
         *
         * @param recvWindow Allowed time deviation in milliseconds (default: 5000, max: 60000).
         *     (optional)
         * @return GetDexTradeHistoryRequest
         */
        public GetDexTradeHistoryRequest recvWindow(Long recvWindow) {
            this.recvWindow = recvWindow;
            return this;
        }

        /**
         * Set nonce
         *
         * @param nonce Unique request identifier for anti-replay; falls back to X-OC-SIGN if
         *     omitted. (optional)
         * @return GetDexTradeHistoryRequest
         */
        public GetDexTradeHistoryRequest nonce(String nonce) {
            this.nonce = nonce;
            return this;
        }

        /**
         * Set begin
         *
         * @param begin Start timestamp (Unix milliseconds, inclusive). If both begin and end are
         *     omitted, no time filter is applied. (optional)
         * @return GetDexTradeHistoryRequest
         */
        public GetDexTradeHistoryRequest begin(String begin) {
            this.begin = begin;
            return this;
        }

        /**
         * Set end
         *
         * @param end End timestamp (Unix milliseconds, inclusive). If both begin and end are
         *     omitted, no time filter is applied. (optional)
         * @return GetDexTradeHistoryRequest
         */
        public GetDexTradeHistoryRequest end(String end) {
            this.end = end;
            return this;
        }

        /**
         * Set tokenContractAddress
         *
         * @param tokenContractAddress Filter by token contract address. Returns all tokens when
         *     omitted. (optional)
         * @return GetDexTradeHistoryRequest
         */
        public GetDexTradeHistoryRequest tokenContractAddress(String tokenContractAddress) {
            this.tokenContractAddress = tokenContractAddress;
            return this;
        }

        /**
         * Set type
         *
         * @param type Trade type filter. 1&#x3D;Buy, 2&#x3D;Sell. Omit to return all types.
         *     (optional)
         * @return GetDexTradeHistoryRequest
         */
        public GetDexTradeHistoryRequest type(OrderType type) {
            this.type = type;
            return this;
        }

        /**
         * Set cursor
         *
         * @param cursor Pagination cursor. Omit or pass empty string for the first page. (optional)
         * @return GetDexTradeHistoryRequest
         */
        public GetDexTradeHistoryRequest cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }

        /**
         * Set limit
         *
         * @param limit Number of records per page. Default 20, max 100. (optional)
         * @return GetDexTradeHistoryRequest
         */
        public GetDexTradeHistoryRequest limit(String limit) {
            this.limit = limit;
            return this;
        }
    }

    private okhttp3.Call getLeaderboardCall(
            String binanceChainId,
            TimeFrame timeFrame,
            SortBy sortBy,
            Long recvWindow,
            String nonce,
            WalletType walletType,
            String minRealizedPnlUsd,
            String maxRealizedPnlUsd,
            String minWinRatePercent,
            String maxWinRatePercent,
            String minTxs,
            String maxTxs,
            String minTxVolume,
            String maxTxVolume,
            String cursor,
            String limit)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/dex/market/leaderboard/list";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (binanceChainId != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("binanceChainId", binanceChainId));
        }

        if (timeFrame != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("timeFrame", timeFrame));
        }

        if (sortBy != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sortBy", sortBy));
        }

        if (walletType != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("walletType", walletType));
        }

        if (minRealizedPnlUsd != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("minRealizedPnlUsd", minRealizedPnlUsd));
        }

        if (maxRealizedPnlUsd != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("maxRealizedPnlUsd", maxRealizedPnlUsd));
        }

        if (minWinRatePercent != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("minWinRatePercent", minWinRatePercent));
        }

        if (maxWinRatePercent != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("maxWinRatePercent", maxWinRatePercent));
        }

        if (minTxs != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("minTxs", minTxs));
        }

        if (maxTxs != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("maxTxs", maxTxs));
        }

        if (minTxVolume != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("minTxVolume", minTxVolume));
        }

        if (maxTxVolume != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("maxTxVolume", maxTxVolume));
        }

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/x-www-form-urlencoded"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (!localVarFormParams.isEmpty() && localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (recvWindow != null) {
            localVarHeaderParams.put("recvWindow", localVarApiClient.parameterToString(recvWindow));
        }

        if (nonce != null) {
            localVarHeaderParams.put("nonce", localVarApiClient.parameterToString(nonce));
        }

        Set<String> localVarAuthNames = new HashSet<>();
        localVarAuthNames.add("binanceWeb3Signature");
        if (HAS_TIME_UNIT) {
            localVarAuthNames.add("timeUnit");
        }
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getLeaderboardValidateBeforeCall(
            String binanceChainId,
            TimeFrame timeFrame,
            SortBy sortBy,
            Long recvWindow,
            String nonce,
            WalletType walletType,
            String minRealizedPnlUsd,
            String maxRealizedPnlUsd,
            String minWinRatePercent,
            String maxWinRatePercent,
            String minTxs,
            String maxTxs,
            String minTxVolume,
            String maxTxVolume,
            String cursor,
            String limit)
            throws ApiException {
        try {
            Validator validator =
                    Validation.byDefaultProvider()
                            .configure()
                            .messageInterpolator(new ParameterMessageInterpolator())
                            .buildValidatorFactory()
                            .getValidator();
            ExecutableValidator executableValidator = validator.forExecutables();

            Object[] parameterValues = {
                binanceChainId,
                timeFrame,
                sortBy,
                recvWindow,
                nonce,
                walletType,
                minRealizedPnlUsd,
                maxRealizedPnlUsd,
                minWinRatePercent,
                maxWinRatePercent,
                minTxs,
                maxTxs,
                minTxVolume,
                maxTxVolume,
                cursor,
                limit
            };
            Method method =
                    this.getClass()
                            .getMethod(
                                    "getLeaderboard",
                                    String.class,
                                    TimeFrame.class,
                                    SortBy.class,
                                    Long.class,
                                    String.class,
                                    WalletType.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    String.class);
            Set<ConstraintViolation<AddressPortfolioApi>> violations =
                    executableValidator.validateParameters(this, method, parameterValues);

            if (violations.size() == 0) {
                return getLeaderboardCall(
                        binanceChainId,
                        timeFrame,
                        sortBy,
                        recvWindow,
                        nonce,
                        walletType,
                        minRealizedPnlUsd,
                        maxRealizedPnlUsd,
                        minWinRatePercent,
                        maxWinRatePercent,
                        minTxs,
                        maxTxs,
                        minTxVolume,
                        maxTxVolume,
                        cursor,
                        limit);
            } else {
                throw new ConstraintViolationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    public ApiResponse<GetLeaderboardResponse> getLeaderboard(
            @NotNull String binanceChainId,
            @NotNull TimeFrame timeFrame,
            @NotNull SortBy sortBy,
            Long recvWindow,
            String nonce,
            WalletType walletType,
            String minRealizedPnlUsd,
            String maxRealizedPnlUsd,
            String minWinRatePercent,
            String maxWinRatePercent,
            String minTxs,
            String maxTxs,
            String minTxVolume,
            String maxTxVolume,
            String cursor,
            String limit)
            throws ApiException {
        okhttp3.Call localVarCall =
                getLeaderboardValidateBeforeCall(
                        binanceChainId,
                        timeFrame,
                        sortBy,
                        recvWindow,
                        nonce,
                        walletType,
                        minRealizedPnlUsd,
                        maxRealizedPnlUsd,
                        minWinRatePercent,
                        maxWinRatePercent,
                        minTxs,
                        maxTxs,
                        minTxVolume,
                        maxTxVolume,
                        cursor,
                        limit);
        java.lang.reflect.Type localVarReturnType =
                new TypeToken<GetLeaderboardResponse>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    public ApiResponse<GetLeaderboardResponse> getLeaderboard(GetLeaderboardRequest request) {
        return getLeaderboard(
                request.getBinanceChainId(),
                request.getTimeFrame(),
                request.getSortBy(),
                request.getRecvWindow(),
                request.getNonce(),
                request.getWalletType(),
                request.getMinRealizedPnlUsd(),
                request.getMaxRealizedPnlUsd(),
                request.getMinWinRatePercent(),
                request.getMaxWinRatePercent(),
                request.getMinTxs(),
                request.getMaxTxs(),
                request.getMinTxVolume(),
                request.getMaxTxVolume(),
                request.getCursor(),
                request.getLimit());
    }

    public static class GetLeaderboardRequest {
        private final String binanceChainId;
        private final TimeFrame timeFrame;
        private final SortBy sortBy;
        private Long recvWindow;
        private String nonce;
        private WalletType walletType;
        private String minRealizedPnlUsd;
        private String maxRealizedPnlUsd;
        private String minWinRatePercent;
        private String maxWinRatePercent;
        private String minTxs;
        private String maxTxs;
        private String minTxVolume;
        private String maxTxVolume;
        private String cursor;
        private String limit;

        public String getBinanceChainId() {
            return binanceChainId;
        }

        public TimeFrame getTimeFrame() {
            return timeFrame;
        }

        public SortBy getSortBy() {
            return sortBy;
        }

        public Long getRecvWindow() {
            return recvWindow;
        }

        public String getNonce() {
            return nonce;
        }

        public WalletType getWalletType() {
            return walletType;
        }

        public String getMinRealizedPnlUsd() {
            return minRealizedPnlUsd;
        }

        public String getMaxRealizedPnlUsd() {
            return maxRealizedPnlUsd;
        }

        public String getMinWinRatePercent() {
            return minWinRatePercent;
        }

        public String getMaxWinRatePercent() {
            return maxWinRatePercent;
        }

        public String getMinTxs() {
            return minTxs;
        }

        public String getMaxTxs() {
            return maxTxs;
        }

        public String getMinTxVolume() {
            return minTxVolume;
        }

        public String getMaxTxVolume() {
            return maxTxVolume;
        }

        public String getCursor() {
            return cursor;
        }

        public String getLimit() {
            return limit;
        }

        public GetLeaderboardRequest(String binanceChainId, TimeFrame timeFrame, SortBy sortBy) {
            this.binanceChainId = binanceChainId;
            this.timeFrame = timeFrame;
            this.sortBy = sortBy;
        }

        /**
         * Set recvWindow
         *
         * @param recvWindow Allowed time deviation in milliseconds (default: 5000, max: 60000).
         *     (optional)
         * @return GetLeaderboardRequest
         */
        public GetLeaderboardRequest recvWindow(Long recvWindow) {
            this.recvWindow = recvWindow;
            return this;
        }

        /**
         * Set nonce
         *
         * @param nonce Unique request identifier for anti-replay; falls back to X-OC-SIGN if
         *     omitted. (optional)
         * @return GetLeaderboardRequest
         */
        public GetLeaderboardRequest nonce(String nonce) {
            this.nonce = nonce;
            return this;
        }

        /**
         * Set walletType
         *
         * @param walletType Wallet type filter, single selection only. 1&#x3D;Smart Money,
         *     2&#x3D;KOL, 3&#x3D;Hot List. Returns all types when omitted. (optional)
         * @return GetLeaderboardRequest
         */
        public GetLeaderboardRequest walletType(WalletType walletType) {
            this.walletType = walletType;
            return this;
        }

        /**
         * Set minRealizedPnlUsd
         *
         * @param minRealizedPnlUsd Minimum realized PnL filter, denominated in USD. (optional)
         * @return GetLeaderboardRequest
         */
        public GetLeaderboardRequest minRealizedPnlUsd(String minRealizedPnlUsd) {
            this.minRealizedPnlUsd = minRealizedPnlUsd;
            return this;
        }

        /**
         * Set maxRealizedPnlUsd
         *
         * @param maxRealizedPnlUsd Maximum realized PnL filter, denominated in USD. (optional)
         * @return GetLeaderboardRequest
         */
        public GetLeaderboardRequest maxRealizedPnlUsd(String maxRealizedPnlUsd) {
            this.maxRealizedPnlUsd = maxRealizedPnlUsd;
            return this;
        }

        /**
         * Set minWinRatePercent
         *
         * @param minWinRatePercent Minimum win rate filter, without percent sign. \&quot;50\&quot;
         *     means ≥50%. (optional)
         * @return GetLeaderboardRequest
         */
        public GetLeaderboardRequest minWinRatePercent(String minWinRatePercent) {
            this.minWinRatePercent = minWinRatePercent;
            return this;
        }

        /**
         * Set maxWinRatePercent
         *
         * @param maxWinRatePercent Maximum win rate filter, without percent sign. \&quot;90\&quot;
         *     means ≤90%. (optional)
         * @return GetLeaderboardRequest
         */
        public GetLeaderboardRequest maxWinRatePercent(String maxWinRatePercent) {
            this.maxWinRatePercent = maxWinRatePercent;
            return this;
        }

        /**
         * Set minTxs
         *
         * @param minTxs Minimum transaction count filter. (optional)
         * @return GetLeaderboardRequest
         */
        public GetLeaderboardRequest minTxs(String minTxs) {
            this.minTxs = minTxs;
            return this;
        }

        /**
         * Set maxTxs
         *
         * @param maxTxs Maximum transaction count filter. (optional)
         * @return GetLeaderboardRequest
         */
        public GetLeaderboardRequest maxTxs(String maxTxs) {
            this.maxTxs = maxTxs;
            return this;
        }

        /**
         * Set minTxVolume
         *
         * @param minTxVolume Minimum total transaction volume filter, denominated in USD.
         *     (optional)
         * @return GetLeaderboardRequest
         */
        public GetLeaderboardRequest minTxVolume(String minTxVolume) {
            this.minTxVolume = minTxVolume;
            return this;
        }

        /**
         * Set maxTxVolume
         *
         * @param maxTxVolume Maximum total transaction volume filter, denominated in USD.
         *     (optional)
         * @return GetLeaderboardRequest
         */
        public GetLeaderboardRequest maxTxVolume(String maxTxVolume) {
            this.maxTxVolume = maxTxVolume;
            return this;
        }

        /**
         * Set cursor
         *
         * @param cursor Pagination cursor. Omit or pass empty string for the first page. (optional)
         * @return GetLeaderboardRequest
         */
        public GetLeaderboardRequest cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }

        /**
         * Set limit
         *
         * @param limit Number of records per page. Default 50, max 50. (optional)
         * @return GetLeaderboardRequest
         */
        public GetLeaderboardRequest limit(String limit) {
            this.limit = limit;
            return this;
        }
    }

    private okhttp3.Call getPortfolioSupportedChainsCall(Long recvWindow, String nonce)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/dex/market/portfolio/supported/chain";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/x-www-form-urlencoded"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (!localVarFormParams.isEmpty() && localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (recvWindow != null) {
            localVarHeaderParams.put("recvWindow", localVarApiClient.parameterToString(recvWindow));
        }

        if (nonce != null) {
            localVarHeaderParams.put("nonce", localVarApiClient.parameterToString(nonce));
        }

        Set<String> localVarAuthNames = new HashSet<>();
        localVarAuthNames.add("binanceWeb3Signature");
        if (HAS_TIME_UNIT) {
            localVarAuthNames.add("timeUnit");
        }
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPortfolioSupportedChainsValidateBeforeCall(
            Long recvWindow, String nonce) throws ApiException {
        try {
            Validator validator =
                    Validation.byDefaultProvider()
                            .configure()
                            .messageInterpolator(new ParameterMessageInterpolator())
                            .buildValidatorFactory()
                            .getValidator();
            ExecutableValidator executableValidator = validator.forExecutables();

            Object[] parameterValues = {recvWindow, nonce};
            Method method =
                    this.getClass()
                            .getMethod("getPortfolioSupportedChains", Long.class, String.class);
            Set<ConstraintViolation<AddressPortfolioApi>> violations =
                    executableValidator.validateParameters(this, method, parameterValues);

            if (violations.size() == 0) {
                return getPortfolioSupportedChainsCall(recvWindow, nonce);
            } else {
                throw new ConstraintViolationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    public ApiResponse<GetPortfolioSupportedChainsResponse> getPortfolioSupportedChains(
            Long recvWindow, String nonce) throws ApiException {
        okhttp3.Call localVarCall =
                getPortfolioSupportedChainsValidateBeforeCall(recvWindow, nonce);
        java.lang.reflect.Type localVarReturnType =
                new TypeToken<GetPortfolioSupportedChainsResponse>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    public ApiResponse<GetPortfolioSupportedChainsResponse> getPortfolioSupportedChains(
            GetPortfolioSupportedChainsRequest request) {
        return getPortfolioSupportedChains(request.getRecvWindow(), request.getNonce());
    }

    public static class GetPortfolioSupportedChainsRequest {
        private Long recvWindow;
        private String nonce;

        public Long getRecvWindow() {
            return recvWindow;
        }

        public String getNonce() {
            return nonce;
        }

        public GetPortfolioSupportedChainsRequest() {}

        /**
         * Set recvWindow
         *
         * @param recvWindow Allowed time deviation in milliseconds (default: 5000, max: 60000).
         *     (optional)
         * @return GetPortfolioSupportedChainsRequest
         */
        public GetPortfolioSupportedChainsRequest recvWindow(Long recvWindow) {
            this.recvWindow = recvWindow;
            return this;
        }

        /**
         * Set nonce
         *
         * @param nonce Unique request identifier for anti-replay; falls back to X-OC-SIGN if
         *     omitted. (optional)
         * @return GetPortfolioSupportedChainsRequest
         */
        public GetPortfolioSupportedChainsRequest nonce(String nonce) {
            this.nonce = nonce;
            return this;
        }
    }

    private okhttp3.Call getTrackedTradesCall(
            TrackerType trackerType,
            Long recvWindow,
            String nonce,
            String walletAddress,
            String tradeType,
            String binanceChainId,
            String minVolume,
            String maxVolume,
            String minMarketCap,
            String maxMarketCap,
            Boolean isHideRiskToken,
            Integer limit)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/dex/market/address-tracker/trades";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (trackerType != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("trackerType", trackerType));
        }

        if (walletAddress != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("walletAddress", walletAddress));
        }

        if (tradeType != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("tradeType", tradeType));
        }

        if (binanceChainId != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("binanceChainId", binanceChainId));
        }

        if (minVolume != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("minVolume", minVolume));
        }

        if (maxVolume != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("maxVolume", maxVolume));
        }

        if (minMarketCap != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("minMarketCap", minMarketCap));
        }

        if (maxMarketCap != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("maxMarketCap", maxMarketCap));
        }

        if (isHideRiskToken != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("isHideRiskToken", isHideRiskToken));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/x-www-form-urlencoded"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (!localVarFormParams.isEmpty() && localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (recvWindow != null) {
            localVarHeaderParams.put("recvWindow", localVarApiClient.parameterToString(recvWindow));
        }

        if (nonce != null) {
            localVarHeaderParams.put("nonce", localVarApiClient.parameterToString(nonce));
        }

        Set<String> localVarAuthNames = new HashSet<>();
        localVarAuthNames.add("binanceWeb3Signature");
        if (HAS_TIME_UNIT) {
            localVarAuthNames.add("timeUnit");
        }
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getTrackedTradesValidateBeforeCall(
            TrackerType trackerType,
            Long recvWindow,
            String nonce,
            String walletAddress,
            String tradeType,
            String binanceChainId,
            String minVolume,
            String maxVolume,
            String minMarketCap,
            String maxMarketCap,
            Boolean isHideRiskToken,
            Integer limit)
            throws ApiException {
        try {
            Validator validator =
                    Validation.byDefaultProvider()
                            .configure()
                            .messageInterpolator(new ParameterMessageInterpolator())
                            .buildValidatorFactory()
                            .getValidator();
            ExecutableValidator executableValidator = validator.forExecutables();

            Object[] parameterValues = {
                trackerType,
                recvWindow,
                nonce,
                walletAddress,
                tradeType,
                binanceChainId,
                minVolume,
                maxVolume,
                minMarketCap,
                maxMarketCap,
                isHideRiskToken,
                limit
            };
            Method method =
                    this.getClass()
                            .getMethod(
                                    "getTrackedTrades",
                                    TrackerType.class,
                                    Long.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    String.class,
                                    Boolean.class,
                                    Integer.class);
            Set<ConstraintViolation<AddressPortfolioApi>> violations =
                    executableValidator.validateParameters(this, method, parameterValues);

            if (violations.size() == 0) {
                return getTrackedTradesCall(
                        trackerType,
                        recvWindow,
                        nonce,
                        walletAddress,
                        tradeType,
                        binanceChainId,
                        minVolume,
                        maxVolume,
                        minMarketCap,
                        maxMarketCap,
                        isHideRiskToken,
                        limit);
            } else {
                throw new ConstraintViolationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    public ApiResponse<GetTrackedTradesResponse> getTrackedTrades(
            @NotNull TrackerType trackerType,
            Long recvWindow,
            String nonce,
            String walletAddress,
            String tradeType,
            String binanceChainId,
            String minVolume,
            String maxVolume,
            String minMarketCap,
            String maxMarketCap,
            Boolean isHideRiskToken,
            Integer limit)
            throws ApiException {
        okhttp3.Call localVarCall =
                getTrackedTradesValidateBeforeCall(
                        trackerType,
                        recvWindow,
                        nonce,
                        walletAddress,
                        tradeType,
                        binanceChainId,
                        minVolume,
                        maxVolume,
                        minMarketCap,
                        maxMarketCap,
                        isHideRiskToken,
                        limit);
        java.lang.reflect.Type localVarReturnType =
                new TypeToken<GetTrackedTradesResponse>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    public ApiResponse<GetTrackedTradesResponse> getTrackedTrades(GetTrackedTradesRequest request) {
        return getTrackedTrades(
                request.getTrackerType(),
                request.getRecvWindow(),
                request.getNonce(),
                request.getWalletAddress(),
                request.getTradeType(),
                request.getBinanceChainId(),
                request.getMinVolume(),
                request.getMaxVolume(),
                request.getMinMarketCap(),
                request.getMaxMarketCap(),
                request.getIsHideRiskToken(),
                request.getLimit());
    }

    public static class GetTrackedTradesRequest {
        private final TrackerType trackerType;
        private Long recvWindow;
        private String nonce;
        private String walletAddress;
        private String tradeType;
        private String binanceChainId;
        private String minVolume;
        private String maxVolume;
        private String minMarketCap;
        private String maxMarketCap;
        private Boolean isHideRiskToken;
        private Integer limit;

        public TrackerType getTrackerType() {
            return trackerType;
        }

        public Long getRecvWindow() {
            return recvWindow;
        }

        public String getNonce() {
            return nonce;
        }

        public String getWalletAddress() {
            return walletAddress;
        }

        public String getTradeType() {
            return tradeType;
        }

        public String getBinanceChainId() {
            return binanceChainId;
        }

        public String getMinVolume() {
            return minVolume;
        }

        public String getMaxVolume() {
            return maxVolume;
        }

        public String getMinMarketCap() {
            return minMarketCap;
        }

        public String getMaxMarketCap() {
            return maxMarketCap;
        }

        public Boolean getIsHideRiskToken() {
            return isHideRiskToken;
        }

        public Integer getLimit() {
            return limit;
        }

        public GetTrackedTradesRequest(TrackerType trackerType) {
            this.trackerType = trackerType;
        }

        /**
         * Set recvWindow
         *
         * @param recvWindow Allowed time deviation in milliseconds (default: 5000, max: 60000).
         *     (optional)
         * @return GetTrackedTradesRequest
         */
        public GetTrackedTradesRequest recvWindow(Long recvWindow) {
            this.recvWindow = recvWindow;
            return this;
        }

        /**
         * Set nonce
         *
         * @param nonce Unique request identifier for anti-replay; falls back to X-OC-SIGN if
         *     omitted. (optional)
         * @return GetTrackedTradesRequest
         */
        public GetTrackedTradesRequest nonce(String nonce) {
            this.nonce = nonce;
            return this;
        }

        /**
         * Set walletAddress
         *
         * @param walletAddress Required when trackerType&#x3D;3. One or more wallet addresses,
         *     comma-separated, up to 20. EVM chains accept lowercase 42-character hex addresses;
         *     Solana accepts base58 addresses (case-sensitive). (optional)
         * @return GetTrackedTradesRequest
         */
        public GetTrackedTradesRequest walletAddress(String walletAddress) {
            this.walletAddress = walletAddress;
            return this;
        }

        /**
         * Set tradeType
         *
         * @param tradeType Trade type filter. 0&#x3D;All (default), 1&#x3D;Buy, 2&#x3D;Sell,
         *     3&#x3D;Add position, 4&#x3D;Reduce position, 5&#x3D;Open position, 6&#x3D;Close
         *     position, 7&#x3D;Transfer in, 8&#x3D;Transfer out. Multiple values comma-separated.
         *     (optional)
         * @return GetTrackedTradesRequest
         */
        public GetTrackedTradesRequest tradeType(String tradeType) {
            this.tradeType = tradeType;
            return this;
        }

        /**
         * Set binanceChainId
         *
         * @param binanceChainId Filter by chain. Returns all chains when omitted. (optional)
         * @return GetTrackedTradesRequest
         */
        public GetTrackedTradesRequest binanceChainId(String binanceChainId) {
            this.binanceChainId = binanceChainId;
            return this;
        }

        /**
         * Set minVolume
         *
         * @param minVolume Minimum trade volume filter, denominated in USD. (optional)
         * @return GetTrackedTradesRequest
         */
        public GetTrackedTradesRequest minVolume(String minVolume) {
            this.minVolume = minVolume;
            return this;
        }

        /**
         * Set maxVolume
         *
         * @param maxVolume Maximum trade volume filter, denominated in USD. (optional)
         * @return GetTrackedTradesRequest
         */
        public GetTrackedTradesRequest maxVolume(String maxVolume) {
            this.maxVolume = maxVolume;
            return this;
        }

        /**
         * Set minMarketCap
         *
         * @param minMarketCap Minimum market cap filter, denominated in USD. (optional)
         * @return GetTrackedTradesRequest
         */
        public GetTrackedTradesRequest minMarketCap(String minMarketCap) {
            this.minMarketCap = minMarketCap;
            return this;
        }

        /**
         * Set maxMarketCap
         *
         * @param maxMarketCap Maximum market cap filter, denominated in USD. (optional)
         * @return GetTrackedTradesRequest
         */
        public GetTrackedTradesRequest maxMarketCap(String maxMarketCap) {
            this.maxMarketCap = maxMarketCap;
            return this;
        }

        /**
         * Set isHideRiskToken
         *
         * @param isHideRiskToken Whether to hide risk tokens. true&#x3D;hide risk tokens (default),
         *     false&#x3D;show all tokens including risk tokens. (optional)
         * @return GetTrackedTradesRequest
         */
        public GetTrackedTradesRequest isHideRiskToken(Boolean isHideRiskToken) {
            this.isHideRiskToken = isHideRiskToken;
            return this;
        }

        /**
         * Set limit
         *
         * @param limit Maximum number of trades to return. Effective only for trackerType&#x3D;3
         *     (custom address list); trackerType&#x3D;1/2 ignore this and use the downstream public
         *     query fixed cap. Omit to use the downstream default. (optional)
         * @return GetTrackedTradesRequest
         */
        public GetTrackedTradesRequest limit(Integer limit) {
            this.limit = limit;
            return this;
        }
    }
}
