/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.api;

import com.binance.connector.client.common.ApiException;
import com.binance.connector.client.common.ApiResponse;
import com.binance.connector.client.common.Pair;
import com.binance.connector.client.common.SystemUtil;
import com.binance.connector.client.common.configuration.ClientConfiguration;
import com.binance.connector.client.common.exception.ConstraintViolationException;
import com.binance.connector.client.web3.common.ApiClient;
import com.binance.connector.client.web3_wallet.rest.model.GetWebSocketAuthTokenResponse;
import com.google.gson.reflect.TypeToken;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.constraints.*;
import jakarta.validation.executable.ExecutableValidator;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator;

public class WebSocketApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    private static final String USER_AGENT =
            String.format(
                    "binance-web3-wallet/4.2.0 (Java/%s; %s; %s)",
                    SystemUtil.getJavaVersion(), SystemUtil.getOs(), SystemUtil.getArch());
    private static final boolean HAS_TIME_UNIT = false;

    public WebSocketApi(ClientConfiguration clientConfiguration) {
        this(new ApiClient(clientConfiguration));
    }

    public WebSocketApi(ApiClient apiClient) {
        apiClient.setUserAgent(USER_AGENT);
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call getWebSocketAuthTokenCall(Long recvWindow, String nonce)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/dex/market/wss/auth/token";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/x-www-form-urlencoded"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (!localVarFormParams.isEmpty() && localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (recvWindow != null) {
            localVarHeaderParams.put("recvWindow", localVarApiClient.parameterToString(recvWindow));
        }

        if (nonce != null) {
            localVarHeaderParams.put("nonce", localVarApiClient.parameterToString(nonce));
        }

        Set<String> localVarAuthNames = new HashSet<>();
        localVarAuthNames.add("binanceWeb3Signature");
        if (HAS_TIME_UNIT) {
            localVarAuthNames.add("timeUnit");
        }
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getWebSocketAuthTokenValidateBeforeCall(Long recvWindow, String nonce)
            throws ApiException {
        try {
            Validator validator =
                    Validation.byDefaultProvider()
                            .configure()
                            .messageInterpolator(new ParameterMessageInterpolator())
                            .buildValidatorFactory()
                            .getValidator();
            ExecutableValidator executableValidator = validator.forExecutables();

            Object[] parameterValues = {recvWindow, nonce};
            Method method =
                    this.getClass().getMethod("getWebSocketAuthToken", Long.class, String.class);
            Set<ConstraintViolation<WebSocketApi>> violations =
                    executableValidator.validateParameters(this, method, parameterValues);

            if (violations.size() == 0) {
                return getWebSocketAuthTokenCall(recvWindow, nonce);
            } else {
                throw new ConstraintViolationException((Set) violations);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        } catch (SecurityException e) {
            e.printStackTrace();
            throw new ApiException(e.getMessage());
        }
    }

    public ApiResponse<GetWebSocketAuthTokenResponse> getWebSocketAuthToken(
            Long recvWindow, String nonce) throws ApiException {
        okhttp3.Call localVarCall = getWebSocketAuthTokenValidateBeforeCall(recvWindow, nonce);
        java.lang.reflect.Type localVarReturnType =
                new TypeToken<GetWebSocketAuthTokenResponse>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    public ApiResponse<GetWebSocketAuthTokenResponse> getWebSocketAuthToken(
            GetWebSocketAuthTokenRequest request) {
        return getWebSocketAuthToken(request.getRecvWindow(), request.getNonce());
    }

    public static class GetWebSocketAuthTokenRequest {
        private Long recvWindow;
        private String nonce;

        public Long getRecvWindow() {
            return recvWindow;
        }

        public String getNonce() {
            return nonce;
        }

        public GetWebSocketAuthTokenRequest() {}

        /**
         * Set recvWindow
         *
         * @param recvWindow Allowed time deviation in milliseconds (default: 5000, max: 60000).
         *     (optional)
         * @return GetWebSocketAuthTokenRequest
         */
        public GetWebSocketAuthTokenRequest recvWindow(Long recvWindow) {
            this.recvWindow = recvWindow;
            return this;
        }

        /**
         * Set nonce
         *
         * @param nonce Unique request identifier for anti-replay; falls back to X-OC-SIGN if
         *     omitted. (optional)
         * @return GetWebSocketAuthTokenRequest
         */
        public GetWebSocketAuthTokenRequest nonce(String nonce) {
            this.nonce = nonce;
            return this;
        }
    }
}
