/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Objects;
import org.hibernate.validator.constraints.*;

/** B402PaymentKindV1Extra */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class B402PaymentKindV1Extra {
    public static final String SERIALIZED_NAME_NAME = "name";

    @SerializedName(SERIALIZED_NAME_NAME)
    @jakarta.annotation.Nullable
    private String name;

    public static final String SERIALIZED_NAME_VERSION = "version";

    @SerializedName(SERIALIZED_NAME_VERSION)
    @jakarta.annotation.Nullable
    private String version;

    /** Gets or Sets assetTransferMethod */
    @JsonAdapter(AssetTransferMethodEnum.Adapter.class)
    public enum AssetTransferMethodEnum {
        EIP3009("eip3009"),

        PERMIT2_EXACT("permit2-exact"),

        PERMIT2_UPTO("permit2-upto");

        private String value;

        AssetTransferMethodEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static AssetTransferMethodEnum fromValue(String value) {
            for (AssetTransferMethodEnum b : AssetTransferMethodEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<AssetTransferMethodEnum> {
            @Override
            public void write(
                    final JsonWriter jsonWriter, final AssetTransferMethodEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public AssetTransferMethodEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return AssetTransferMethodEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            AssetTransferMethodEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_ASSET_TRANSFER_METHOD = "assetTransferMethod";

    @SerializedName(SERIALIZED_NAME_ASSET_TRANSFER_METHOD)
    @jakarta.annotation.Nullable
    private AssetTransferMethodEnum assetTransferMethod;

    public static final String SERIALIZED_NAME_FACILITATOR_ADDRESS = "facilitatorAddress";

    @SerializedName(SERIALIZED_NAME_FACILITATOR_ADDRESS)
    @jakarta.annotation.Nullable
    private String facilitatorAddress;

    public B402PaymentKindV1Extra() {}

    public B402PaymentKindV1Extra name(@jakarta.annotation.Nullable String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     */
    @jakarta.annotation.Nullable
    public String getName() {
        return name;
    }

    public void setName(@jakarta.annotation.Nullable String name) {
        this.name = name;
    }

    public B402PaymentKindV1Extra version(@jakarta.annotation.Nullable String version) {
        this.version = version;
        return this;
    }

    /**
     * Get version
     *
     * @return version
     */
    @jakarta.annotation.Nullable
    public String getVersion() {
        return version;
    }

    public void setVersion(@jakarta.annotation.Nullable String version) {
        this.version = version;
    }

    public B402PaymentKindV1Extra assetTransferMethod(
            @jakarta.annotation.Nullable AssetTransferMethodEnum assetTransferMethod) {
        this.assetTransferMethod = assetTransferMethod;
        return this;
    }

    /**
     * Get assetTransferMethod
     *
     * @return assetTransferMethod
     */
    @jakarta.annotation.Nullable
    public AssetTransferMethodEnum getAssetTransferMethod() {
        return assetTransferMethod;
    }

    public void setAssetTransferMethod(
            @jakarta.annotation.Nullable AssetTransferMethodEnum assetTransferMethod) {
        this.assetTransferMethod = assetTransferMethod;
    }

    public B402PaymentKindV1Extra facilitatorAddress(
            @jakarta.annotation.Nullable String facilitatorAddress) {
        this.facilitatorAddress = facilitatorAddress;
        return this;
    }

    /**
     * Get facilitatorAddress
     *
     * @return facilitatorAddress
     */
    @jakarta.annotation.Nullable
    public String getFacilitatorAddress() {
        return facilitatorAddress;
    }

    public void setFacilitatorAddress(@jakarta.annotation.Nullable String facilitatorAddress) {
        this.facilitatorAddress = facilitatorAddress;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        B402PaymentKindV1Extra b402PaymentKindV1Extra = (B402PaymentKindV1Extra) o;
        return Objects.equals(this.name, b402PaymentKindV1Extra.name)
                && Objects.equals(this.version, b402PaymentKindV1Extra.version)
                && Objects.equals(
                        this.assetTransferMethod, b402PaymentKindV1Extra.assetTransferMethod)
                && Objects.equals(
                        this.facilitatorAddress, b402PaymentKindV1Extra.facilitatorAddress);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, version, assetTransferMethod, facilitatorAddress);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class B402PaymentKindV1Extra {\n");
        sb.append("		name: ").append(toIndentedString(name)).append("\n");
        sb.append("		version: ").append(toIndentedString(version)).append("\n");
        sb.append("		assetTransferMethod: ")
                .append(toIndentedString(assetTransferMethod))
                .append("\n");
        sb.append("		facilitatorAddress: ")
                .append(toIndentedString(facilitatorAddress))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object nameValue = getName();
        String nameValueAsString = "";
        nameValueAsString = nameValue.toString();
        sb.append("name=").append(urlEncode(nameValueAsString)).append("");
        Object versionValue = getVersion();
        String versionValueAsString = "";
        versionValueAsString = versionValue.toString();
        sb.append("version=").append(urlEncode(versionValueAsString)).append("");
        Object assetTransferMethodValue = getAssetTransferMethod();
        String assetTransferMethodValueAsString = "";
        assetTransferMethodValueAsString = assetTransferMethodValue.toString();
        sb.append("assetTransferMethod=")
                .append(urlEncode(assetTransferMethodValueAsString))
                .append("");
        Object facilitatorAddressValue = getFacilitatorAddress();
        String facilitatorAddressValueAsString = "";
        facilitatorAddressValueAsString = facilitatorAddressValue.toString();
        sb.append("facilitatorAddress=")
                .append(urlEncode(facilitatorAddressValueAsString))
                .append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("name");
        openapiFields.add("version");
        openapiFields.add("assetTransferMethod");
        openapiFields.add("facilitatorAddress");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to B402PaymentKindV1Extra
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!B402PaymentKindV1Extra.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in B402PaymentKindV1Extra is not found in"
                                        + " the empty JSON string",
                                B402PaymentKindV1Extra.openapiRequiredFields.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull())
                && !jsonObj.get("name").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `name` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("name").toString()));
        }
        if ((jsonObj.get("version") != null && !jsonObj.get("version").isJsonNull())
                && !jsonObj.get("version").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `version` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("version").toString()));
        }
        if ((jsonObj.get("assetTransferMethod") != null
                        && !jsonObj.get("assetTransferMethod").isJsonNull())
                && !jsonObj.get("assetTransferMethod").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `assetTransferMethod` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("assetTransferMethod").toString()));
        }
        // validate the optional field `assetTransferMethod`
        if (jsonObj.get("assetTransferMethod") != null
                && !jsonObj.get("assetTransferMethod").isJsonNull()) {
            AssetTransferMethodEnum.validateJsonElement(jsonObj.get("assetTransferMethod"));
        }
        if ((jsonObj.get("facilitatorAddress") != null
                        && !jsonObj.get("facilitatorAddress").isJsonNull())
                && !jsonObj.get("facilitatorAddress").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `facilitatorAddress` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("facilitatorAddress").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!B402PaymentKindV1Extra.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'B402PaymentKindV1Extra' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<B402PaymentKindV1Extra> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(B402PaymentKindV1Extra.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<B402PaymentKindV1Extra>() {
                        @Override
                        public void write(JsonWriter out, B402PaymentKindV1Extra value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public B402PaymentKindV1Extra read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of B402PaymentKindV1Extra given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of B402PaymentKindV1Extra
     * @throws IOException if the JSON string is invalid with respect to B402PaymentKindV1Extra
     */
    public static B402PaymentKindV1Extra fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, B402PaymentKindV1Extra.class);
    }

    /**
     * Convert an instance of B402PaymentKindV1Extra to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
