/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Objects;
import org.hibernate.validator.constraints.*;

/** B402SettleRequestV1AllOfPaymentPayload */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class B402SettleRequestV1AllOfPaymentPayload {
    /** Gets or Sets x402Version */
    @JsonAdapter(X402VersionEnum.Adapter.class)
    public enum X402VersionEnum {
        X402_VERSION_1(1);

        private Integer value;

        X402VersionEnum(Integer value) {
            this.value = value;
        }

        public Integer getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static X402VersionEnum fromValue(Integer value) {
            for (X402VersionEnum b : X402VersionEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<X402VersionEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final X402VersionEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public X402VersionEnum read(final JsonReader jsonReader) throws IOException {
                Integer value = jsonReader.nextInt();
                return X402VersionEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            Integer value = jsonElement.getAsInt();
            X402VersionEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_X402_VERSION = "x402Version";

    @SerializedName(SERIALIZED_NAME_X402_VERSION)
    @jakarta.annotation.Nonnull
    private X402VersionEnum x402Version;

    /** Gets or Sets scheme */
    @JsonAdapter(SchemeEnum.Adapter.class)
    public enum SchemeEnum {
        exact("exact");

        private String value;

        SchemeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static SchemeEnum fromValue(String value) {
            for (SchemeEnum b : SchemeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<SchemeEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final SchemeEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public SchemeEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return SchemeEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            SchemeEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_SCHEME = "scheme";

    @SerializedName(SERIALIZED_NAME_SCHEME)
    @jakarta.annotation.Nonnull
    private SchemeEnum scheme;

    public static final String SERIALIZED_NAME_NETWORK = "network";

    @SerializedName(SERIALIZED_NAME_NETWORK)
    @jakarta.annotation.Nonnull
    private String network;

    public static final String SERIALIZED_NAME_PAYLOAD = "payload";

    @SerializedName(SERIALIZED_NAME_PAYLOAD)
    @jakarta.annotation.Nonnull
    private B402SettleRequestV2AllOfPaymentPayloadPayload payload;

    public B402SettleRequestV1AllOfPaymentPayload() {}

    public B402SettleRequestV1AllOfPaymentPayload x402Version(
            @jakarta.annotation.Nonnull X402VersionEnum x402Version) {
        this.x402Version = x402Version;
        return this;
    }

    /**
     * Get x402Version
     *
     * @return x402Version
     */
    @jakarta.annotation.Nonnull
    @NotNull
    public X402VersionEnum getX402Version() {
        return x402Version;
    }

    public void setX402Version(@jakarta.annotation.Nonnull X402VersionEnum x402Version) {
        this.x402Version = x402Version;
    }

    public B402SettleRequestV1AllOfPaymentPayload scheme(
            @jakarta.annotation.Nonnull SchemeEnum scheme) {
        this.scheme = scheme;
        return this;
    }

    /**
     * Get scheme
     *
     * @return scheme
     */
    @jakarta.annotation.Nonnull
    @NotNull
    public SchemeEnum getScheme() {
        return scheme;
    }

    public void setScheme(@jakarta.annotation.Nonnull SchemeEnum scheme) {
        this.scheme = scheme;
    }

    public B402SettleRequestV1AllOfPaymentPayload network(
            @jakarta.annotation.Nonnull String network) {
        this.network = network;
        return this;
    }

    /**
     * Get network
     *
     * @return network
     */
    @jakarta.annotation.Nonnull
    @NotNull
    public String getNetwork() {
        return network;
    }

    public void setNetwork(@jakarta.annotation.Nonnull String network) {
        this.network = network;
    }

    public B402SettleRequestV1AllOfPaymentPayload payload(
            @jakarta.annotation.Nonnull B402SettleRequestV2AllOfPaymentPayloadPayload payload) {
        this.payload = payload;
        return this;
    }

    /**
     * Get payload
     *
     * @return payload
     */
    @jakarta.annotation.Nonnull
    @NotNull
    @Valid
    public B402SettleRequestV2AllOfPaymentPayloadPayload getPayload() {
        return payload;
    }

    public void setPayload(
            @jakarta.annotation.Nonnull B402SettleRequestV2AllOfPaymentPayloadPayload payload) {
        this.payload = payload;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        B402SettleRequestV1AllOfPaymentPayload b402SettleRequestV1AllOfPaymentPayload =
                (B402SettleRequestV1AllOfPaymentPayload) o;
        return Objects.equals(this.x402Version, b402SettleRequestV1AllOfPaymentPayload.x402Version)
                && Objects.equals(this.scheme, b402SettleRequestV1AllOfPaymentPayload.scheme)
                && Objects.equals(this.network, b402SettleRequestV1AllOfPaymentPayload.network)
                && Objects.equals(this.payload, b402SettleRequestV1AllOfPaymentPayload.payload);
    }

    @Override
    public int hashCode() {
        return Objects.hash(x402Version, scheme, network, payload);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class B402SettleRequestV1AllOfPaymentPayload {\n");
        sb.append("		x402Version: ").append(toIndentedString(x402Version)).append("\n");
        sb.append("		scheme: ").append(toIndentedString(scheme)).append("\n");
        sb.append("		network: ").append(toIndentedString(network)).append("\n");
        sb.append("		payload: ").append(toIndentedString(payload)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object x402VersionValue = getX402Version();
        String x402VersionValueAsString = "";
        x402VersionValueAsString = x402VersionValue.toString();
        sb.append("x402Version=").append(urlEncode(x402VersionValueAsString)).append("");
        Object schemeValue = getScheme();
        String schemeValueAsString = "";
        schemeValueAsString = schemeValue.toString();
        sb.append("scheme=").append(urlEncode(schemeValueAsString)).append("");
        Object networkValue = getNetwork();
        String networkValueAsString = "";
        networkValueAsString = networkValue.toString();
        sb.append("network=").append(urlEncode(networkValueAsString)).append("");
        Object payloadValue = getPayload();
        String payloadValueAsString = "";
        payloadValueAsString = payloadValue.toString();
        sb.append("payload=").append(urlEncode(payloadValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("x402Version");
        openapiFields.add("scheme");
        openapiFields.add("network");
        openapiFields.add("payload");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("x402Version");
        openapiRequiredFields.add("scheme");
        openapiRequiredFields.add("network");
        openapiRequiredFields.add("payload");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     B402SettleRequestV1AllOfPaymentPayload
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!B402SettleRequestV1AllOfPaymentPayload.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in B402SettleRequestV1AllOfPaymentPayload"
                                        + " is not found in the empty JSON string",
                                B402SettleRequestV1AllOfPaymentPayload.openapiRequiredFields
                                        .toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : B402SettleRequestV1AllOfPaymentPayload.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the required field `x402Version`
        X402VersionEnum.validateJsonElement(jsonObj.get("x402Version"));
        if (!jsonObj.get("scheme").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `scheme` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("scheme").toString()));
        }
        // validate the required field `scheme`
        SchemeEnum.validateJsonElement(jsonObj.get("scheme"));
        if (!jsonObj.get("network").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `network` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("network").toString()));
        }
        // validate the required field `payload`
        B402SettleRequestV2AllOfPaymentPayloadPayload.validateJsonElement(jsonObj.get("payload"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!B402SettleRequestV1AllOfPaymentPayload.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'B402SettleRequestV1AllOfPaymentPayload'
                // and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<B402SettleRequestV1AllOfPaymentPayload> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(B402SettleRequestV1AllOfPaymentPayload.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<B402SettleRequestV1AllOfPaymentPayload>() {
                        @Override
                        public void write(
                                JsonWriter out, B402SettleRequestV1AllOfPaymentPayload value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public B402SettleRequestV1AllOfPaymentPayload read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of B402SettleRequestV1AllOfPaymentPayload given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of B402SettleRequestV1AllOfPaymentPayload
     * @throws IOException if the JSON string is invalid with respect to
     *     B402SettleRequestV1AllOfPaymentPayload
     */
    public static B402SettleRequestV1AllOfPaymentPayload fromJson(String jsonString)
            throws IOException {
        return JSON.getGson().fromJson(jsonString, B402SettleRequestV1AllOfPaymentPayload.class);
    }

    /**
     * Convert an instance of B402SettleRequestV1AllOfPaymentPayload to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
