/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;
import org.hibernate.validator.constraints.*;

/** B402SupportedResponseV2Data */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class B402SupportedResponseV2Data {
    public static final String SERIALIZED_NAME_KINDS = "kinds";

    @SerializedName(SERIALIZED_NAME_KINDS)
    @jakarta.annotation.Nonnull
    private List<@Valid B402SupportedDataV2KindsInner> kinds;

    public static final String SERIALIZED_NAME_EXTENSIONS = "extensions";

    @SerializedName(SERIALIZED_NAME_EXTENSIONS)
    @jakarta.annotation.Nonnull
    private List<String> extensions;

    public static final String SERIALIZED_NAME_SIGNERS = "signers";

    @SerializedName(SERIALIZED_NAME_SIGNERS)
    @jakarta.annotation.Nonnull
    private Map<String, List<String>> signers;

    public B402SupportedResponseV2Data() {}

    public B402SupportedResponseV2Data kinds(
            @jakarta.annotation.Nonnull List<@Valid B402SupportedDataV2KindsInner> kinds) {
        this.kinds = kinds;
        return this;
    }

    public B402SupportedResponseV2Data addKindsItem(B402SupportedDataV2KindsInner kindsItem) {
        if (this.kinds == null) {
            this.kinds = new ArrayList<>();
        }
        this.kinds.add(kindsItem);
        return this;
    }

    /**
     * Get kinds
     *
     * @return kinds
     */
    @jakarta.annotation.Nonnull
    @NotNull
    @Valid
    public List<@Valid B402SupportedDataV2KindsInner> getKinds() {
        return kinds;
    }

    public void setKinds(
            @jakarta.annotation.Nonnull List<@Valid B402SupportedDataV2KindsInner> kinds) {
        this.kinds = kinds;
    }

    public B402SupportedResponseV2Data extensions(
            @jakarta.annotation.Nonnull List<String> extensions) {
        this.extensions = extensions;
        return this;
    }

    public B402SupportedResponseV2Data addExtensionsItem(String extensionsItem) {
        if (this.extensions == null) {
            this.extensions = new ArrayList<>();
        }
        this.extensions.add(extensionsItem);
        return this;
    }

    /**
     * Get extensions
     *
     * @return extensions
     */
    @jakarta.annotation.Nonnull
    @NotNull
    public List<String> getExtensions() {
        return extensions;
    }

    public void setExtensions(@jakarta.annotation.Nonnull List<String> extensions) {
        this.extensions = extensions;
    }

    public B402SupportedResponseV2Data signers(
            @jakarta.annotation.Nonnull Map<String, List<String>> signers) {
        this.signers = signers;
        return this;
    }

    public B402SupportedResponseV2Data putSignersItem(String key, List<String> signersItem) {
        if (this.signers == null) {
            this.signers = new HashMap<>();
        }
        this.signers.put(key, signersItem);
        return this;
    }

    /**
     * Get signers
     *
     * @return signers
     */
    @jakarta.annotation.Nonnull
    @NotNull
    @Valid
    public Map<String, List<String>> getSigners() {
        return signers;
    }

    public void setSigners(@jakarta.annotation.Nonnull Map<String, List<String>> signers) {
        this.signers = signers;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        B402SupportedResponseV2Data b402SupportedResponseV2Data = (B402SupportedResponseV2Data) o;
        return Objects.equals(this.kinds, b402SupportedResponseV2Data.kinds)
                && Objects.equals(this.extensions, b402SupportedResponseV2Data.extensions)
                && Objects.equals(this.signers, b402SupportedResponseV2Data.signers);
    }

    @Override
    public int hashCode() {
        return Objects.hash(kinds, extensions, signers);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class B402SupportedResponseV2Data {\n");
        sb.append("		kinds: ").append(toIndentedString(kinds)).append("\n");
        sb.append("		extensions: ").append(toIndentedString(extensions)).append("\n");
        sb.append("		signers: ").append(toIndentedString(signers)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object kindsValue = getKinds();
        String kindsValueAsString = "";
        kindsValueAsString =
                (String)
                        ((Collection) kindsValue)
                                .stream().map(Object::toString).collect(Collectors.joining(","));
        sb.append("kinds=").append(urlEncode(kindsValueAsString)).append("");
        Object extensionsValue = getExtensions();
        String extensionsValueAsString = "";
        extensionsValueAsString =
                (String)
                        ((Collection) extensionsValue)
                                .stream().map(Object::toString).collect(Collectors.joining(","));
        sb.append("extensions=").append(urlEncode(extensionsValueAsString)).append("");
        Object signersValue = getSigners();
        String signersValueAsString = "";
        signersValueAsString = signersValue.toString();
        sb.append("signers=").append(urlEncode(signersValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("kinds");
        openapiFields.add("extensions");
        openapiFields.add("signers");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("kinds");
        openapiRequiredFields.add("extensions");
        openapiRequiredFields.add("signers");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     B402SupportedResponseV2Data
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!B402SupportedResponseV2Data.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in B402SupportedResponseV2Data is not"
                                        + " found in the empty JSON string",
                                B402SupportedResponseV2Data.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : B402SupportedResponseV2Data.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // ensure the json data is an array
        if (!jsonObj.get("kinds").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `kinds` to be an array in the JSON string but got"
                                    + " `%s`",
                            jsonObj.get("kinds").toString()));
        }

        JsonArray jsonArraykinds = jsonObj.getAsJsonArray("kinds");
        // validate the required field `kinds` (array)
        for (int i = 0; i < jsonArraykinds.size(); i++) {
            B402SupportedDataV2KindsInner.validateJsonElement(jsonArraykinds.get(i));
        }
        ;
        // ensure the required json array is present
        if (jsonObj.get("extensions") == null) {
            throw new IllegalArgumentException(
                    "Expected the field `linkedContent` to be an array in the JSON string but got"
                            + " `null`");
        } else if (!jsonObj.get("extensions").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `extensions` to be an array in the JSON string but"
                                    + " got `%s`",
                            jsonObj.get("extensions").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!B402SupportedResponseV2Data.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'B402SupportedResponseV2Data' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<B402SupportedResponseV2Data> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(B402SupportedResponseV2Data.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<B402SupportedResponseV2Data>() {
                        @Override
                        public void write(JsonWriter out, B402SupportedResponseV2Data value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public B402SupportedResponseV2Data read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of B402SupportedResponseV2Data given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of B402SupportedResponseV2Data
     * @throws IOException if the JSON string is invalid with respect to B402SupportedResponseV2Data
     */
    public static B402SupportedResponseV2Data fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, B402SupportedResponseV2Data.class);
    }

    /**
     * Convert an instance of B402SupportedResponseV2Data to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
