/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import org.hibernate.validator.constraints.*;
import org.openapitools.jackson.nullable.JsonNullable;

/** Fundraising round. */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class DefiProtocolInfoDtoFundRaisingInner {
    public static final String SERIALIZED_NAME_ROUND = "round";

    @SerializedName(SERIALIZED_NAME_ROUND)
    @jakarta.annotation.Nullable
    private String round;

    public static final String SERIALIZED_NAME_AMOUNT = "amount";

    @SerializedName(SERIALIZED_NAME_AMOUNT)
    @jakarta.annotation.Nullable
    private String amount;

    public static final String SERIALIZED_NAME_DATE = "date";

    @SerializedName(SERIALIZED_NAME_DATE)
    @jakarta.annotation.Nullable
    private String date;

    public static final String SERIALIZED_NAME_INVESTORS = "investors";

    @SerializedName(SERIALIZED_NAME_INVESTORS)
    @jakarta.annotation.Nullable
    private List<String> investors;

    public DefiProtocolInfoDtoFundRaisingInner() {}

    public DefiProtocolInfoDtoFundRaisingInner round(@jakarta.annotation.Nullable String round) {
        this.round = round;
        return this;
    }

    /**
     * Round name (e.g. \&quot;Strategic\&quot;).
     *
     * @return round
     */
    @jakarta.annotation.Nullable
    public String getRound() {
        return round;
    }

    public void setRound(@jakarta.annotation.Nullable String round) {
        this.round = round;
    }

    public DefiProtocolInfoDtoFundRaisingInner amount(@jakarta.annotation.Nullable String amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Amount raised. Null when not disclosed.
     *
     * @return amount
     */
    @jakarta.annotation.Nullable
    public String getAmount() {
        return amount;
    }

    public void setAmount(@jakarta.annotation.Nullable String amount) {
        this.amount = amount;
    }

    public DefiProtocolInfoDtoFundRaisingInner date(@jakarta.annotation.Nullable String date) {
        this.date = date;
        return this;
    }

    /**
     * Round date.
     *
     * @return date
     */
    @jakarta.annotation.Nullable
    public String getDate() {
        return date;
    }

    public void setDate(@jakarta.annotation.Nullable String date) {
        this.date = date;
    }

    public DefiProtocolInfoDtoFundRaisingInner investors(
            @jakarta.annotation.Nullable List<String> investors) {
        this.investors = investors;
        return this;
    }

    public DefiProtocolInfoDtoFundRaisingInner addInvestorsItem(String investorsItem) {
        if (this.investors == null) {
            this.investors = new ArrayList<>();
        }
        this.investors.add(investorsItem);
        return this;
    }

    /**
     * Investor names.
     *
     * @return investors
     */
    @jakarta.annotation.Nullable
    public List<String> getInvestors() {
        return investors;
    }

    public void setInvestors(@jakarta.annotation.Nullable List<String> investors) {
        this.investors = investors;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DefiProtocolInfoDtoFundRaisingInner defiProtocolInfoDtoFundRaisingInner =
                (DefiProtocolInfoDtoFundRaisingInner) o;
        return Objects.equals(this.round, defiProtocolInfoDtoFundRaisingInner.round)
                && Objects.equals(this.amount, defiProtocolInfoDtoFundRaisingInner.amount)
                && Objects.equals(this.date, defiProtocolInfoDtoFundRaisingInner.date)
                && Objects.equals(this.investors, defiProtocolInfoDtoFundRaisingInner.investors);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b
                || (a != null
                        && b != null
                        && a.isPresent()
                        && b.isPresent()
                        && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode() {
        return Objects.hash(round, amount, date, investors);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DefiProtocolInfoDtoFundRaisingInner {\n");
        sb.append("		round: ").append(toIndentedString(round)).append("\n");
        sb.append("		amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("		date: ").append(toIndentedString(date)).append("\n");
        sb.append("		investors: ").append(toIndentedString(investors)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object roundValue = getRound();
        String roundValueAsString = "";
        roundValueAsString = roundValue.toString();
        sb.append("round=").append(urlEncode(roundValueAsString)).append("");
        Object amountValue = getAmount();
        String amountValueAsString = "";
        amountValueAsString = amountValue.toString();
        sb.append("amount=").append(urlEncode(amountValueAsString)).append("");
        Object dateValue = getDate();
        String dateValueAsString = "";
        dateValueAsString = dateValue.toString();
        sb.append("date=").append(urlEncode(dateValueAsString)).append("");
        Object investorsValue = getInvestors();
        String investorsValueAsString = "";
        investorsValueAsString =
                (String)
                        ((Collection) investorsValue)
                                .stream().map(Object::toString).collect(Collectors.joining(","));
        sb.append("investors=").append(urlEncode(investorsValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("round");
        openapiFields.add("amount");
        openapiFields.add("date");
        openapiFields.add("investors");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     DefiProtocolInfoDtoFundRaisingInner
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!DefiProtocolInfoDtoFundRaisingInner.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in DefiProtocolInfoDtoFundRaisingInner is"
                                        + " not found in the empty JSON string",
                                DefiProtocolInfoDtoFundRaisingInner.openapiRequiredFields
                                        .toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("round") != null && !jsonObj.get("round").isJsonNull())
                && !jsonObj.get("round").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `round` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("round").toString()));
        }
        if ((jsonObj.get("amount") != null && !jsonObj.get("amount").isJsonNull())
                && !jsonObj.get("amount").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `amount` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("amount").toString()));
        }
        if ((jsonObj.get("date") != null && !jsonObj.get("date").isJsonNull())
                && !jsonObj.get("date").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `date` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("date").toString()));
        }
        // ensure the optional json data is an array if present
        if (jsonObj.get("investors") != null
                && !jsonObj.get("investors").isJsonNull()
                && !jsonObj.get("investors").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `investors` to be an array in the JSON string but"
                                    + " got `%s`",
                            jsonObj.get("investors").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DefiProtocolInfoDtoFundRaisingInner.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DefiProtocolInfoDtoFundRaisingInner' and
                // its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DefiProtocolInfoDtoFundRaisingInner> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(DefiProtocolInfoDtoFundRaisingInner.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<DefiProtocolInfoDtoFundRaisingInner>() {
                        @Override
                        public void write(JsonWriter out, DefiProtocolInfoDtoFundRaisingInner value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public DefiProtocolInfoDtoFundRaisingInner read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of DefiProtocolInfoDtoFundRaisingInner given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DefiProtocolInfoDtoFundRaisingInner
     * @throws IOException if the JSON string is invalid with respect to
     *     DefiProtocolInfoDtoFundRaisingInner
     */
    public static DefiProtocolInfoDtoFundRaisingInner fromJson(String jsonString)
            throws IOException {
        return JSON.getGson().fromJson(jsonString, DefiProtocolInfoDtoFundRaisingInner.class);
    }

    /**
     * Convert an instance of DefiProtocolInfoDtoFundRaisingInner to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
