/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Objects;
import org.hibernate.validator.constraints.*;

/** CertiK six-dimension security scores. */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class DefiProtocolInfoDtoDimensionScores {
    public static final String SERIALIZED_NAME_CODE_SECURITY = "codeSecurity";

    @SerializedName(SERIALIZED_NAME_CODE_SECURITY)
    @jakarta.annotation.Nullable
    private String codeSecurity;

    public static final String SERIALIZED_NAME_FUNDAMENTAL_HEALTH = "fundamentalHealth";

    @SerializedName(SERIALIZED_NAME_FUNDAMENTAL_HEALTH)
    @jakarta.annotation.Nullable
    private String fundamentalHealth;

    public static final String SERIALIZED_NAME_OPERATIONAL_RESILIENCE = "operationalResilience";

    @SerializedName(SERIALIZED_NAME_OPERATIONAL_RESILIENCE)
    @jakarta.annotation.Nullable
    private String operationalResilience;

    public static final String SERIALIZED_NAME_COMMUNITY_TRUST = "communityTrust";

    @SerializedName(SERIALIZED_NAME_COMMUNITY_TRUST)
    @jakarta.annotation.Nullable
    private String communityTrust;

    public static final String SERIALIZED_NAME_GOVERNANCE_STRENGTH = "governanceStrength";

    @SerializedName(SERIALIZED_NAME_GOVERNANCE_STRENGTH)
    @jakarta.annotation.Nullable
    private String governanceStrength;

    public static final String SERIALIZED_NAME_MARKET_STABILITY = "marketStability";

    @SerializedName(SERIALIZED_NAME_MARKET_STABILITY)
    @jakarta.annotation.Nullable
    private String marketStability;

    public DefiProtocolInfoDtoDimensionScores() {}

    public DefiProtocolInfoDtoDimensionScores codeSecurity(
            @jakarta.annotation.Nullable String codeSecurity) {
        this.codeSecurity = codeSecurity;
        return this;
    }

    /**
     * Code security score.
     *
     * @return codeSecurity
     */
    @jakarta.annotation.Nullable
    public String getCodeSecurity() {
        return codeSecurity;
    }

    public void setCodeSecurity(@jakarta.annotation.Nullable String codeSecurity) {
        this.codeSecurity = codeSecurity;
    }

    public DefiProtocolInfoDtoDimensionScores fundamentalHealth(
            @jakarta.annotation.Nullable String fundamentalHealth) {
        this.fundamentalHealth = fundamentalHealth;
        return this;
    }

    /**
     * Fundamental health score.
     *
     * @return fundamentalHealth
     */
    @jakarta.annotation.Nullable
    public String getFundamentalHealth() {
        return fundamentalHealth;
    }

    public void setFundamentalHealth(@jakarta.annotation.Nullable String fundamentalHealth) {
        this.fundamentalHealth = fundamentalHealth;
    }

    public DefiProtocolInfoDtoDimensionScores operationalResilience(
            @jakarta.annotation.Nullable String operationalResilience) {
        this.operationalResilience = operationalResilience;
        return this;
    }

    /**
     * Operational resilience score.
     *
     * @return operationalResilience
     */
    @jakarta.annotation.Nullable
    public String getOperationalResilience() {
        return operationalResilience;
    }

    public void setOperationalResilience(
            @jakarta.annotation.Nullable String operationalResilience) {
        this.operationalResilience = operationalResilience;
    }

    public DefiProtocolInfoDtoDimensionScores communityTrust(
            @jakarta.annotation.Nullable String communityTrust) {
        this.communityTrust = communityTrust;
        return this;
    }

    /**
     * Community trust score.
     *
     * @return communityTrust
     */
    @jakarta.annotation.Nullable
    public String getCommunityTrust() {
        return communityTrust;
    }

    public void setCommunityTrust(@jakarta.annotation.Nullable String communityTrust) {
        this.communityTrust = communityTrust;
    }

    public DefiProtocolInfoDtoDimensionScores governanceStrength(
            @jakarta.annotation.Nullable String governanceStrength) {
        this.governanceStrength = governanceStrength;
        return this;
    }

    /**
     * Governance strength score.
     *
     * @return governanceStrength
     */
    @jakarta.annotation.Nullable
    public String getGovernanceStrength() {
        return governanceStrength;
    }

    public void setGovernanceStrength(@jakarta.annotation.Nullable String governanceStrength) {
        this.governanceStrength = governanceStrength;
    }

    public DefiProtocolInfoDtoDimensionScores marketStability(
            @jakarta.annotation.Nullable String marketStability) {
        this.marketStability = marketStability;
        return this;
    }

    /**
     * Market stability score.
     *
     * @return marketStability
     */
    @jakarta.annotation.Nullable
    public String getMarketStability() {
        return marketStability;
    }

    public void setMarketStability(@jakarta.annotation.Nullable String marketStability) {
        this.marketStability = marketStability;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DefiProtocolInfoDtoDimensionScores defiProtocolInfoDtoDimensionScores =
                (DefiProtocolInfoDtoDimensionScores) o;
        return Objects.equals(this.codeSecurity, defiProtocolInfoDtoDimensionScores.codeSecurity)
                && Objects.equals(
                        this.fundamentalHealth,
                        defiProtocolInfoDtoDimensionScores.fundamentalHealth)
                && Objects.equals(
                        this.operationalResilience,
                        defiProtocolInfoDtoDimensionScores.operationalResilience)
                && Objects.equals(
                        this.communityTrust, defiProtocolInfoDtoDimensionScores.communityTrust)
                && Objects.equals(
                        this.governanceStrength,
                        defiProtocolInfoDtoDimensionScores.governanceStrength)
                && Objects.equals(
                        this.marketStability, defiProtocolInfoDtoDimensionScores.marketStability);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                codeSecurity,
                fundamentalHealth,
                operationalResilience,
                communityTrust,
                governanceStrength,
                marketStability);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DefiProtocolInfoDtoDimensionScores {\n");
        sb.append("		codeSecurity: ").append(toIndentedString(codeSecurity)).append("\n");
        sb.append("		fundamentalHealth: ").append(toIndentedString(fundamentalHealth)).append("\n");
        sb.append("		operationalResilience: ")
                .append(toIndentedString(operationalResilience))
                .append("\n");
        sb.append("		communityTrust: ").append(toIndentedString(communityTrust)).append("\n");
        sb.append("		governanceStrength: ")
                .append(toIndentedString(governanceStrength))
                .append("\n");
        sb.append("		marketStability: ").append(toIndentedString(marketStability)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object codeSecurityValue = getCodeSecurity();
        String codeSecurityValueAsString = "";
        codeSecurityValueAsString = codeSecurityValue.toString();
        sb.append("codeSecurity=").append(urlEncode(codeSecurityValueAsString)).append("");
        Object fundamentalHealthValue = getFundamentalHealth();
        String fundamentalHealthValueAsString = "";
        fundamentalHealthValueAsString = fundamentalHealthValue.toString();
        sb.append("fundamentalHealth=")
                .append(urlEncode(fundamentalHealthValueAsString))
                .append("");
        Object operationalResilienceValue = getOperationalResilience();
        String operationalResilienceValueAsString = "";
        operationalResilienceValueAsString = operationalResilienceValue.toString();
        sb.append("operationalResilience=")
                .append(urlEncode(operationalResilienceValueAsString))
                .append("");
        Object communityTrustValue = getCommunityTrust();
        String communityTrustValueAsString = "";
        communityTrustValueAsString = communityTrustValue.toString();
        sb.append("communityTrust=").append(urlEncode(communityTrustValueAsString)).append("");
        Object governanceStrengthValue = getGovernanceStrength();
        String governanceStrengthValueAsString = "";
        governanceStrengthValueAsString = governanceStrengthValue.toString();
        sb.append("governanceStrength=")
                .append(urlEncode(governanceStrengthValueAsString))
                .append("");
        Object marketStabilityValue = getMarketStability();
        String marketStabilityValueAsString = "";
        marketStabilityValueAsString = marketStabilityValue.toString();
        sb.append("marketStability=").append(urlEncode(marketStabilityValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("codeSecurity");
        openapiFields.add("fundamentalHealth");
        openapiFields.add("operationalResilience");
        openapiFields.add("communityTrust");
        openapiFields.add("governanceStrength");
        openapiFields.add("marketStability");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     DefiProtocolInfoDtoDimensionScores
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!DefiProtocolInfoDtoDimensionScores.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in DefiProtocolInfoDtoDimensionScores is"
                                        + " not found in the empty JSON string",
                                DefiProtocolInfoDtoDimensionScores.openapiRequiredFields
                                        .toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("codeSecurity") != null && !jsonObj.get("codeSecurity").isJsonNull())
                && !jsonObj.get("codeSecurity").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `codeSecurity` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("codeSecurity").toString()));
        }
        if ((jsonObj.get("fundamentalHealth") != null
                        && !jsonObj.get("fundamentalHealth").isJsonNull())
                && !jsonObj.get("fundamentalHealth").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `fundamentalHealth` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("fundamentalHealth").toString()));
        }
        if ((jsonObj.get("operationalResilience") != null
                        && !jsonObj.get("operationalResilience").isJsonNull())
                && !jsonObj.get("operationalResilience").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `operationalResilience` to be a primitive type in"
                                    + " the JSON string but got `%s`",
                            jsonObj.get("operationalResilience").toString()));
        }
        if ((jsonObj.get("communityTrust") != null && !jsonObj.get("communityTrust").isJsonNull())
                && !jsonObj.get("communityTrust").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `communityTrust` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("communityTrust").toString()));
        }
        if ((jsonObj.get("governanceStrength") != null
                        && !jsonObj.get("governanceStrength").isJsonNull())
                && !jsonObj.get("governanceStrength").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `governanceStrength` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("governanceStrength").toString()));
        }
        if ((jsonObj.get("marketStability") != null && !jsonObj.get("marketStability").isJsonNull())
                && !jsonObj.get("marketStability").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `marketStability` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("marketStability").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DefiProtocolInfoDtoDimensionScores.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DefiProtocolInfoDtoDimensionScores' and
                // its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DefiProtocolInfoDtoDimensionScores> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(DefiProtocolInfoDtoDimensionScores.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<DefiProtocolInfoDtoDimensionScores>() {
                        @Override
                        public void write(JsonWriter out, DefiProtocolInfoDtoDimensionScores value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public DefiProtocolInfoDtoDimensionScores read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of DefiProtocolInfoDtoDimensionScores given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DefiProtocolInfoDtoDimensionScores
     * @throws IOException if the JSON string is invalid with respect to
     *     DefiProtocolInfoDtoDimensionScores
     */
    public static DefiProtocolInfoDtoDimensionScores fromJson(String jsonString)
            throws IOException {
        return JSON.getGson().fromJson(jsonString, DefiProtocolInfoDtoDimensionScores.class);
    }

    /**
     * Convert an instance of DefiProtocolInfoDtoDimensionScores to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
