/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import org.hibernate.validator.constraints.*;

/** Address portfolio overview. */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class GetAddressPortfolioOverviewResponseData {
    public static final String SERIALIZED_NAME_REALIZED_PNL_USD = "realizedPnlUsd";

    @SerializedName(SERIALIZED_NAME_REALIZED_PNL_USD)
    @jakarta.annotation.Nullable
    private String realizedPnlUsd;

    public static final String SERIALIZED_NAME_REALIZED_PNL_PERCENT = "realizedPnlPercent";

    @SerializedName(SERIALIZED_NAME_REALIZED_PNL_PERCENT)
    @jakarta.annotation.Nullable
    private String realizedPnlPercent;

    public static final String SERIALIZED_NAME_DAILY_PNL = "dailyPnl";

    @SerializedName(SERIALIZED_NAME_DAILY_PNL)
    @jakarta.annotation.Nullable
    private List<@Valid GetAddressPortfolioOverviewResponseDataDailyPnlInner> dailyPnl;

    public static final String SERIALIZED_NAME_WIN_RATE = "winRate";

    @SerializedName(SERIALIZED_NAME_WIN_RATE)
    @jakarta.annotation.Nullable
    private String winRate;

    public static final String SERIALIZED_NAME_TOKEN_COUNT_BY_PNL_PERCENT =
            "tokenCountByPnlPercent";

    @SerializedName(SERIALIZED_NAME_TOKEN_COUNT_BY_PNL_PERCENT)
    @jakarta.annotation.Nullable
    private GetAddressPortfolioOverviewResponseDataTokenCountByPnlPercent tokenCountByPnlPercent;

    public static final String SERIALIZED_NAME_BUY_TX_COUNT = "buyTxCount";

    @SerializedName(SERIALIZED_NAME_BUY_TX_COUNT)
    @jakarta.annotation.Nullable
    private String buyTxCount;

    public static final String SERIALIZED_NAME_SELL_TX_COUNT = "sellTxCount";

    @SerializedName(SERIALIZED_NAME_SELL_TX_COUNT)
    @jakarta.annotation.Nullable
    private String sellTxCount;

    public static final String SERIALIZED_NAME_TOTAL_TOKEN_COUNT = "totalTokenCount";

    @SerializedName(SERIALIZED_NAME_TOTAL_TOKEN_COUNT)
    @jakarta.annotation.Nullable
    private String totalTokenCount;

    public static final String SERIALIZED_NAME_BUY_TX_VOLUME = "buyTxVolume";

    @SerializedName(SERIALIZED_NAME_BUY_TX_VOLUME)
    @jakarta.annotation.Nullable
    private String buyTxVolume;

    public static final String SERIALIZED_NAME_SELL_TX_VOLUME = "sellTxVolume";

    @SerializedName(SERIALIZED_NAME_SELL_TX_VOLUME)
    @jakarta.annotation.Nullable
    private String sellTxVolume;

    public static final String SERIALIZED_NAME_AVG_BUY_VALUE_USD = "avgBuyValueUsd";

    @SerializedName(SERIALIZED_NAME_AVG_BUY_VALUE_USD)
    @jakarta.annotation.Nullable
    private String avgBuyValueUsd;

    public static final String SERIALIZED_NAME_TOP3_PNL_TOKEN_SUM_USD = "top3PnlTokenSumUsd";

    @SerializedName(SERIALIZED_NAME_TOP3_PNL_TOKEN_SUM_USD)
    @jakarta.annotation.Nullable
    private String top3PnlTokenSumUsd;

    public static final String SERIALIZED_NAME_TOP3_PNL_TOKEN_PERCENT = "top3PnlTokenPercent";

    @SerializedName(SERIALIZED_NAME_TOP3_PNL_TOKEN_PERCENT)
    @jakarta.annotation.Nullable
    private String top3PnlTokenPercent;

    public static final String SERIALIZED_NAME_TOP_PNL_TOKEN_LIST = "topPnlTokenList";

    @SerializedName(SERIALIZED_NAME_TOP_PNL_TOKEN_LIST)
    @jakarta.annotation.Nullable
    private List<@Valid GetAddressPortfolioOverviewResponseDataTopPnlTokenListInner>
            topPnlTokenList;

    public GetAddressPortfolioOverviewResponseData() {}

    public GetAddressPortfolioOverviewResponseData realizedPnlUsd(
            @jakarta.annotation.Nullable String realizedPnlUsd) {
        this.realizedPnlUsd = realizedPnlUsd;
        return this;
    }

    /**
     * Total realized PnL within the time frame, denominated in USD. Positive means profit, negative
     * means loss.
     *
     * @return realizedPnlUsd
     */
    @jakarta.annotation.Nullable
    public String getRealizedPnlUsd() {
        return realizedPnlUsd;
    }

    public void setRealizedPnlUsd(@jakarta.annotation.Nullable String realizedPnlUsd) {
        this.realizedPnlUsd = realizedPnlUsd;
    }

    public GetAddressPortfolioOverviewResponseData realizedPnlPercent(
            @jakarta.annotation.Nullable String realizedPnlPercent) {
        this.realizedPnlPercent = realizedPnlPercent;
        return this;
    }

    /**
     * Realized PnL percentage within the time frame. \&quot;16.44\&quot; means +16.44%. No percent
     * sign included.
     *
     * @return realizedPnlPercent
     */
    @jakarta.annotation.Nullable
    public String getRealizedPnlPercent() {
        return realizedPnlPercent;
    }

    public void setRealizedPnlPercent(@jakarta.annotation.Nullable String realizedPnlPercent) {
        this.realizedPnlPercent = realizedPnlPercent;
    }

    public GetAddressPortfolioOverviewResponseData dailyPnl(
            @jakarta.annotation.Nullable
                    List<@Valid GetAddressPortfolioOverviewResponseDataDailyPnlInner> dailyPnl) {
        this.dailyPnl = dailyPnl;
        return this;
    }

    public GetAddressPortfolioOverviewResponseData addDailyPnlItem(
            GetAddressPortfolioOverviewResponseDataDailyPnlInner dailyPnlItem) {
        if (this.dailyPnl == null) {
            this.dailyPnl = new ArrayList<>();
        }
        this.dailyPnl.add(dailyPnlItem);
        return this;
    }

    /**
     * Daily realized PnL breakdown, sorted by date descending (most recent first). Number of
     * entries matches the timeFrame.
     *
     * @return dailyPnl
     */
    @jakarta.annotation.Nullable
    @Valid
    public List<@Valid GetAddressPortfolioOverviewResponseDataDailyPnlInner> getDailyPnl() {
        return dailyPnl;
    }

    public void setDailyPnl(
            @jakarta.annotation.Nullable
                    List<@Valid GetAddressPortfolioOverviewResponseDataDailyPnlInner> dailyPnl) {
        this.dailyPnl = dailyPnl;
    }

    public GetAddressPortfolioOverviewResponseData winRate(
            @jakarta.annotation.Nullable String winRate) {
        this.winRate = winRate;
        return this;
    }

    /**
     * Win rate within the time frame. \&quot;61.11\&quot; means 61.11%. No percent sign included.
     *
     * @return winRate
     */
    @jakarta.annotation.Nullable
    public String getWinRate() {
        return winRate;
    }

    public void setWinRate(@jakarta.annotation.Nullable String winRate) {
        this.winRate = winRate;
    }

    public GetAddressPortfolioOverviewResponseData tokenCountByPnlPercent(
            @jakarta.annotation.Nullable
                    GetAddressPortfolioOverviewResponseDataTokenCountByPnlPercent
                            tokenCountByPnlPercent) {
        this.tokenCountByPnlPercent = tokenCountByPnlPercent;
        return this;
    }

    /**
     * Get tokenCountByPnlPercent
     *
     * @return tokenCountByPnlPercent
     */
    @jakarta.annotation.Nullable
    @Valid
    public GetAddressPortfolioOverviewResponseDataTokenCountByPnlPercent
            getTokenCountByPnlPercent() {
        return tokenCountByPnlPercent;
    }

    public void setTokenCountByPnlPercent(
            @jakarta.annotation.Nullable
                    GetAddressPortfolioOverviewResponseDataTokenCountByPnlPercent
                            tokenCountByPnlPercent) {
        this.tokenCountByPnlPercent = tokenCountByPnlPercent;
    }

    public GetAddressPortfolioOverviewResponseData buyTxCount(
            @jakarta.annotation.Nullable String buyTxCount) {
        this.buyTxCount = buyTxCount;
        return this;
    }

    /**
     * Number of buy transactions within the time frame.
     *
     * @return buyTxCount
     */
    @jakarta.annotation.Nullable
    public String getBuyTxCount() {
        return buyTxCount;
    }

    public void setBuyTxCount(@jakarta.annotation.Nullable String buyTxCount) {
        this.buyTxCount = buyTxCount;
    }

    public GetAddressPortfolioOverviewResponseData sellTxCount(
            @jakarta.annotation.Nullable String sellTxCount) {
        this.sellTxCount = sellTxCount;
        return this;
    }

    /**
     * Number of sell transactions within the time frame.
     *
     * @return sellTxCount
     */
    @jakarta.annotation.Nullable
    public String getSellTxCount() {
        return sellTxCount;
    }

    public void setSellTxCount(@jakarta.annotation.Nullable String sellTxCount) {
        this.sellTxCount = sellTxCount;
    }

    public GetAddressPortfolioOverviewResponseData totalTokenCount(
            @jakarta.annotation.Nullable String totalTokenCount) {
        this.totalTokenCount = totalTokenCount;
        return this;
    }

    /**
     * Total number of distinct tokens traded within the time frame.
     *
     * @return totalTokenCount
     */
    @jakarta.annotation.Nullable
    public String getTotalTokenCount() {
        return totalTokenCount;
    }

    public void setTotalTokenCount(@jakarta.annotation.Nullable String totalTokenCount) {
        this.totalTokenCount = totalTokenCount;
    }

    public GetAddressPortfolioOverviewResponseData buyTxVolume(
            @jakarta.annotation.Nullable String buyTxVolume) {
        this.buyTxVolume = buyTxVolume;
        return this;
    }

    /**
     * Total buy volume within the time frame, denominated in USD.
     *
     * @return buyTxVolume
     */
    @jakarta.annotation.Nullable
    public String getBuyTxVolume() {
        return buyTxVolume;
    }

    public void setBuyTxVolume(@jakarta.annotation.Nullable String buyTxVolume) {
        this.buyTxVolume = buyTxVolume;
    }

    public GetAddressPortfolioOverviewResponseData sellTxVolume(
            @jakarta.annotation.Nullable String sellTxVolume) {
        this.sellTxVolume = sellTxVolume;
        return this;
    }

    /**
     * Total sell volume within the time frame, denominated in USD.
     *
     * @return sellTxVolume
     */
    @jakarta.annotation.Nullable
    public String getSellTxVolume() {
        return sellTxVolume;
    }

    public void setSellTxVolume(@jakarta.annotation.Nullable String sellTxVolume) {
        this.sellTxVolume = sellTxVolume;
    }

    public GetAddressPortfolioOverviewResponseData avgBuyValueUsd(
            @jakarta.annotation.Nullable String avgBuyValueUsd) {
        this.avgBuyValueUsd = avgBuyValueUsd;
        return this;
    }

    /**
     * Average buy value per transaction within the time frame, denominated in USD.
     *
     * @return avgBuyValueUsd
     */
    @jakarta.annotation.Nullable
    public String getAvgBuyValueUsd() {
        return avgBuyValueUsd;
    }

    public void setAvgBuyValueUsd(@jakarta.annotation.Nullable String avgBuyValueUsd) {
        this.avgBuyValueUsd = avgBuyValueUsd;
    }

    public GetAddressPortfolioOverviewResponseData top3PnlTokenSumUsd(
            @jakarta.annotation.Nullable String top3PnlTokenSumUsd) {
        this.top3PnlTokenSumUsd = top3PnlTokenSumUsd;
        return this;
    }

    /**
     * Total realized PnL of the top 3 profit tokens, denominated in USD.
     *
     * @return top3PnlTokenSumUsd
     */
    @jakarta.annotation.Nullable
    public String getTop3PnlTokenSumUsd() {
        return top3PnlTokenSumUsd;
    }

    public void setTop3PnlTokenSumUsd(@jakarta.annotation.Nullable String top3PnlTokenSumUsd) {
        this.top3PnlTokenSumUsd = top3PnlTokenSumUsd;
    }

    public GetAddressPortfolioOverviewResponseData top3PnlTokenPercent(
            @jakarta.annotation.Nullable String top3PnlTokenPercent) {
        this.top3PnlTokenPercent = top3PnlTokenPercent;
        return this;
    }

    /**
     * Percentage of total realized PnL contributed by the top 3 profit tokens. No percent sign
     * included.
     *
     * @return top3PnlTokenPercent
     */
    @jakarta.annotation.Nullable
    public String getTop3PnlTokenPercent() {
        return top3PnlTokenPercent;
    }

    public void setTop3PnlTokenPercent(@jakarta.annotation.Nullable String top3PnlTokenPercent) {
        this.top3PnlTokenPercent = top3PnlTokenPercent;
    }

    public GetAddressPortfolioOverviewResponseData topPnlTokenList(
            @jakarta.annotation.Nullable
                    List<@Valid GetAddressPortfolioOverviewResponseDataTopPnlTokenListInner>
                            topPnlTokenList) {
        this.topPnlTokenList = topPnlTokenList;
        return this;
    }

    public GetAddressPortfolioOverviewResponseData addTopPnlTokenListItem(
            GetAddressPortfolioOverviewResponseDataTopPnlTokenListInner topPnlTokenListItem) {
        if (this.topPnlTokenList == null) {
            this.topPnlTokenList = new ArrayList<>();
        }
        this.topPnlTokenList.add(topPnlTokenListItem);
        return this;
    }

    /**
     * Top 3 tokens by realized PnL. Returns fewer items if fewer than 3 tokens were traded.
     *
     * @return topPnlTokenList
     */
    @jakarta.annotation.Nullable
    @Valid
    public List<@Valid GetAddressPortfolioOverviewResponseDataTopPnlTokenListInner>
            getTopPnlTokenList() {
        return topPnlTokenList;
    }

    public void setTopPnlTokenList(
            @jakarta.annotation.Nullable
                    List<@Valid GetAddressPortfolioOverviewResponseDataTopPnlTokenListInner>
                            topPnlTokenList) {
        this.topPnlTokenList = topPnlTokenList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetAddressPortfolioOverviewResponseData getAddressPortfolioOverviewResponseData =
                (GetAddressPortfolioOverviewResponseData) o;
        return Objects.equals(
                        this.realizedPnlUsd, getAddressPortfolioOverviewResponseData.realizedPnlUsd)
                && Objects.equals(
                        this.realizedPnlPercent,
                        getAddressPortfolioOverviewResponseData.realizedPnlPercent)
                && Objects.equals(this.dailyPnl, getAddressPortfolioOverviewResponseData.dailyPnl)
                && Objects.equals(this.winRate, getAddressPortfolioOverviewResponseData.winRate)
                && Objects.equals(
                        this.tokenCountByPnlPercent,
                        getAddressPortfolioOverviewResponseData.tokenCountByPnlPercent)
                && Objects.equals(
                        this.buyTxCount, getAddressPortfolioOverviewResponseData.buyTxCount)
                && Objects.equals(
                        this.sellTxCount, getAddressPortfolioOverviewResponseData.sellTxCount)
                && Objects.equals(
                        this.totalTokenCount,
                        getAddressPortfolioOverviewResponseData.totalTokenCount)
                && Objects.equals(
                        this.buyTxVolume, getAddressPortfolioOverviewResponseData.buyTxVolume)
                && Objects.equals(
                        this.sellTxVolume, getAddressPortfolioOverviewResponseData.sellTxVolume)
                && Objects.equals(
                        this.avgBuyValueUsd, getAddressPortfolioOverviewResponseData.avgBuyValueUsd)
                && Objects.equals(
                        this.top3PnlTokenSumUsd,
                        getAddressPortfolioOverviewResponseData.top3PnlTokenSumUsd)
                && Objects.equals(
                        this.top3PnlTokenPercent,
                        getAddressPortfolioOverviewResponseData.top3PnlTokenPercent)
                && Objects.equals(
                        this.topPnlTokenList,
                        getAddressPortfolioOverviewResponseData.topPnlTokenList);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                realizedPnlUsd,
                realizedPnlPercent,
                dailyPnl,
                winRate,
                tokenCountByPnlPercent,
                buyTxCount,
                sellTxCount,
                totalTokenCount,
                buyTxVolume,
                sellTxVolume,
                avgBuyValueUsd,
                top3PnlTokenSumUsd,
                top3PnlTokenPercent,
                topPnlTokenList);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetAddressPortfolioOverviewResponseData {\n");
        sb.append("		realizedPnlUsd: ").append(toIndentedString(realizedPnlUsd)).append("\n");
        sb.append("		realizedPnlPercent: ")
                .append(toIndentedString(realizedPnlPercent))
                .append("\n");
        sb.append("		dailyPnl: ").append(toIndentedString(dailyPnl)).append("\n");
        sb.append("		winRate: ").append(toIndentedString(winRate)).append("\n");
        sb.append("		tokenCountByPnlPercent: ")
                .append(toIndentedString(tokenCountByPnlPercent))
                .append("\n");
        sb.append("		buyTxCount: ").append(toIndentedString(buyTxCount)).append("\n");
        sb.append("		sellTxCount: ").append(toIndentedString(sellTxCount)).append("\n");
        sb.append("		totalTokenCount: ").append(toIndentedString(totalTokenCount)).append("\n");
        sb.append("		buyTxVolume: ").append(toIndentedString(buyTxVolume)).append("\n");
        sb.append("		sellTxVolume: ").append(toIndentedString(sellTxVolume)).append("\n");
        sb.append("		avgBuyValueUsd: ").append(toIndentedString(avgBuyValueUsd)).append("\n");
        sb.append("		top3PnlTokenSumUsd: ")
                .append(toIndentedString(top3PnlTokenSumUsd))
                .append("\n");
        sb.append("		top3PnlTokenPercent: ")
                .append(toIndentedString(top3PnlTokenPercent))
                .append("\n");
        sb.append("		topPnlTokenList: ").append(toIndentedString(topPnlTokenList)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object realizedPnlUsdValue = getRealizedPnlUsd();
        String realizedPnlUsdValueAsString = "";
        realizedPnlUsdValueAsString = realizedPnlUsdValue.toString();
        sb.append("realizedPnlUsd=").append(urlEncode(realizedPnlUsdValueAsString)).append("");
        Object realizedPnlPercentValue = getRealizedPnlPercent();
        String realizedPnlPercentValueAsString = "";
        realizedPnlPercentValueAsString = realizedPnlPercentValue.toString();
        sb.append("realizedPnlPercent=")
                .append(urlEncode(realizedPnlPercentValueAsString))
                .append("");
        Object dailyPnlValue = getDailyPnl();
        String dailyPnlValueAsString = "";
        dailyPnlValueAsString =
                (String)
                        ((Collection) dailyPnlValue)
                                .stream().map(Object::toString).collect(Collectors.joining(","));
        sb.append("dailyPnl=").append(urlEncode(dailyPnlValueAsString)).append("");
        Object winRateValue = getWinRate();
        String winRateValueAsString = "";
        winRateValueAsString = winRateValue.toString();
        sb.append("winRate=").append(urlEncode(winRateValueAsString)).append("");
        Object tokenCountByPnlPercentValue = getTokenCountByPnlPercent();
        String tokenCountByPnlPercentValueAsString = "";
        tokenCountByPnlPercentValueAsString = tokenCountByPnlPercentValue.toString();
        sb.append("tokenCountByPnlPercent=")
                .append(urlEncode(tokenCountByPnlPercentValueAsString))
                .append("");
        Object buyTxCountValue = getBuyTxCount();
        String buyTxCountValueAsString = "";
        buyTxCountValueAsString = buyTxCountValue.toString();
        sb.append("buyTxCount=").append(urlEncode(buyTxCountValueAsString)).append("");
        Object sellTxCountValue = getSellTxCount();
        String sellTxCountValueAsString = "";
        sellTxCountValueAsString = sellTxCountValue.toString();
        sb.append("sellTxCount=").append(urlEncode(sellTxCountValueAsString)).append("");
        Object totalTokenCountValue = getTotalTokenCount();
        String totalTokenCountValueAsString = "";
        totalTokenCountValueAsString = totalTokenCountValue.toString();
        sb.append("totalTokenCount=").append(urlEncode(totalTokenCountValueAsString)).append("");
        Object buyTxVolumeValue = getBuyTxVolume();
        String buyTxVolumeValueAsString = "";
        buyTxVolumeValueAsString = buyTxVolumeValue.toString();
        sb.append("buyTxVolume=").append(urlEncode(buyTxVolumeValueAsString)).append("");
        Object sellTxVolumeValue = getSellTxVolume();
        String sellTxVolumeValueAsString = "";
        sellTxVolumeValueAsString = sellTxVolumeValue.toString();
        sb.append("sellTxVolume=").append(urlEncode(sellTxVolumeValueAsString)).append("");
        Object avgBuyValueUsdValue = getAvgBuyValueUsd();
        String avgBuyValueUsdValueAsString = "";
        avgBuyValueUsdValueAsString = avgBuyValueUsdValue.toString();
        sb.append("avgBuyValueUsd=").append(urlEncode(avgBuyValueUsdValueAsString)).append("");
        Object top3PnlTokenSumUsdValue = getTop3PnlTokenSumUsd();
        String top3PnlTokenSumUsdValueAsString = "";
        top3PnlTokenSumUsdValueAsString = top3PnlTokenSumUsdValue.toString();
        sb.append("top3PnlTokenSumUsd=")
                .append(urlEncode(top3PnlTokenSumUsdValueAsString))
                .append("");
        Object top3PnlTokenPercentValue = getTop3PnlTokenPercent();
        String top3PnlTokenPercentValueAsString = "";
        top3PnlTokenPercentValueAsString = top3PnlTokenPercentValue.toString();
        sb.append("top3PnlTokenPercent=")
                .append(urlEncode(top3PnlTokenPercentValueAsString))
                .append("");
        Object topPnlTokenListValue = getTopPnlTokenList();
        String topPnlTokenListValueAsString = "";
        topPnlTokenListValueAsString =
                (String)
                        ((Collection) topPnlTokenListValue)
                                .stream().map(Object::toString).collect(Collectors.joining(","));
        sb.append("topPnlTokenList=").append(urlEncode(topPnlTokenListValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("realizedPnlUsd");
        openapiFields.add("realizedPnlPercent");
        openapiFields.add("dailyPnl");
        openapiFields.add("winRate");
        openapiFields.add("tokenCountByPnlPercent");
        openapiFields.add("buyTxCount");
        openapiFields.add("sellTxCount");
        openapiFields.add("totalTokenCount");
        openapiFields.add("buyTxVolume");
        openapiFields.add("sellTxVolume");
        openapiFields.add("avgBuyValueUsd");
        openapiFields.add("top3PnlTokenSumUsd");
        openapiFields.add("top3PnlTokenPercent");
        openapiFields.add("topPnlTokenList");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     GetAddressPortfolioOverviewResponseData
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetAddressPortfolioOverviewResponseData.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in"
                                    + " GetAddressPortfolioOverviewResponseData is not found in the"
                                    + " empty JSON string",
                                GetAddressPortfolioOverviewResponseData.openapiRequiredFields
                                        .toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("realizedPnlUsd") != null && !jsonObj.get("realizedPnlUsd").isJsonNull())
                && !jsonObj.get("realizedPnlUsd").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `realizedPnlUsd` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("realizedPnlUsd").toString()));
        }
        if ((jsonObj.get("realizedPnlPercent") != null
                        && !jsonObj.get("realizedPnlPercent").isJsonNull())
                && !jsonObj.get("realizedPnlPercent").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `realizedPnlPercent` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("realizedPnlPercent").toString()));
        }
        if (jsonObj.get("dailyPnl") != null && !jsonObj.get("dailyPnl").isJsonNull()) {
            JsonArray jsonArraydailyPnl = jsonObj.getAsJsonArray("dailyPnl");
            if (jsonArraydailyPnl != null) {
                // ensure the json data is an array
                if (!jsonObj.get("dailyPnl").isJsonArray()) {
                    throw new IllegalArgumentException(
                            String.format(
                                    "Expected the field `dailyPnl` to be an array in the JSON"
                                            + " string but got `%s`",
                                    jsonObj.get("dailyPnl").toString()));
                }

                // validate the optional field `dailyPnl` (array)
                for (int i = 0; i < jsonArraydailyPnl.size(); i++) {
                    GetAddressPortfolioOverviewResponseDataDailyPnlInner.validateJsonElement(
                            jsonArraydailyPnl.get(i));
                }
                ;
            }
        }
        if ((jsonObj.get("winRate") != null && !jsonObj.get("winRate").isJsonNull())
                && !jsonObj.get("winRate").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `winRate` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("winRate").toString()));
        }
        // validate the optional field `tokenCountByPnlPercent`
        if (jsonObj.get("tokenCountByPnlPercent") != null
                && !jsonObj.get("tokenCountByPnlPercent").isJsonNull()) {
            GetAddressPortfolioOverviewResponseDataTokenCountByPnlPercent.validateJsonElement(
                    jsonObj.get("tokenCountByPnlPercent"));
        }
        if ((jsonObj.get("buyTxCount") != null && !jsonObj.get("buyTxCount").isJsonNull())
                && !jsonObj.get("buyTxCount").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `buyTxCount` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("buyTxCount").toString()));
        }
        if ((jsonObj.get("sellTxCount") != null && !jsonObj.get("sellTxCount").isJsonNull())
                && !jsonObj.get("sellTxCount").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `sellTxCount` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("sellTxCount").toString()));
        }
        if ((jsonObj.get("totalTokenCount") != null && !jsonObj.get("totalTokenCount").isJsonNull())
                && !jsonObj.get("totalTokenCount").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `totalTokenCount` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("totalTokenCount").toString()));
        }
        if ((jsonObj.get("buyTxVolume") != null && !jsonObj.get("buyTxVolume").isJsonNull())
                && !jsonObj.get("buyTxVolume").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `buyTxVolume` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("buyTxVolume").toString()));
        }
        if ((jsonObj.get("sellTxVolume") != null && !jsonObj.get("sellTxVolume").isJsonNull())
                && !jsonObj.get("sellTxVolume").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `sellTxVolume` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("sellTxVolume").toString()));
        }
        if ((jsonObj.get("avgBuyValueUsd") != null && !jsonObj.get("avgBuyValueUsd").isJsonNull())
                && !jsonObj.get("avgBuyValueUsd").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `avgBuyValueUsd` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("avgBuyValueUsd").toString()));
        }
        if ((jsonObj.get("top3PnlTokenSumUsd") != null
                        && !jsonObj.get("top3PnlTokenSumUsd").isJsonNull())
                && !jsonObj.get("top3PnlTokenSumUsd").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `top3PnlTokenSumUsd` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("top3PnlTokenSumUsd").toString()));
        }
        if ((jsonObj.get("top3PnlTokenPercent") != null
                        && !jsonObj.get("top3PnlTokenPercent").isJsonNull())
                && !jsonObj.get("top3PnlTokenPercent").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `top3PnlTokenPercent` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("top3PnlTokenPercent").toString()));
        }
        if (jsonObj.get("topPnlTokenList") != null
                && !jsonObj.get("topPnlTokenList").isJsonNull()) {
            JsonArray jsonArraytopPnlTokenList = jsonObj.getAsJsonArray("topPnlTokenList");
            if (jsonArraytopPnlTokenList != null) {
                // ensure the json data is an array
                if (!jsonObj.get("topPnlTokenList").isJsonArray()) {
                    throw new IllegalArgumentException(
                            String.format(
                                    "Expected the field `topPnlTokenList` to be an array in the"
                                            + " JSON string but got `%s`",
                                    jsonObj.get("topPnlTokenList").toString()));
                }

                // validate the optional field `topPnlTokenList` (array)
                for (int i = 0; i < jsonArraytopPnlTokenList.size(); i++) {
                    GetAddressPortfolioOverviewResponseDataTopPnlTokenListInner.validateJsonElement(
                            jsonArraytopPnlTokenList.get(i));
                }
                ;
            }
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetAddressPortfolioOverviewResponseData.class.isAssignableFrom(
                    type.getRawType())) {
                return null; // this class only serializes 'GetAddressPortfolioOverviewResponseData'
                // and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetAddressPortfolioOverviewResponseData> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(GetAddressPortfolioOverviewResponseData.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<GetAddressPortfolioOverviewResponseData>() {
                        @Override
                        public void write(
                                JsonWriter out, GetAddressPortfolioOverviewResponseData value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public GetAddressPortfolioOverviewResponseData read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of GetAddressPortfolioOverviewResponseData given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetAddressPortfolioOverviewResponseData
     * @throws IOException if the JSON string is invalid with respect to
     *     GetAddressPortfolioOverviewResponseData
     */
    public static GetAddressPortfolioOverviewResponseData fromJson(String jsonString)
            throws IOException {
        return JSON.getGson().fromJson(jsonString, GetAddressPortfolioOverviewResponseData.class);
    }

    /**
     * Convert an instance of GetAddressPortfolioOverviewResponseData to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
