/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Objects;
import org.hibernate.validator.constraints.*;

/** GetB402SupportedConfigurationsV1Request */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class GetB402SupportedConfigurationsV1Request {
    public static final String SERIALIZED_NAME_BODY = "body";

    @SerializedName(SERIALIZED_NAME_BODY)
    @jakarta.annotation.Nonnull
    private Object body;

    public GetB402SupportedConfigurationsV1Request() {}

    public GetB402SupportedConfigurationsV1Request body(@jakarta.annotation.Nonnull Object body) {
        this.body = body;
        return this;
    }

    /**
     * Get body
     *
     * @return body
     */
    @jakarta.annotation.Nonnull
    @NotNull
    public Object getBody() {
        return body;
    }

    public void setBody(@jakarta.annotation.Nonnull Object body) {
        this.body = body;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetB402SupportedConfigurationsV1Request getB402SupportedConfigurationsV1Request =
                (GetB402SupportedConfigurationsV1Request) o;
        return Objects.equals(this.body, getB402SupportedConfigurationsV1Request.body);
    }

    @Override
    public int hashCode() {
        return Objects.hash(body);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetB402SupportedConfigurationsV1Request {\n");
        sb.append("		body: ").append(toIndentedString(body)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object bodyValue = getBody();
        String bodyValueAsString = "";
        bodyValueAsString = bodyValue.toString();
        sb.append("body=").append(urlEncode(bodyValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("body");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("body");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     GetB402SupportedConfigurationsV1Request
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetB402SupportedConfigurationsV1Request.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in"
                                    + " GetB402SupportedConfigurationsV1Request is not found in the"
                                    + " empty JSON string",
                                GetB402SupportedConfigurationsV1Request.openapiRequiredFields
                                        .toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : GetB402SupportedConfigurationsV1Request.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetB402SupportedConfigurationsV1Request.class.isAssignableFrom(
                    type.getRawType())) {
                return null; // this class only serializes 'GetB402SupportedConfigurationsV1Request'
                // and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetB402SupportedConfigurationsV1Request> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(GetB402SupportedConfigurationsV1Request.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<GetB402SupportedConfigurationsV1Request>() {
                        @Override
                        public void write(
                                JsonWriter out, GetB402SupportedConfigurationsV1Request value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public GetB402SupportedConfigurationsV1Request read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of GetB402SupportedConfigurationsV1Request given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetB402SupportedConfigurationsV1Request
     * @throws IOException if the JSON string is invalid with respect to
     *     GetB402SupportedConfigurationsV1Request
     */
    public static GetB402SupportedConfigurationsV1Request fromJson(String jsonString)
            throws IOException {
        return JSON.getGson().fromJson(jsonString, GetB402SupportedConfigurationsV1Request.class);
    }

    /**
     * Convert an instance of GetB402SupportedConfigurationsV1Request to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
