/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;
import org.hibernate.validator.constraints.*;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * Position-level metadata. Present for concentrated-liquidity / locked / farming positions; null
 * otherwise. Fields are null when not applicable to the position type.
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public
class GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail {
    public static final String SERIALIZED_NAME_POSITION_INDEX = "positionIndex";

    @SerializedName(SERIALIZED_NAME_POSITION_INDEX)
    @jakarta.annotation.Nullable
    private String positionIndex;

    public static final String SERIALIZED_NAME_NFT_ID = "nftId";

    @SerializedName(SERIALIZED_NAME_NFT_ID)
    @jakarta.annotation.Nullable
    private String nftId;

    public static final String SERIALIZED_NAME_UNLOCK_TIME = "unlockTime";

    @SerializedName(SERIALIZED_NAME_UNLOCK_TIME)
    @jakarta.annotation.Nullable
    private String unlockTime;

    public static final String SERIALIZED_NAME_UNLOCK_TIME_REACHED = "unlockTimeReached";

    @SerializedName(SERIALIZED_NAME_UNLOCK_TIME_REACHED)
    @jakarta.annotation.Nullable
    private Boolean unlockTimeReached;

    public static final String SERIALIZED_NAME_TICK_LOWER = "tickLower";

    @SerializedName(SERIALIZED_NAME_TICK_LOWER)
    @jakarta.annotation.Nullable
    private String tickLower;

    public static final String SERIALIZED_NAME_TICK_UPPER = "tickUpper";

    @SerializedName(SERIALIZED_NAME_TICK_UPPER)
    @jakarta.annotation.Nullable
    private String tickUpper;

    public static final String SERIALIZED_NAME_ACTIVE = "active";

    @SerializedName(SERIALIZED_NAME_ACTIVE)
    @jakarta.annotation.Nullable
    private Boolean active;

    public static final String SERIALIZED_NAME_PROOFS = "proofs";

    @SerializedName(SERIALIZED_NAME_PROOFS)
    @jakarta.annotation.Nullable
    private Map<String, List<String>> proofs;

    public static final String SERIALIZED_NAME_STAKE_STATE = "stakeState";

    @SerializedName(SERIALIZED_NAME_STAKE_STATE)
    @jakarta.annotation.Nullable
    private String stakeState;

    public static final String SERIALIZED_NAME_CLAIM_TYPES = "claimTypes";

    @SerializedName(SERIALIZED_NAME_CLAIM_TYPES)
    @jakarta.annotation.Nullable
    private List<String> claimTypes;

    public static final String SERIALIZED_NAME_REDEMPTION_ID = "redemptionId";

    @SerializedName(SERIALIZED_NAME_REDEMPTION_ID)
    @jakarta.annotation.Nullable
    private String redemptionId;

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail() {}

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            positionIndex(@jakarta.annotation.Nullable String positionIndex) {
        this.positionIndex = positionIndex;
        return this;
    }

    /**
     * Position index (e.g. the Uniswap-V3-style position number).
     *
     * @return positionIndex
     */
    @jakarta.annotation.Nullable
    public String getPositionIndex() {
        return positionIndex;
    }

    public void setPositionIndex(@jakarta.annotation.Nullable String positionIndex) {
        this.positionIndex = positionIndex;
    }

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            nftId(@jakarta.annotation.Nullable String nftId) {
        this.nftId = nftId;
        return this;
    }

    /**
     * NFT token ID for concentrated-liquidity positions, prefixed with &#x60;#&#x60; (e.g.
     * &#x60;\&quot;#7225901\&quot;&#x60;). Null for non-NFT positions. The &#x60;#&#x60; prefix may
     * be passed as-is to a transaction build endpoint (&#x60;lp-add&#x60; / &#x60;lp-remove&#x60; /
     * &#x60;claim&#x60; &#x60;LP_FEE&#x60;) — the service strips it automatically; passing the raw
     * id without &#x60;#&#x60; is also accepted.
     *
     * @return nftId
     */
    @jakarta.annotation.Nullable
    public String getNftId() {
        return nftId;
    }

    public void setNftId(@jakarta.annotation.Nullable String nftId) {
        this.nftId = nftId;
    }

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            unlockTime(@jakarta.annotation.Nullable String unlockTime) {
        this.unlockTime = unlockTime;
        return this;
    }

    /**
     * Unix timestamp (seconds) when the position unlocks. Null if no lock.
     *
     * @return unlockTime
     */
    @jakarta.annotation.Nullable
    public String getUnlockTime() {
        return unlockTime;
    }

    public void setUnlockTime(@jakarta.annotation.Nullable String unlockTime) {
        this.unlockTime = unlockTime;
    }

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            unlockTimeReached(@jakarta.annotation.Nullable Boolean unlockTimeReached) {
        this.unlockTimeReached = unlockTimeReached;
        return this;
    }

    /**
     * Whether the unlock time has been reached.
     *
     * @return unlockTimeReached
     */
    @jakarta.annotation.Nullable
    public Boolean getUnlockTimeReached() {
        return unlockTimeReached;
    }

    public void setUnlockTimeReached(@jakarta.annotation.Nullable Boolean unlockTimeReached) {
        this.unlockTimeReached = unlockTimeReached;
    }

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            tickLower(@jakarta.annotation.Nullable String tickLower) {
        this.tickLower = tickLower;
        return this;
    }

    /**
     * Lower tick bound for concentrated-liquidity positions.
     *
     * @return tickLower
     */
    @jakarta.annotation.Nullable
    public String getTickLower() {
        return tickLower;
    }

    public void setTickLower(@jakarta.annotation.Nullable String tickLower) {
        this.tickLower = tickLower;
    }

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            tickUpper(@jakarta.annotation.Nullable String tickUpper) {
        this.tickUpper = tickUpper;
        return this;
    }

    /**
     * Upper tick bound for concentrated-liquidity positions.
     *
     * @return tickUpper
     */
    @jakarta.annotation.Nullable
    public String getTickUpper() {
        return tickUpper;
    }

    public void setTickUpper(@jakarta.annotation.Nullable String tickUpper) {
        this.tickUpper = tickUpper;
    }

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            active(@jakarta.annotation.Nullable Boolean active) {
        this.active = active;
        return this;
    }

    /**
     * Whether the position is currently in-range (active).
     *
     * @return active
     */
    @jakarta.annotation.Nullable
    public Boolean getActive() {
        return active;
    }

    public void setActive(@jakarta.annotation.Nullable Boolean active) {
        this.active = active;
    }

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            proofs(@jakarta.annotation.Nullable Map<String, List<String>> proofs) {
        this.proofs = proofs;
        return this;
    }

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            putProofsItem(String key, List<String> proofsItem) {
        if (this.proofs == null) {
            this.proofs = new HashMap<>();
        }
        this.proofs.put(key, proofsItem);
        return this;
    }

    /**
     * Merkle proofs keyed by reward token address. Required when claiming PancakeSwap Infinity (V4)
     * rewards.
     *
     * @return proofs
     */
    @jakarta.annotation.Nullable
    @Valid
    public Map<String, List<String>> getProofs() {
        return proofs;
    }

    public void setProofs(@jakarta.annotation.Nullable Map<String, List<String>> proofs) {
        this.proofs = proofs;
    }

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            stakeState(@jakarta.annotation.Nullable String stakeState) {
        this.stakeState = stakeState;
        return this;
    }

    /**
     * Staking lifecycle state. Complete value set: active (earning), deactivating (unstaking in
     * progress, rewards stop), inactive (fully unstaked).
     *
     * @return stakeState
     */
    @jakarta.annotation.Nullable
    public String getStakeState() {
        return stakeState;
    }

    public void setStakeState(@jakarta.annotation.Nullable String stakeState) {
        this.stakeState = stakeState;
    }

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            claimTypes(@jakarta.annotation.Nullable List<String> claimTypes) {
        this.claimTypes = claimTypes;
        return this;
    }

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            addClaimTypesItem(String claimTypesItem) {
        if (this.claimTypes == null) {
            this.claimTypes = new ArrayList<>();
        }
        this.claimTypes.add(claimTypesItem);
        return this;
    }

    /**
     * Claim types available for this position. Values map to the &#x60;claimType&#x60; field of
     * &#x60;POST /transaction/claim&#x60; and determine which companion fields a claim requires.
     *
     * @return claimTypes
     */
    @jakarta.annotation.Nullable
    public List<String> getClaimTypes() {
        return claimTypes;
    }

    public void setClaimTypes(@jakarta.annotation.Nullable List<String> claimTypes) {
        this.claimTypes = claimTypes;
    }

    public
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            redemptionId(@jakarta.annotation.Nullable String redemptionId) {
        this.redemptionId = redemptionId;
        return this;
    }

    /**
     * Redemption record ID (for pending redemptions). Null when not a pending redemption.
     *
     * @return redemptionId
     */
    @jakarta.annotation.Nullable
    public String getRedemptionId() {
        return redemptionId;
    }

    public void setRedemptionId(@jakarta.annotation.Nullable String redemptionId) {
        this.redemptionId = redemptionId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                getDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail =
                        (GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail)
                                o;
        return Objects.equals(
                        this.positionIndex,
                        getDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                .positionIndex)
                && Objects.equals(
                        this.nftId,
                        getDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                .nftId)
                && Objects.equals(
                        this.unlockTime,
                        getDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                .unlockTime)
                && Objects.equals(
                        this.unlockTimeReached,
                        getDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                .unlockTimeReached)
                && Objects.equals(
                        this.tickLower,
                        getDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                .tickLower)
                && Objects.equals(
                        this.tickUpper,
                        getDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                .tickUpper)
                && Objects.equals(
                        this.active,
                        getDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                .active)
                && Objects.equals(
                        this.proofs,
                        getDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                .proofs)
                && Objects.equals(
                        this.stakeState,
                        getDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                .stakeState)
                && Objects.equals(
                        this.claimTypes,
                        getDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                .claimTypes)
                && Objects.equals(
                        this.redemptionId,
                        getDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                .redemptionId);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b
                || (a != null
                        && b != null
                        && a.isPresent()
                        && b.isPresent()
                        && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                positionIndex,
                nftId,
                unlockTime,
                unlockTimeReached,
                tickLower,
                tickUpper,
                active,
                proofs,
                stakeState,
                claimTypes,
                redemptionId);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(
                "class"
                    + " GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail"
                    + " {\n");
        sb.append("		positionIndex: ").append(toIndentedString(positionIndex)).append("\n");
        sb.append("		nftId: ").append(toIndentedString(nftId)).append("\n");
        sb.append("		unlockTime: ").append(toIndentedString(unlockTime)).append("\n");
        sb.append("		unlockTimeReached: ").append(toIndentedString(unlockTimeReached)).append("\n");
        sb.append("		tickLower: ").append(toIndentedString(tickLower)).append("\n");
        sb.append("		tickUpper: ").append(toIndentedString(tickUpper)).append("\n");
        sb.append("		active: ").append(toIndentedString(active)).append("\n");
        sb.append("		proofs: ").append(toIndentedString(proofs)).append("\n");
        sb.append("		stakeState: ").append(toIndentedString(stakeState)).append("\n");
        sb.append("		claimTypes: ").append(toIndentedString(claimTypes)).append("\n");
        sb.append("		redemptionId: ").append(toIndentedString(redemptionId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object positionIndexValue = getPositionIndex();
        String positionIndexValueAsString = "";
        positionIndexValueAsString = positionIndexValue.toString();
        sb.append("positionIndex=").append(urlEncode(positionIndexValueAsString)).append("");
        Object nftIdValue = getNftId();
        String nftIdValueAsString = "";
        nftIdValueAsString = nftIdValue.toString();
        sb.append("nftId=").append(urlEncode(nftIdValueAsString)).append("");
        Object unlockTimeValue = getUnlockTime();
        String unlockTimeValueAsString = "";
        unlockTimeValueAsString = unlockTimeValue.toString();
        sb.append("unlockTime=").append(urlEncode(unlockTimeValueAsString)).append("");
        Object unlockTimeReachedValue = getUnlockTimeReached();
        String unlockTimeReachedValueAsString = "";
        unlockTimeReachedValueAsString = unlockTimeReachedValue.toString();
        sb.append("unlockTimeReached=")
                .append(urlEncode(unlockTimeReachedValueAsString))
                .append("");
        Object tickLowerValue = getTickLower();
        String tickLowerValueAsString = "";
        tickLowerValueAsString = tickLowerValue.toString();
        sb.append("tickLower=").append(urlEncode(tickLowerValueAsString)).append("");
        Object tickUpperValue = getTickUpper();
        String tickUpperValueAsString = "";
        tickUpperValueAsString = tickUpperValue.toString();
        sb.append("tickUpper=").append(urlEncode(tickUpperValueAsString)).append("");
        Object activeValue = getActive();
        String activeValueAsString = "";
        activeValueAsString = activeValue.toString();
        sb.append("active=").append(urlEncode(activeValueAsString)).append("");
        Object proofsValue = getProofs();
        String proofsValueAsString = "";
        proofsValueAsString = proofsValue.toString();
        sb.append("proofs=").append(urlEncode(proofsValueAsString)).append("");
        Object stakeStateValue = getStakeState();
        String stakeStateValueAsString = "";
        stakeStateValueAsString = stakeStateValue.toString();
        sb.append("stakeState=").append(urlEncode(stakeStateValueAsString)).append("");
        Object claimTypesValue = getClaimTypes();
        String claimTypesValueAsString = "";
        claimTypesValueAsString =
                (String)
                        ((Collection) claimTypesValue)
                                .stream().map(Object::toString).collect(Collectors.joining(","));
        sb.append("claimTypes=").append(urlEncode(claimTypesValueAsString)).append("");
        Object redemptionIdValue = getRedemptionId();
        String redemptionIdValueAsString = "";
        redemptionIdValueAsString = redemptionIdValue.toString();
        sb.append("redemptionId=").append(urlEncode(redemptionIdValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("positionIndex");
        openapiFields.add("nftId");
        openapiFields.add("unlockTime");
        openapiFields.add("unlockTimeReached");
        openapiFields.add("tickLower");
        openapiFields.add("tickUpper");
        openapiFields.add("active");
        openapiFields.add("proofs");
        openapiFields.add("stakeState");
        openapiFields.add("claimTypes");
        openapiFields.add("redemptionId");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                    .openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in"
                                    + " GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail"
                                    + " is not found in the empty JSON string",
                                GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                        .openapiRequiredFields
                                        .toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("positionIndex") != null && !jsonObj.get("positionIndex").isJsonNull())
                && !jsonObj.get("positionIndex").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `positionIndex` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("positionIndex").toString()));
        }
        if ((jsonObj.get("nftId") != null && !jsonObj.get("nftId").isJsonNull())
                && !jsonObj.get("nftId").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `nftId` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("nftId").toString()));
        }
        if ((jsonObj.get("unlockTime") != null && !jsonObj.get("unlockTime").isJsonNull())
                && !jsonObj.get("unlockTime").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `unlockTime` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("unlockTime").toString()));
        }
        if ((jsonObj.get("tickLower") != null && !jsonObj.get("tickLower").isJsonNull())
                && !jsonObj.get("tickLower").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `tickLower` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("tickLower").toString()));
        }
        if ((jsonObj.get("tickUpper") != null && !jsonObj.get("tickUpper").isJsonNull())
                && !jsonObj.get("tickUpper").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `tickUpper` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("tickUpper").toString()));
        }
        if ((jsonObj.get("stakeState") != null && !jsonObj.get("stakeState").isJsonNull())
                && !jsonObj.get("stakeState").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `stakeState` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("stakeState").toString()));
        }
        // ensure the optional json data is an array if present
        if (jsonObj.get("claimTypes") != null
                && !jsonObj.get("claimTypes").isJsonNull()
                && !jsonObj.get("claimTypes").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `claimTypes` to be an array in the JSON string but"
                                    + " got `%s`",
                            jsonObj.get("claimTypes").toString()));
        }
        if ((jsonObj.get("redemptionId") != null && !jsonObj.get("redemptionId").isJsonNull())
                && !jsonObj.get("redemptionId").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `redemptionId` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("redemptionId").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                    .class
                    .isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes
                // 'GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<
                            GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail>
                    thisAdapter =
                            gson.getDelegateAdapter(
                                    this,
                                    TypeToken.get(
                                            GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                                    .class));

            return (TypeAdapter<T>)
                    new TypeAdapter<
                            GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail>() {
                        @Override
                        public void write(
                                JsonWriter out,
                                GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                        value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public
                        GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of
     * GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     * given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of
     *     GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     * @throws IOException if the JSON string is invalid with respect to
     *     GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     */
    public static
    GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
            fromJson(String jsonString) throws IOException {
        return JSON.getGson()
                .fromJson(
                        jsonString,
                        GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
                                .class);
    }

    /**
     * Convert an instance of
     * GetDeFiPositionsResponseDataAddressListInnerProtocolListInnerPoolListInnerPositionCollectionListInnerPositionListInnerPositionDetail
     * to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
