/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Objects;
import org.hibernate.validator.constraints.*;

/** GetDexTradeHistoryResponseDataTransactionListInner */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class GetDexTradeHistoryResponseDataTransactionListInner {
    public static final String SERIALIZED_NAME_TYPE = "type";

    @SerializedName(SERIALIZED_NAME_TYPE)
    @jakarta.annotation.Nullable
    private String type;

    public static final String SERIALIZED_NAME_BINANCE_CHAIN_ID = "binanceChainId";

    @SerializedName(SERIALIZED_NAME_BINANCE_CHAIN_ID)
    @jakarta.annotation.Nullable
    private String binanceChainId;

    public static final String SERIALIZED_NAME_TOKEN_CONTRACT_ADDRESS = "tokenContractAddress";

    @SerializedName(SERIALIZED_NAME_TOKEN_CONTRACT_ADDRESS)
    @jakarta.annotation.Nullable
    private String tokenContractAddress;

    public static final String SERIALIZED_NAME_TOKEN_SYMBOL = "tokenSymbol";

    @SerializedName(SERIALIZED_NAME_TOKEN_SYMBOL)
    @jakarta.annotation.Nullable
    private String tokenSymbol;

    public static final String SERIALIZED_NAME_VALUE_USD = "valueUsd";

    @SerializedName(SERIALIZED_NAME_VALUE_USD)
    @jakarta.annotation.Nullable
    private String valueUsd;

    public static final String SERIALIZED_NAME_AMOUNT = "amount";

    @SerializedName(SERIALIZED_NAME_AMOUNT)
    @jakarta.annotation.Nullable
    private String amount;

    public static final String SERIALIZED_NAME_PRICE = "price";

    @SerializedName(SERIALIZED_NAME_PRICE)
    @jakarta.annotation.Nullable
    private String price;

    public static final String SERIALIZED_NAME_MARKET_CAP = "marketCap";

    @SerializedName(SERIALIZED_NAME_MARKET_CAP)
    @jakarta.annotation.Nullable
    private String marketCap;

    public static final String SERIALIZED_NAME_TX_HASH = "txHash";

    @SerializedName(SERIALIZED_NAME_TX_HASH)
    @jakarta.annotation.Nullable
    private String txHash;

    public static final String SERIALIZED_NAME_CHAIN_LOGO_URL = "chainLogoUrl";

    @SerializedName(SERIALIZED_NAME_CHAIN_LOGO_URL)
    @jakarta.annotation.Nullable
    private String chainLogoUrl;

    public static final String SERIALIZED_NAME_TIME = "time";

    @SerializedName(SERIALIZED_NAME_TIME)
    @jakarta.annotation.Nullable
    private String time;

    public GetDexTradeHistoryResponseDataTransactionListInner() {}

    public GetDexTradeHistoryResponseDataTransactionListInner type(
            @jakarta.annotation.Nullable String type) {
        this.type = type;
        return this;
    }

    /**
     * Trade type. 1&#x3D;Buy, 2&#x3D;Sell.
     *
     * @return type
     */
    @jakarta.annotation.Nullable
    public String getType() {
        return type;
    }

    public void setType(@jakarta.annotation.Nullable String type) {
        this.type = type;
    }

    public GetDexTradeHistoryResponseDataTransactionListInner binanceChainId(
            @jakarta.annotation.Nullable String binanceChainId) {
        this.binanceChainId = binanceChainId;
        return this;
    }

    /**
     * Unique chain identifier.
     *
     * @return binanceChainId
     */
    @jakarta.annotation.Nullable
    public String getBinanceChainId() {
        return binanceChainId;
    }

    public void setBinanceChainId(@jakarta.annotation.Nullable String binanceChainId) {
        this.binanceChainId = binanceChainId;
    }

    public GetDexTradeHistoryResponseDataTransactionListInner tokenContractAddress(
            @jakarta.annotation.Nullable String tokenContractAddress) {
        this.tokenContractAddress = tokenContractAddress;
        return this;
    }

    /**
     * Token contract address. EVM addresses are lowercase; Solana addresses are case-sensitive.
     *
     * @return tokenContractAddress
     */
    @jakarta.annotation.Nullable
    public String getTokenContractAddress() {
        return tokenContractAddress;
    }

    public void setTokenContractAddress(@jakarta.annotation.Nullable String tokenContractAddress) {
        this.tokenContractAddress = tokenContractAddress;
    }

    public GetDexTradeHistoryResponseDataTransactionListInner tokenSymbol(
            @jakarta.annotation.Nullable String tokenSymbol) {
        this.tokenSymbol = tokenSymbol;
        return this;
    }

    /**
     * Token symbol.
     *
     * @return tokenSymbol
     */
    @jakarta.annotation.Nullable
    public String getTokenSymbol() {
        return tokenSymbol;
    }

    public void setTokenSymbol(@jakarta.annotation.Nullable String tokenSymbol) {
        this.tokenSymbol = tokenSymbol;
    }

    public GetDexTradeHistoryResponseDataTransactionListInner valueUsd(
            @jakarta.annotation.Nullable String valueUsd) {
        this.valueUsd = valueUsd;
        return this;
    }

    /**
     * Transaction value, denominated in USD.
     *
     * @return valueUsd
     */
    @jakarta.annotation.Nullable
    public String getValueUsd() {
        return valueUsd;
    }

    public void setValueUsd(@jakarta.annotation.Nullable String valueUsd) {
        this.valueUsd = valueUsd;
    }

    public GetDexTradeHistoryResponseDataTransactionListInner amount(
            @jakarta.annotation.Nullable String amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Token quantity involved in this transaction (token units).
     *
     * @return amount
     */
    @jakarta.annotation.Nullable
    public String getAmount() {
        return amount;
    }

    public void setAmount(@jakarta.annotation.Nullable String amount) {
        this.amount = amount;
    }

    public GetDexTradeHistoryResponseDataTransactionListInner price(
            @jakarta.annotation.Nullable String price) {
        this.price = price;
        return this;
    }

    /**
     * Execution price of this transaction, denominated in USD.
     *
     * @return price
     */
    @jakarta.annotation.Nullable
    public String getPrice() {
        return price;
    }

    public void setPrice(@jakarta.annotation.Nullable String price) {
        this.price = price;
    }

    public GetDexTradeHistoryResponseDataTransactionListInner marketCap(
            @jakarta.annotation.Nullable String marketCap) {
        this.marketCap = marketCap;
        return this;
    }

    /**
     * Token market cap at the time of this transaction, denominated in USD.
     *
     * @return marketCap
     */
    @jakarta.annotation.Nullable
    public String getMarketCap() {
        return marketCap;
    }

    public void setMarketCap(@jakarta.annotation.Nullable String marketCap) {
        this.marketCap = marketCap;
    }

    public GetDexTradeHistoryResponseDataTransactionListInner txHash(
            @jakarta.annotation.Nullable String txHash) {
        this.txHash = txHash;
        return this;
    }

    /**
     * On-chain transaction hash.
     *
     * @return txHash
     */
    @jakarta.annotation.Nullable
    public String getTxHash() {
        return txHash;
    }

    public void setTxHash(@jakarta.annotation.Nullable String txHash) {
        this.txHash = txHash;
    }

    public GetDexTradeHistoryResponseDataTransactionListInner chainLogoUrl(
            @jakarta.annotation.Nullable String chainLogoUrl) {
        this.chainLogoUrl = chainLogoUrl;
        return this;
    }

    /**
     * Chain logo image URL.
     *
     * @return chainLogoUrl
     */
    @jakarta.annotation.Nullable
    public String getChainLogoUrl() {
        return chainLogoUrl;
    }

    public void setChainLogoUrl(@jakarta.annotation.Nullable String chainLogoUrl) {
        this.chainLogoUrl = chainLogoUrl;
    }

    public GetDexTradeHistoryResponseDataTransactionListInner time(
            @jakarta.annotation.Nullable String time) {
        this.time = time;
        return this;
    }

    /**
     * Transaction on-chain time, Unix millisecond timestamp.
     *
     * @return time
     */
    @jakarta.annotation.Nullable
    public String getTime() {
        return time;
    }

    public void setTime(@jakarta.annotation.Nullable String time) {
        this.time = time;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetDexTradeHistoryResponseDataTransactionListInner
                getDexTradeHistoryResponseDataTransactionListInner =
                        (GetDexTradeHistoryResponseDataTransactionListInner) o;
        return Objects.equals(this.type, getDexTradeHistoryResponseDataTransactionListInner.type)
                && Objects.equals(
                        this.binanceChainId,
                        getDexTradeHistoryResponseDataTransactionListInner.binanceChainId)
                && Objects.equals(
                        this.tokenContractAddress,
                        getDexTradeHistoryResponseDataTransactionListInner.tokenContractAddress)
                && Objects.equals(
                        this.tokenSymbol,
                        getDexTradeHistoryResponseDataTransactionListInner.tokenSymbol)
                && Objects.equals(
                        this.valueUsd, getDexTradeHistoryResponseDataTransactionListInner.valueUsd)
                && Objects.equals(
                        this.amount, getDexTradeHistoryResponseDataTransactionListInner.amount)
                && Objects.equals(
                        this.price, getDexTradeHistoryResponseDataTransactionListInner.price)
                && Objects.equals(
                        this.marketCap,
                        getDexTradeHistoryResponseDataTransactionListInner.marketCap)
                && Objects.equals(
                        this.txHash, getDexTradeHistoryResponseDataTransactionListInner.txHash)
                && Objects.equals(
                        this.chainLogoUrl,
                        getDexTradeHistoryResponseDataTransactionListInner.chainLogoUrl)
                && Objects.equals(
                        this.time, getDexTradeHistoryResponseDataTransactionListInner.time);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                type,
                binanceChainId,
                tokenContractAddress,
                tokenSymbol,
                valueUsd,
                amount,
                price,
                marketCap,
                txHash,
                chainLogoUrl,
                time);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetDexTradeHistoryResponseDataTransactionListInner {\n");
        sb.append("		type: ").append(toIndentedString(type)).append("\n");
        sb.append("		binanceChainId: ").append(toIndentedString(binanceChainId)).append("\n");
        sb.append("		tokenContractAddress: ")
                .append(toIndentedString(tokenContractAddress))
                .append("\n");
        sb.append("		tokenSymbol: ").append(toIndentedString(tokenSymbol)).append("\n");
        sb.append("		valueUsd: ").append(toIndentedString(valueUsd)).append("\n");
        sb.append("		amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("		price: ").append(toIndentedString(price)).append("\n");
        sb.append("		marketCap: ").append(toIndentedString(marketCap)).append("\n");
        sb.append("		txHash: ").append(toIndentedString(txHash)).append("\n");
        sb.append("		chainLogoUrl: ").append(toIndentedString(chainLogoUrl)).append("\n");
        sb.append("		time: ").append(toIndentedString(time)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object typeValue = getType();
        String typeValueAsString = "";
        typeValueAsString = typeValue.toString();
        sb.append("type=").append(urlEncode(typeValueAsString)).append("");
        Object binanceChainIdValue = getBinanceChainId();
        String binanceChainIdValueAsString = "";
        binanceChainIdValueAsString = binanceChainIdValue.toString();
        sb.append("binanceChainId=").append(urlEncode(binanceChainIdValueAsString)).append("");
        Object tokenContractAddressValue = getTokenContractAddress();
        String tokenContractAddressValueAsString = "";
        tokenContractAddressValueAsString = tokenContractAddressValue.toString();
        sb.append("tokenContractAddress=")
                .append(urlEncode(tokenContractAddressValueAsString))
                .append("");
        Object tokenSymbolValue = getTokenSymbol();
        String tokenSymbolValueAsString = "";
        tokenSymbolValueAsString = tokenSymbolValue.toString();
        sb.append("tokenSymbol=").append(urlEncode(tokenSymbolValueAsString)).append("");
        Object valueUsdValue = getValueUsd();
        String valueUsdValueAsString = "";
        valueUsdValueAsString = valueUsdValue.toString();
        sb.append("valueUsd=").append(urlEncode(valueUsdValueAsString)).append("");
        Object amountValue = getAmount();
        String amountValueAsString = "";
        amountValueAsString = amountValue.toString();
        sb.append("amount=").append(urlEncode(amountValueAsString)).append("");
        Object priceValue = getPrice();
        String priceValueAsString = "";
        priceValueAsString = priceValue.toString();
        sb.append("price=").append(urlEncode(priceValueAsString)).append("");
        Object marketCapValue = getMarketCap();
        String marketCapValueAsString = "";
        marketCapValueAsString = marketCapValue.toString();
        sb.append("marketCap=").append(urlEncode(marketCapValueAsString)).append("");
        Object txHashValue = getTxHash();
        String txHashValueAsString = "";
        txHashValueAsString = txHashValue.toString();
        sb.append("txHash=").append(urlEncode(txHashValueAsString)).append("");
        Object chainLogoUrlValue = getChainLogoUrl();
        String chainLogoUrlValueAsString = "";
        chainLogoUrlValueAsString = chainLogoUrlValue.toString();
        sb.append("chainLogoUrl=").append(urlEncode(chainLogoUrlValueAsString)).append("");
        Object timeValue = getTime();
        String timeValueAsString = "";
        timeValueAsString = timeValue.toString();
        sb.append("time=").append(urlEncode(timeValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("type");
        openapiFields.add("binanceChainId");
        openapiFields.add("tokenContractAddress");
        openapiFields.add("tokenSymbol");
        openapiFields.add("valueUsd");
        openapiFields.add("amount");
        openapiFields.add("price");
        openapiFields.add("marketCap");
        openapiFields.add("txHash");
        openapiFields.add("chainLogoUrl");
        openapiFields.add("time");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     GetDexTradeHistoryResponseDataTransactionListInner
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetDexTradeHistoryResponseDataTransactionListInner.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in"
                                    + " GetDexTradeHistoryResponseDataTransactionListInner is not"
                                    + " found in the empty JSON string",
                                GetDexTradeHistoryResponseDataTransactionListInner
                                        .openapiRequiredFields
                                        .toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull())
                && !jsonObj.get("type").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `type` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("type").toString()));
        }
        if ((jsonObj.get("binanceChainId") != null && !jsonObj.get("binanceChainId").isJsonNull())
                && !jsonObj.get("binanceChainId").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `binanceChainId` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("binanceChainId").toString()));
        }
        if ((jsonObj.get("tokenContractAddress") != null
                        && !jsonObj.get("tokenContractAddress").isJsonNull())
                && !jsonObj.get("tokenContractAddress").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `tokenContractAddress` to be a primitive type in"
                                    + " the JSON string but got `%s`",
                            jsonObj.get("tokenContractAddress").toString()));
        }
        if ((jsonObj.get("tokenSymbol") != null && !jsonObj.get("tokenSymbol").isJsonNull())
                && !jsonObj.get("tokenSymbol").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `tokenSymbol` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("tokenSymbol").toString()));
        }
        if ((jsonObj.get("valueUsd") != null && !jsonObj.get("valueUsd").isJsonNull())
                && !jsonObj.get("valueUsd").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `valueUsd` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("valueUsd").toString()));
        }
        if ((jsonObj.get("amount") != null && !jsonObj.get("amount").isJsonNull())
                && !jsonObj.get("amount").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `amount` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("amount").toString()));
        }
        if ((jsonObj.get("price") != null && !jsonObj.get("price").isJsonNull())
                && !jsonObj.get("price").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `price` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("price").toString()));
        }
        if ((jsonObj.get("marketCap") != null && !jsonObj.get("marketCap").isJsonNull())
                && !jsonObj.get("marketCap").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `marketCap` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("marketCap").toString()));
        }
        if ((jsonObj.get("txHash") != null && !jsonObj.get("txHash").isJsonNull())
                && !jsonObj.get("txHash").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `txHash` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("txHash").toString()));
        }
        if ((jsonObj.get("chainLogoUrl") != null && !jsonObj.get("chainLogoUrl").isJsonNull())
                && !jsonObj.get("chainLogoUrl").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `chainLogoUrl` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("chainLogoUrl").toString()));
        }
        if ((jsonObj.get("time") != null && !jsonObj.get("time").isJsonNull())
                && !jsonObj.get("time").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `time` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("time").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetDexTradeHistoryResponseDataTransactionListInner.class.isAssignableFrom(
                    type.getRawType())) {
                return null; // this class only serializes
                // 'GetDexTradeHistoryResponseDataTransactionListInner' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetDexTradeHistoryResponseDataTransactionListInner> thisAdapter =
                    gson.getDelegateAdapter(
                            this,
                            TypeToken.get(
                                    GetDexTradeHistoryResponseDataTransactionListInner.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<GetDexTradeHistoryResponseDataTransactionListInner>() {
                        @Override
                        public void write(
                                JsonWriter out,
                                GetDexTradeHistoryResponseDataTransactionListInner value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public GetDexTradeHistoryResponseDataTransactionListInner read(
                                JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of GetDexTradeHistoryResponseDataTransactionListInner given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetDexTradeHistoryResponseDataTransactionListInner
     * @throws IOException if the JSON string is invalid with respect to
     *     GetDexTradeHistoryResponseDataTransactionListInner
     */
    public static GetDexTradeHistoryResponseDataTransactionListInner fromJson(String jsonString)
            throws IOException {
        return JSON.getGson()
                .fromJson(jsonString, GetDexTradeHistoryResponseDataTransactionListInner.class);
    }

    /**
     * Convert an instance of GetDexTradeHistoryResponseDataTransactionListInner to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
