/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import org.hibernate.validator.constraints.*;
import org.openapitools.jackson.nullable.JsonNullable;

/** GetRwaTokenIssuancePlatformsResponseDataInner */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class GetRwaTokenIssuancePlatformsResponseDataInner {
    public static final String SERIALIZED_NAME_PLATFORM_ID = "platformId";

    @SerializedName(SERIALIZED_NAME_PLATFORM_ID)
    @jakarta.annotation.Nullable
    private String platformId;

    public static final String SERIALIZED_NAME_TICKER_COUNT = "tickerCount";

    @SerializedName(SERIALIZED_NAME_TICKER_COUNT)
    @jakarta.annotation.Nullable
    private Integer tickerCount;

    public static final String SERIALIZED_NAME_CHAIN_DISTRIBUTION = "chainDistribution";

    @SerializedName(SERIALIZED_NAME_CHAIN_DISTRIBUTION)
    @jakarta.annotation.Nullable
    private List<@Valid GetRwaTokenIssuancePlatformsResponseDataInnerChainDistributionInner>
            chainDistribution;

    public static final String SERIALIZED_NAME_WEBSITE = "website";

    @SerializedName(SERIALIZED_NAME_WEBSITE)
    @jakarta.annotation.Nullable
    private String website;

    public static final String SERIALIZED_NAME_LOGO_URL = "logoUrl";

    @SerializedName(SERIALIZED_NAME_LOGO_URL)
    @jakarta.annotation.Nullable
    private String logoUrl;

    public GetRwaTokenIssuancePlatformsResponseDataInner() {}

    public GetRwaTokenIssuancePlatformsResponseDataInner platformId(
            @jakarta.annotation.Nullable String platformId) {
        this.platformId = platformId;
        return this;
    }

    /**
     * Unique platform identifier. Examples: ondo&#x3D;Ondo Finance, bstock&#x3D;bStocks.
     *
     * @return platformId
     */
    @jakarta.annotation.Nullable
    public String getPlatformId() {
        return platformId;
    }

    public void setPlatformId(@jakarta.annotation.Nullable String platformId) {
        this.platformId = platformId;
    }

    public GetRwaTokenIssuancePlatformsResponseDataInner tickerCount(
            @jakarta.annotation.Nullable Integer tickerCount) {
        this.tickerCount = tickerCount;
        return this;
    }

    /**
     * Number of underlying assets corresponding to the RWA tokens.
     *
     * @return tickerCount
     */
    @jakarta.annotation.Nullable
    public Integer getTickerCount() {
        return tickerCount;
    }

    public void setTickerCount(@jakarta.annotation.Nullable Integer tickerCount) {
        this.tickerCount = tickerCount;
    }

    public GetRwaTokenIssuancePlatformsResponseDataInner chainDistribution(
            @jakarta.annotation.Nullable
                    List<@Valid GetRwaTokenIssuancePlatformsResponseDataInnerChainDistributionInner>
                            chainDistribution) {
        this.chainDistribution = chainDistribution;
        return this;
    }

    public GetRwaTokenIssuancePlatformsResponseDataInner addChainDistributionItem(
            GetRwaTokenIssuancePlatformsResponseDataInnerChainDistributionInner
                    chainDistributionItem) {
        if (this.chainDistribution == null) {
            this.chainDistribution = new ArrayList<>();
        }
        this.chainDistribution.add(chainDistributionItem);
        return this;
    }

    /**
     * RWA token distribution across chains.
     *
     * @return chainDistribution
     */
    @jakarta.annotation.Nullable
    @Valid
    public List<@Valid GetRwaTokenIssuancePlatformsResponseDataInnerChainDistributionInner>
            getChainDistribution() {
        return chainDistribution;
    }

    public void setChainDistribution(
            @jakarta.annotation.Nullable
                    List<@Valid GetRwaTokenIssuancePlatformsResponseDataInnerChainDistributionInner>
                            chainDistribution) {
        this.chainDistribution = chainDistribution;
    }

    public GetRwaTokenIssuancePlatformsResponseDataInner website(
            @jakarta.annotation.Nullable String website) {
        this.website = website;
        return this;
    }

    /**
     * Platform official website. Null when unavailable.
     *
     * @return website
     */
    @jakarta.annotation.Nullable
    public String getWebsite() {
        return website;
    }

    public void setWebsite(@jakarta.annotation.Nullable String website) {
        this.website = website;
    }

    public GetRwaTokenIssuancePlatformsResponseDataInner logoUrl(
            @jakarta.annotation.Nullable String logoUrl) {
        this.logoUrl = logoUrl;
        return this;
    }

    /**
     * Platform logo URL. Null when unavailable.
     *
     * @return logoUrl
     */
    @jakarta.annotation.Nullable
    public String getLogoUrl() {
        return logoUrl;
    }

    public void setLogoUrl(@jakarta.annotation.Nullable String logoUrl) {
        this.logoUrl = logoUrl;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetRwaTokenIssuancePlatformsResponseDataInner
                getRwaTokenIssuancePlatformsResponseDataInner =
                        (GetRwaTokenIssuancePlatformsResponseDataInner) o;
        return Objects.equals(
                        this.platformId, getRwaTokenIssuancePlatformsResponseDataInner.platformId)
                && Objects.equals(
                        this.tickerCount, getRwaTokenIssuancePlatformsResponseDataInner.tickerCount)
                && Objects.equals(
                        this.chainDistribution,
                        getRwaTokenIssuancePlatformsResponseDataInner.chainDistribution)
                && Objects.equals(
                        this.website, getRwaTokenIssuancePlatformsResponseDataInner.website)
                && Objects.equals(
                        this.logoUrl, getRwaTokenIssuancePlatformsResponseDataInner.logoUrl);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b
                || (a != null
                        && b != null
                        && a.isPresent()
                        && b.isPresent()
                        && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode() {
        return Objects.hash(platformId, tickerCount, chainDistribution, website, logoUrl);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetRwaTokenIssuancePlatformsResponseDataInner {\n");
        sb.append("		platformId: ").append(toIndentedString(platformId)).append("\n");
        sb.append("		tickerCount: ").append(toIndentedString(tickerCount)).append("\n");
        sb.append("		chainDistribution: ").append(toIndentedString(chainDistribution)).append("\n");
        sb.append("		website: ").append(toIndentedString(website)).append("\n");
        sb.append("		logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object platformIdValue = getPlatformId();
        String platformIdValueAsString = "";
        platformIdValueAsString = platformIdValue.toString();
        sb.append("platformId=").append(urlEncode(platformIdValueAsString)).append("");
        Object tickerCountValue = getTickerCount();
        String tickerCountValueAsString = "";
        tickerCountValueAsString = tickerCountValue.toString();
        sb.append("tickerCount=").append(urlEncode(tickerCountValueAsString)).append("");
        Object chainDistributionValue = getChainDistribution();
        String chainDistributionValueAsString = "";
        chainDistributionValueAsString =
                (String)
                        ((Collection) chainDistributionValue)
                                .stream().map(Object::toString).collect(Collectors.joining(","));
        sb.append("chainDistribution=")
                .append(urlEncode(chainDistributionValueAsString))
                .append("");
        Object websiteValue = getWebsite();
        String websiteValueAsString = "";
        websiteValueAsString = websiteValue.toString();
        sb.append("website=").append(urlEncode(websiteValueAsString)).append("");
        Object logoUrlValue = getLogoUrl();
        String logoUrlValueAsString = "";
        logoUrlValueAsString = logoUrlValue.toString();
        sb.append("logoUrl=").append(urlEncode(logoUrlValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("platformId");
        openapiFields.add("tickerCount");
        openapiFields.add("chainDistribution");
        openapiFields.add("website");
        openapiFields.add("logoUrl");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     GetRwaTokenIssuancePlatformsResponseDataInner
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetRwaTokenIssuancePlatformsResponseDataInner.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in"
                                    + " GetRwaTokenIssuancePlatformsResponseDataInner is not found"
                                    + " in the empty JSON string",
                                GetRwaTokenIssuancePlatformsResponseDataInner.openapiRequiredFields
                                        .toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("platformId") != null && !jsonObj.get("platformId").isJsonNull())
                && !jsonObj.get("platformId").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `platformId` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("platformId").toString()));
        }
        if (jsonObj.get("chainDistribution") != null
                && !jsonObj.get("chainDistribution").isJsonNull()) {
            JsonArray jsonArraychainDistribution = jsonObj.getAsJsonArray("chainDistribution");
            if (jsonArraychainDistribution != null) {
                // ensure the json data is an array
                if (!jsonObj.get("chainDistribution").isJsonArray()) {
                    throw new IllegalArgumentException(
                            String.format(
                                    "Expected the field `chainDistribution` to be an array in the"
                                            + " JSON string but got `%s`",
                                    jsonObj.get("chainDistribution").toString()));
                }

                // validate the optional field `chainDistribution` (array)
                for (int i = 0; i < jsonArraychainDistribution.size(); i++) {
                    GetRwaTokenIssuancePlatformsResponseDataInnerChainDistributionInner
                            .validateJsonElement(jsonArraychainDistribution.get(i));
                }
                ;
            }
        }
        if ((jsonObj.get("website") != null && !jsonObj.get("website").isJsonNull())
                && !jsonObj.get("website").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `website` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("website").toString()));
        }
        if ((jsonObj.get("logoUrl") != null && !jsonObj.get("logoUrl").isJsonNull())
                && !jsonObj.get("logoUrl").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `logoUrl` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("logoUrl").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetRwaTokenIssuancePlatformsResponseDataInner.class.isAssignableFrom(
                    type.getRawType())) {
                return null; // this class only serializes
                // 'GetRwaTokenIssuancePlatformsResponseDataInner' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetRwaTokenIssuancePlatformsResponseDataInner> thisAdapter =
                    gson.getDelegateAdapter(
                            this,
                            TypeToken.get(GetRwaTokenIssuancePlatformsResponseDataInner.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<GetRwaTokenIssuancePlatformsResponseDataInner>() {
                        @Override
                        public void write(
                                JsonWriter out, GetRwaTokenIssuancePlatformsResponseDataInner value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public GetRwaTokenIssuancePlatformsResponseDataInner read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of GetRwaTokenIssuancePlatformsResponseDataInner given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetRwaTokenIssuancePlatformsResponseDataInner
     * @throws IOException if the JSON string is invalid with respect to
     *     GetRwaTokenIssuancePlatformsResponseDataInner
     */
    public static GetRwaTokenIssuancePlatformsResponseDataInner fromJson(String jsonString)
            throws IOException {
        return JSON.getGson()
                .fromJson(jsonString, GetRwaTokenIssuancePlatformsResponseDataInner.class);
    }

    /**
     * Convert an instance of GetRwaTokenIssuancePlatformsResponseDataInner to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
