/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;
import org.hibernate.validator.constraints.*;
import org.openapitools.jackson.nullable.JsonNullable;

/** GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner {
    public static final String SERIALIZED_NAME_FROM = "from";

    @SerializedName(SERIALIZED_NAME_FROM)
    @jakarta.annotation.Nullable
    private String from;

    public static final String SERIALIZED_NAME_TO = "to";

    @SerializedName(SERIALIZED_NAME_TO)
    @jakarta.annotation.Nullable
    private String to;

    public static final String SERIALIZED_NAME_IS_FROM_CONTRACT = "isFromContract";

    @SerializedName(SERIALIZED_NAME_IS_FROM_CONTRACT)
    @jakarta.annotation.Nullable
    private Boolean isFromContract;

    public static final String SERIALIZED_NAME_IS_TO_CONTRACT = "isToContract";

    @SerializedName(SERIALIZED_NAME_IS_TO_CONTRACT)
    @jakarta.annotation.Nullable
    private Boolean isToContract;

    public static final String SERIALIZED_NAME_TOKEN_CONTRACT_ADDRESS = "tokenContractAddress";

    @SerializedName(SERIALIZED_NAME_TOKEN_CONTRACT_ADDRESS)
    @jakarta.annotation.Nullable
    private String tokenContractAddress;

    public static final String SERIALIZED_NAME_SYMBOL = "symbol";

    @SerializedName(SERIALIZED_NAME_SYMBOL)
    @jakarta.annotation.Nullable
    private String symbol;

    public static final String SERIALIZED_NAME_AMOUNT = "amount";

    @SerializedName(SERIALIZED_NAME_AMOUNT)
    @jakarta.annotation.Nullable
    private String amount;

    public GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner() {}

    public GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner from(
            @jakarta.annotation.Nullable String from) {
        this.from = from;
        return this;
    }

    /**
     * Sender address.
     *
     * @return from
     */
    @jakarta.annotation.Nullable
    public String getFrom() {
        return from;
    }

    public void setFrom(@jakarta.annotation.Nullable String from) {
        this.from = from;
    }

    public GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner to(
            @jakarta.annotation.Nullable String to) {
        this.to = to;
        return this;
    }

    /**
     * Receiver address.
     *
     * @return to
     */
    @jakarta.annotation.Nullable
    public String getTo() {
        return to;
    }

    public void setTo(@jakarta.annotation.Nullable String to) {
        this.to = to;
    }

    public GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner isFromContract(
            @jakarta.annotation.Nullable Boolean isFromContract) {
        this.isFromContract = isFromContract;
        return this;
    }

    /**
     * Whether the sender is a contract.
     *
     * @return isFromContract
     */
    @jakarta.annotation.Nullable
    public Boolean getIsFromContract() {
        return isFromContract;
    }

    public void setIsFromContract(@jakarta.annotation.Nullable Boolean isFromContract) {
        this.isFromContract = isFromContract;
    }

    public GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner isToContract(
            @jakarta.annotation.Nullable Boolean isToContract) {
        this.isToContract = isToContract;
        return this;
    }

    /**
     * Whether the receiver is a contract.
     *
     * @return isToContract
     */
    @jakarta.annotation.Nullable
    public Boolean getIsToContract() {
        return isToContract;
    }

    public void setIsToContract(@jakarta.annotation.Nullable Boolean isToContract) {
        this.isToContract = isToContract;
    }

    public GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
            tokenContractAddress(@jakarta.annotation.Nullable String tokenContractAddress) {
        this.tokenContractAddress = tokenContractAddress;
        return this;
    }

    /**
     * Token contract address.
     *
     * @return tokenContractAddress
     */
    @jakarta.annotation.Nullable
    public String getTokenContractAddress() {
        return tokenContractAddress;
    }

    public void setTokenContractAddress(@jakarta.annotation.Nullable String tokenContractAddress) {
        this.tokenContractAddress = tokenContractAddress;
    }

    public GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner symbol(
            @jakarta.annotation.Nullable String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Token ticker.
     *
     * @return symbol
     */
    @jakarta.annotation.Nullable
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(@jakarta.annotation.Nullable String symbol) {
        this.symbol = symbol;
    }

    public GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner amount(
            @jakarta.annotation.Nullable String amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Transfer amount (smallest unit, decimal string).
     *
     * @return amount
     */
    @jakarta.annotation.Nullable
    public String getAmount() {
        return amount;
    }

    public void setAmount(@jakarta.annotation.Nullable String amount) {
        this.amount = amount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
                getTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner =
                        (GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner) o;
        return Objects.equals(
                        this.from,
                        getTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner.from)
                && Objects.equals(
                        this.to,
                        getTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner.to)
                && Objects.equals(
                        this.isFromContract,
                        getTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
                                .isFromContract)
                && Objects.equals(
                        this.isToContract,
                        getTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
                                .isToContract)
                && Objects.equals(
                        this.tokenContractAddress,
                        getTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
                                .tokenContractAddress)
                && Objects.equals(
                        this.symbol,
                        getTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner.symbol)
                && Objects.equals(
                        this.amount,
                        getTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
                                .amount);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b
                || (a != null
                        && b != null
                        && a.isPresent()
                        && b.isPresent()
                        && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                from, to, isFromContract, isToContract, tokenContractAddress, symbol, amount);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner {\n");
        sb.append("		from: ").append(toIndentedString(from)).append("\n");
        sb.append("		to: ").append(toIndentedString(to)).append("\n");
        sb.append("		isFromContract: ").append(toIndentedString(isFromContract)).append("\n");
        sb.append("		isToContract: ").append(toIndentedString(isToContract)).append("\n");
        sb.append("		tokenContractAddress: ")
                .append(toIndentedString(tokenContractAddress))
                .append("\n");
        sb.append("		symbol: ").append(toIndentedString(symbol)).append("\n");
        sb.append("		amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object fromValue = getFrom();
        String fromValueAsString = "";
        fromValueAsString = fromValue.toString();
        sb.append("from=").append(urlEncode(fromValueAsString)).append("");
        Object toValue = getTo();
        String toValueAsString = "";
        toValueAsString = toValue.toString();
        sb.append("to=").append(urlEncode(toValueAsString)).append("");
        Object isFromContractValue = getIsFromContract();
        String isFromContractValueAsString = "";
        isFromContractValueAsString = isFromContractValue.toString();
        sb.append("isFromContract=").append(urlEncode(isFromContractValueAsString)).append("");
        Object isToContractValue = getIsToContract();
        String isToContractValueAsString = "";
        isToContractValueAsString = isToContractValue.toString();
        sb.append("isToContract=").append(urlEncode(isToContractValueAsString)).append("");
        Object tokenContractAddressValue = getTokenContractAddress();
        String tokenContractAddressValueAsString = "";
        tokenContractAddressValueAsString = tokenContractAddressValue.toString();
        sb.append("tokenContractAddress=")
                .append(urlEncode(tokenContractAddressValueAsString))
                .append("");
        Object symbolValue = getSymbol();
        String symbolValueAsString = "";
        symbolValueAsString = symbolValue.toString();
        sb.append("symbol=").append(urlEncode(symbolValueAsString)).append("");
        Object amountValue = getAmount();
        String amountValueAsString = "";
        amountValueAsString = amountValue.toString();
        sb.append("amount=").append(urlEncode(amountValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("from");
        openapiFields.add("to");
        openapiFields.add("isFromContract");
        openapiFields.add("isToContract");
        openapiFields.add("tokenContractAddress");
        openapiFields.add("symbol");
        openapiFields.add("amount");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
                    .openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in"
                                    + " GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner"
                                    + " is not found in the empty JSON string",
                                GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
                                        .openapiRequiredFields
                                        .toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("from") != null && !jsonObj.get("from").isJsonNull())
                && !jsonObj.get("from").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `from` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("from").toString()));
        }
        if ((jsonObj.get("to") != null && !jsonObj.get("to").isJsonNull())
                && !jsonObj.get("to").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `to` to be a primitive type in the JSON string but"
                                    + " got `%s`",
                            jsonObj.get("to").toString()));
        }
        if ((jsonObj.get("tokenContractAddress") != null
                        && !jsonObj.get("tokenContractAddress").isJsonNull())
                && !jsonObj.get("tokenContractAddress").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `tokenContractAddress` to be a primitive type in"
                                    + " the JSON string but got `%s`",
                            jsonObj.get("tokenContractAddress").toString()));
        }
        if ((jsonObj.get("symbol") != null && !jsonObj.get("symbol").isJsonNull())
                && !jsonObj.get("symbol").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `symbol` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("symbol").toString()));
        }
        if ((jsonObj.get("amount") != null && !jsonObj.get("amount").isJsonNull())
                && !jsonObj.get("amount").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `amount` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("amount").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner.class
                    .isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes
                // 'GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner>
                    thisAdapter =
                            gson.getDelegateAdapter(
                                    this,
                                    TypeToken.get(
                                            GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
                                                    .class));

            return (TypeAdapter<T>)
                    new TypeAdapter<
                            GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner>() {
                        @Override
                        public void write(
                                JsonWriter out,
                                GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
                                        value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
                                read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
     * given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
     * @throws IOException if the JSON string is invalid with respect to
     *     GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
     */
    public static GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner fromJson(
            String jsonString) throws IOException {
        return JSON.getGson()
                .fromJson(
                        jsonString,
                        GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner.class);
    }

    /**
     * Convert an instance of GetTransactionDetailByHashResponseDataInnerTokenTransferDetailsInner
     * to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
