/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import org.hibernate.validator.constraints.*;
import org.openapitools.jackson.nullable.JsonNullable;

/** A collection of positions grouped under the same underlying asset. */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class PositionCollectionResp {
    public static final String SERIALIZED_NAME_POSITION_COLLECTION_ID = "positionCollectionId";

    @SerializedName(SERIALIZED_NAME_POSITION_COLLECTION_ID)
    @jakarta.annotation.Nullable
    private String positionCollectionId;

    public static final String SERIALIZED_NAME_POSITION_COLLECTION_DETAIL =
            "positionCollectionDetail";

    @SerializedName(SERIALIZED_NAME_POSITION_COLLECTION_DETAIL)
    @jakarta.annotation.Nullable
    private PositionCollectionRespPositionCollectionDetail positionCollectionDetail;

    public static final String SERIALIZED_NAME_POSITION_COLLECTION_TOTAL_VALUE =
            "positionCollectionTotalValue";

    @SerializedName(SERIALIZED_NAME_POSITION_COLLECTION_TOTAL_VALUE)
    @jakarta.annotation.Nullable
    private String positionCollectionTotalValue;

    public static final String SERIALIZED_NAME_POSITION_LIST = "positionList";

    @SerializedName(SERIALIZED_NAME_POSITION_LIST)
    @jakarta.annotation.Nullable
    private List<@Valid PositionCollectionRespPositionListInner> positionList;

    public PositionCollectionResp() {}

    public PositionCollectionResp positionCollectionId(
            @jakarta.annotation.Nullable String positionCollectionId) {
        this.positionCollectionId = positionCollectionId;
        return this;
    }

    /**
     * Collection unique identifier (64-char hex, no &#x60;0x&#x60; prefix).
     *
     * @return positionCollectionId
     */
    @jakarta.annotation.Nullable
    public String getPositionCollectionId() {
        return positionCollectionId;
    }

    public void setPositionCollectionId(@jakarta.annotation.Nullable String positionCollectionId) {
        this.positionCollectionId = positionCollectionId;
    }

    public PositionCollectionResp positionCollectionDetail(
            @jakarta.annotation.Nullable
                    PositionCollectionRespPositionCollectionDetail positionCollectionDetail) {
        this.positionCollectionDetail = positionCollectionDetail;
        return this;
    }

    /**
     * Get positionCollectionDetail
     *
     * @return positionCollectionDetail
     */
    @jakarta.annotation.Nullable
    @Valid
    public PositionCollectionRespPositionCollectionDetail getPositionCollectionDetail() {
        return positionCollectionDetail;
    }

    public void setPositionCollectionDetail(
            @jakarta.annotation.Nullable
                    PositionCollectionRespPositionCollectionDetail positionCollectionDetail) {
        this.positionCollectionDetail = positionCollectionDetail;
    }

    public PositionCollectionResp positionCollectionTotalValue(
            @jakarta.annotation.Nullable String positionCollectionTotalValue) {
        this.positionCollectionTotalValue = positionCollectionTotalValue;
        return this;
    }

    /**
     * Total value of all positions in this collection (USD).
     *
     * @return positionCollectionTotalValue
     */
    @jakarta.annotation.Nullable
    public String getPositionCollectionTotalValue() {
        return positionCollectionTotalValue;
    }

    public void setPositionCollectionTotalValue(
            @jakarta.annotation.Nullable String positionCollectionTotalValue) {
        this.positionCollectionTotalValue = positionCollectionTotalValue;
    }

    public PositionCollectionResp positionList(
            @jakarta.annotation.Nullable
                    List<@Valid PositionCollectionRespPositionListInner> positionList) {
        this.positionList = positionList;
        return this;
    }

    public PositionCollectionResp addPositionListItem(
            PositionCollectionRespPositionListInner positionListItem) {
        if (this.positionList == null) {
            this.positionList = new ArrayList<>();
        }
        this.positionList.add(positionListItem);
        return this;
    }

    /**
     * List of positions in this collection.
     *
     * @return positionList
     */
    @jakarta.annotation.Nullable
    @Valid
    public List<@Valid PositionCollectionRespPositionListInner> getPositionList() {
        return positionList;
    }

    public void setPositionList(
            @jakarta.annotation.Nullable
                    List<@Valid PositionCollectionRespPositionListInner> positionList) {
        this.positionList = positionList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PositionCollectionResp positionCollectionResp = (PositionCollectionResp) o;
        return Objects.equals(
                        this.positionCollectionId, positionCollectionResp.positionCollectionId)
                && Objects.equals(
                        this.positionCollectionDetail,
                        positionCollectionResp.positionCollectionDetail)
                && Objects.equals(
                        this.positionCollectionTotalValue,
                        positionCollectionResp.positionCollectionTotalValue)
                && Objects.equals(this.positionList, positionCollectionResp.positionList);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b
                || (a != null
                        && b != null
                        && a.isPresent()
                        && b.isPresent()
                        && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                positionCollectionId,
                positionCollectionDetail,
                positionCollectionTotalValue,
                positionList);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PositionCollectionResp {\n");
        sb.append("		positionCollectionId: ")
                .append(toIndentedString(positionCollectionId))
                .append("\n");
        sb.append("		positionCollectionDetail: ")
                .append(toIndentedString(positionCollectionDetail))
                .append("\n");
        sb.append("		positionCollectionTotalValue: ")
                .append(toIndentedString(positionCollectionTotalValue))
                .append("\n");
        sb.append("		positionList: ").append(toIndentedString(positionList)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object positionCollectionIdValue = getPositionCollectionId();
        String positionCollectionIdValueAsString = "";
        positionCollectionIdValueAsString = positionCollectionIdValue.toString();
        sb.append("positionCollectionId=")
                .append(urlEncode(positionCollectionIdValueAsString))
                .append("");
        Object positionCollectionDetailValue = getPositionCollectionDetail();
        String positionCollectionDetailValueAsString = "";
        positionCollectionDetailValueAsString = positionCollectionDetailValue.toString();
        sb.append("positionCollectionDetail=")
                .append(urlEncode(positionCollectionDetailValueAsString))
                .append("");
        Object positionCollectionTotalValueValue = getPositionCollectionTotalValue();
        String positionCollectionTotalValueValueAsString = "";
        positionCollectionTotalValueValueAsString = positionCollectionTotalValueValue.toString();
        sb.append("positionCollectionTotalValue=")
                .append(urlEncode(positionCollectionTotalValueValueAsString))
                .append("");
        Object positionListValue = getPositionList();
        String positionListValueAsString = "";
        positionListValueAsString =
                (String)
                        ((Collection) positionListValue)
                                .stream().map(Object::toString).collect(Collectors.joining(","));
        sb.append("positionList=").append(urlEncode(positionListValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("positionCollectionId");
        openapiFields.add("positionCollectionDetail");
        openapiFields.add("positionCollectionTotalValue");
        openapiFields.add("positionList");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to PositionCollectionResp
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!PositionCollectionResp.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in PositionCollectionResp is not found in"
                                        + " the empty JSON string",
                                PositionCollectionResp.openapiRequiredFields.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("positionCollectionId") != null
                        && !jsonObj.get("positionCollectionId").isJsonNull())
                && !jsonObj.get("positionCollectionId").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `positionCollectionId` to be a primitive type in"
                                    + " the JSON string but got `%s`",
                            jsonObj.get("positionCollectionId").toString()));
        }
        // validate the optional field `positionCollectionDetail`
        if (jsonObj.get("positionCollectionDetail") != null
                && !jsonObj.get("positionCollectionDetail").isJsonNull()) {
            PositionCollectionRespPositionCollectionDetail.validateJsonElement(
                    jsonObj.get("positionCollectionDetail"));
        }
        if ((jsonObj.get("positionCollectionTotalValue") != null
                        && !jsonObj.get("positionCollectionTotalValue").isJsonNull())
                && !jsonObj.get("positionCollectionTotalValue").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `positionCollectionTotalValue` to be a primitive"
                                    + " type in the JSON string but got `%s`",
                            jsonObj.get("positionCollectionTotalValue").toString()));
        }
        if (jsonObj.get("positionList") != null && !jsonObj.get("positionList").isJsonNull()) {
            JsonArray jsonArraypositionList = jsonObj.getAsJsonArray("positionList");
            if (jsonArraypositionList != null) {
                // ensure the json data is an array
                if (!jsonObj.get("positionList").isJsonArray()) {
                    throw new IllegalArgumentException(
                            String.format(
                                    "Expected the field `positionList` to be an array in the JSON"
                                            + " string but got `%s`",
                                    jsonObj.get("positionList").toString()));
                }

                // validate the optional field `positionList` (array)
                for (int i = 0; i < jsonArraypositionList.size(); i++) {
                    PositionCollectionRespPositionListInner.validateJsonElement(
                            jsonArraypositionList.get(i));
                }
                ;
            }
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!PositionCollectionResp.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'PositionCollectionResp' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<PositionCollectionResp> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(PositionCollectionResp.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<PositionCollectionResp>() {
                        @Override
                        public void write(JsonWriter out, PositionCollectionResp value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public PositionCollectionResp read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of PositionCollectionResp given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of PositionCollectionResp
     * @throws IOException if the JSON string is invalid with respect to PositionCollectionResp
     */
    public static PositionCollectionResp fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, PositionCollectionResp.class);
    }

    /**
     * Convert an instance of PositionCollectionResp to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
