/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import org.hibernate.validator.constraints.*;
import org.openapitools.jackson.nullable.JsonNullable;

/** A single DeFi position with underlying asset and token breakdown. */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class PositionResp {
    public static final String SERIALIZED_NAME_POSITION_ID = "positionId";

    @SerializedName(SERIALIZED_NAME_POSITION_ID)
    @jakarta.annotation.Nullable
    private String positionId;

    public static final String SERIALIZED_NAME_UNDERLYING_ASSET_NAME = "underlyingAssetName";

    @SerializedName(SERIALIZED_NAME_UNDERLYING_ASSET_NAME)
    @jakarta.annotation.Nullable
    private String underlyingAssetName;

    public static final String SERIALIZED_NAME_UNDERLYING_ASSET_ID = "underlyingAssetId";

    @SerializedName(SERIALIZED_NAME_UNDERLYING_ASSET_ID)
    @jakarta.annotation.Nullable
    private String underlyingAssetId;

    public static final String SERIALIZED_NAME_ASSET_TYPE = "assetType";

    @SerializedName(SERIALIZED_NAME_ASSET_TYPE)
    @jakarta.annotation.Nullable
    private String assetType;

    public static final String SERIALIZED_NAME_INVESTMENT_IDS = "investmentIds";

    @SerializedName(SERIALIZED_NAME_INVESTMENT_IDS)
    @jakarta.annotation.Nullable
    private List<String> investmentIds;

    public static final String SERIALIZED_NAME_POSITION_DETAIL = "positionDetail";

    @SerializedName(SERIALIZED_NAME_POSITION_DETAIL)
    @jakarta.annotation.Nullable
    private PositionRespPositionDetail positionDetail;

    public static final String SERIALIZED_NAME_POSITION_VALUE = "positionValue";

    @SerializedName(SERIALIZED_NAME_POSITION_VALUE)
    @jakarta.annotation.Nullable
    private String positionValue;

    public static final String SERIALIZED_NAME_TOKEN_LIST = "tokenList";

    @SerializedName(SERIALIZED_NAME_TOKEN_LIST)
    @jakarta.annotation.Nullable
    private PositionRespTokenList tokenList;

    public PositionResp() {}

    public PositionResp positionId(@jakarta.annotation.Nullable String positionId) {
        this.positionId = positionId;
        return this;
    }

    /**
     * Unique position identifier (64-char hex, no &#x60;0x&#x60; prefix).
     *
     * @return positionId
     */
    @jakarta.annotation.Nullable
    public String getPositionId() {
        return positionId;
    }

    public void setPositionId(@jakarta.annotation.Nullable String positionId) {
        this.positionId = positionId;
    }

    public PositionResp underlyingAssetName(
            @jakarta.annotation.Nullable String underlyingAssetName) {
        this.underlyingAssetName = underlyingAssetName;
        return this;
    }

    /**
     * Display name of the underlying asset (e.g. \&quot;USDT-USDC\&quot;, \&quot;lisUSD\&quot;).
     *
     * @return underlyingAssetName
     */
    @jakarta.annotation.Nullable
    public String getUnderlyingAssetName() {
        return underlyingAssetName;
    }

    public void setUnderlyingAssetName(@jakarta.annotation.Nullable String underlyingAssetName) {
        this.underlyingAssetName = underlyingAssetName;
    }

    public PositionResp underlyingAssetId(@jakarta.annotation.Nullable String underlyingAssetId) {
        this.underlyingAssetId = underlyingAssetId;
        return this;
    }

    /**
     * Underlying asset identifier (64-char hex, no &#x60;0x&#x60; prefix). Hashed from the pool and
     * underlying token addresses.
     *
     * @return underlyingAssetId
     */
    @jakarta.annotation.Nullable
    public String getUnderlyingAssetId() {
        return underlyingAssetId;
    }

    public void setUnderlyingAssetId(@jakarta.annotation.Nullable String underlyingAssetId) {
        this.underlyingAssetId = underlyingAssetId;
    }

    public PositionResp assetType(@jakarta.annotation.Nullable String assetType) {
        this.assetType = assetType;
        return this;
    }

    /**
     * Asset structure type. Null for a regular position; &#x60;locked&#x60; for a locked position
     * (e.g. locked staking — check &#x60;unlockTime&#x60; on positionDetail); &#x60;farming&#x60;
     * for a MasterChef-style farming position (rewards accrue under the &#x60;farming_reward&#x60;
     * token group).
     *
     * @return assetType
     */
    @jakarta.annotation.Nullable
    public String getAssetType() {
        return assetType;
    }

    public void setAssetType(@jakarta.annotation.Nullable String assetType) {
        this.assetType = assetType;
    }

    public PositionResp investmentIds(@jakarta.annotation.Nullable List<String> investmentIds) {
        this.investmentIds = investmentIds;
        return this;
    }

    public PositionResp addInvestmentIdsItem(String investmentIdsItem) {
        if (this.investmentIds == null) {
            this.investmentIds = new ArrayList<>();
        }
        this.investmentIds.add(investmentIdsItem);
        return this;
    }

    /**
     * Related investment IDs (64-char hex, no &#x60;0x&#x60; prefix). Use with &#x60;POST
     * /api/v1/defi/data/investment/detail&#x60;. Usually a single entry; a position can relate to
     * several investments when the pool stacks products on top of each other (e.g. a farming
     * position wraps the underlying LP investment plus its incentive product, or a staked vault
     * layers a receipt token over the base deposit). When there are several, query each with
     * investment/detail and pick by the action you want to perform — redeeming the principal uses
     * the base investment, claiming farming incentives uses the incentive one.
     *
     * @return investmentIds
     */
    @jakarta.annotation.Nullable
    public List<String> getInvestmentIds() {
        return investmentIds;
    }

    public void setInvestmentIds(@jakarta.annotation.Nullable List<String> investmentIds) {
        this.investmentIds = investmentIds;
    }

    public PositionResp positionDetail(
            @jakarta.annotation.Nullable PositionRespPositionDetail positionDetail) {
        this.positionDetail = positionDetail;
        return this;
    }

    /**
     * Get positionDetail
     *
     * @return positionDetail
     */
    @jakarta.annotation.Nullable
    @Valid
    public PositionRespPositionDetail getPositionDetail() {
        return positionDetail;
    }

    public void setPositionDetail(
            @jakarta.annotation.Nullable PositionRespPositionDetail positionDetail) {
        this.positionDetail = positionDetail;
    }

    public PositionResp positionValue(@jakarta.annotation.Nullable String positionValue) {
        this.positionValue = positionValue;
        return this;
    }

    /**
     * Total position value in USD (sum of all token values; may be negative for borrow positions).
     *
     * @return positionValue
     */
    @jakarta.annotation.Nullable
    public String getPositionValue() {
        return positionValue;
    }

    public void setPositionValue(@jakarta.annotation.Nullable String positionValue) {
        this.positionValue = positionValue;
    }

    public PositionResp tokenList(@jakarta.annotation.Nullable PositionRespTokenList tokenList) {
        this.tokenList = tokenList;
        return this;
    }

    /**
     * Get tokenList
     *
     * @return tokenList
     */
    @jakarta.annotation.Nullable
    @Valid
    public PositionRespTokenList getTokenList() {
        return tokenList;
    }

    public void setTokenList(@jakarta.annotation.Nullable PositionRespTokenList tokenList) {
        this.tokenList = tokenList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PositionResp positionResp = (PositionResp) o;
        return Objects.equals(this.positionId, positionResp.positionId)
                && Objects.equals(this.underlyingAssetName, positionResp.underlyingAssetName)
                && Objects.equals(this.underlyingAssetId, positionResp.underlyingAssetId)
                && Objects.equals(this.assetType, positionResp.assetType)
                && Objects.equals(this.investmentIds, positionResp.investmentIds)
                && Objects.equals(this.positionDetail, positionResp.positionDetail)
                && Objects.equals(this.positionValue, positionResp.positionValue)
                && Objects.equals(this.tokenList, positionResp.tokenList);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b
                || (a != null
                        && b != null
                        && a.isPresent()
                        && b.isPresent()
                        && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                positionId,
                underlyingAssetName,
                underlyingAssetId,
                assetType,
                investmentIds,
                positionDetail,
                positionValue,
                tokenList);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PositionResp {\n");
        sb.append("		positionId: ").append(toIndentedString(positionId)).append("\n");
        sb.append("		underlyingAssetName: ")
                .append(toIndentedString(underlyingAssetName))
                .append("\n");
        sb.append("		underlyingAssetId: ").append(toIndentedString(underlyingAssetId)).append("\n");
        sb.append("		assetType: ").append(toIndentedString(assetType)).append("\n");
        sb.append("		investmentIds: ").append(toIndentedString(investmentIds)).append("\n");
        sb.append("		positionDetail: ").append(toIndentedString(positionDetail)).append("\n");
        sb.append("		positionValue: ").append(toIndentedString(positionValue)).append("\n");
        sb.append("		tokenList: ").append(toIndentedString(tokenList)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object positionIdValue = getPositionId();
        String positionIdValueAsString = "";
        positionIdValueAsString = positionIdValue.toString();
        sb.append("positionId=").append(urlEncode(positionIdValueAsString)).append("");
        Object underlyingAssetNameValue = getUnderlyingAssetName();
        String underlyingAssetNameValueAsString = "";
        underlyingAssetNameValueAsString = underlyingAssetNameValue.toString();
        sb.append("underlyingAssetName=")
                .append(urlEncode(underlyingAssetNameValueAsString))
                .append("");
        Object underlyingAssetIdValue = getUnderlyingAssetId();
        String underlyingAssetIdValueAsString = "";
        underlyingAssetIdValueAsString = underlyingAssetIdValue.toString();
        sb.append("underlyingAssetId=")
                .append(urlEncode(underlyingAssetIdValueAsString))
                .append("");
        Object assetTypeValue = getAssetType();
        String assetTypeValueAsString = "";
        assetTypeValueAsString = assetTypeValue.toString();
        sb.append("assetType=").append(urlEncode(assetTypeValueAsString)).append("");
        Object investmentIdsValue = getInvestmentIds();
        String investmentIdsValueAsString = "";
        investmentIdsValueAsString =
                (String)
                        ((Collection) investmentIdsValue)
                                .stream().map(Object::toString).collect(Collectors.joining(","));
        sb.append("investmentIds=").append(urlEncode(investmentIdsValueAsString)).append("");
        Object positionDetailValue = getPositionDetail();
        String positionDetailValueAsString = "";
        positionDetailValueAsString = positionDetailValue.toString();
        sb.append("positionDetail=").append(urlEncode(positionDetailValueAsString)).append("");
        Object positionValueValue = getPositionValue();
        String positionValueValueAsString = "";
        positionValueValueAsString = positionValueValue.toString();
        sb.append("positionValue=").append(urlEncode(positionValueValueAsString)).append("");
        Object tokenListValue = getTokenList();
        String tokenListValueAsString = "";
        tokenListValueAsString = tokenListValue.toString();
        sb.append("tokenList=").append(urlEncode(tokenListValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("positionId");
        openapiFields.add("underlyingAssetName");
        openapiFields.add("underlyingAssetId");
        openapiFields.add("assetType");
        openapiFields.add("investmentIds");
        openapiFields.add("positionDetail");
        openapiFields.add("positionValue");
        openapiFields.add("tokenList");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to PositionResp
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!PositionResp.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in PositionResp is not found in the empty"
                                        + " JSON string",
                                PositionResp.openapiRequiredFields.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("positionId") != null && !jsonObj.get("positionId").isJsonNull())
                && !jsonObj.get("positionId").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `positionId` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("positionId").toString()));
        }
        if ((jsonObj.get("underlyingAssetName") != null
                        && !jsonObj.get("underlyingAssetName").isJsonNull())
                && !jsonObj.get("underlyingAssetName").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `underlyingAssetName` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("underlyingAssetName").toString()));
        }
        if ((jsonObj.get("underlyingAssetId") != null
                        && !jsonObj.get("underlyingAssetId").isJsonNull())
                && !jsonObj.get("underlyingAssetId").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `underlyingAssetId` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("underlyingAssetId").toString()));
        }
        if ((jsonObj.get("assetType") != null && !jsonObj.get("assetType").isJsonNull())
                && !jsonObj.get("assetType").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `assetType` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("assetType").toString()));
        }
        // ensure the optional json data is an array if present
        if (jsonObj.get("investmentIds") != null
                && !jsonObj.get("investmentIds").isJsonNull()
                && !jsonObj.get("investmentIds").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `investmentIds` to be an array in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("investmentIds").toString()));
        }
        // validate the optional field `positionDetail`
        if (jsonObj.get("positionDetail") != null && !jsonObj.get("positionDetail").isJsonNull()) {
            PositionRespPositionDetail.validateJsonElement(jsonObj.get("positionDetail"));
        }
        if ((jsonObj.get("positionValue") != null && !jsonObj.get("positionValue").isJsonNull())
                && !jsonObj.get("positionValue").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `positionValue` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("positionValue").toString()));
        }
        // validate the optional field `tokenList`
        if (jsonObj.get("tokenList") != null && !jsonObj.get("tokenList").isJsonNull()) {
            PositionRespTokenList.validateJsonElement(jsonObj.get("tokenList"));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!PositionResp.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'PositionResp' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<PositionResp> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(PositionResp.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<PositionResp>() {
                        @Override
                        public void write(JsonWriter out, PositionResp value) throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public PositionResp read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of PositionResp given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of PositionResp
     * @throws IOException if the JSON string is invalid with respect to PositionResp
     */
    public static PositionResp fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, PositionResp.class);
    }

    /**
     * Convert an instance of PositionResp to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
