/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Objects;
import org.hibernate.validator.constraints.*;

/** SearchRwaTokenResponseDataInnerAssetsInner */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class SearchRwaTokenResponseDataInnerAssetsInner {
    public static final String SERIALIZED_NAME_PLATFORM_ID = "platformId";

    @SerializedName(SERIALIZED_NAME_PLATFORM_ID)
    @jakarta.annotation.Nullable
    private String platformId;

    public static final String SERIALIZED_NAME_BINANCE_CHAIN_ID = "binanceChainId";

    @SerializedName(SERIALIZED_NAME_BINANCE_CHAIN_ID)
    @jakarta.annotation.Nullable
    private String binanceChainId;

    public static final String SERIALIZED_NAME_TOKEN_CONTRACT_ADDRESS = "tokenContractAddress";

    @SerializedName(SERIALIZED_NAME_TOKEN_CONTRACT_ADDRESS)
    @jakarta.annotation.Nullable
    private String tokenContractAddress;

    public static final String SERIALIZED_NAME_TOKEN_SYMBOL = "tokenSymbol";

    @SerializedName(SERIALIZED_NAME_TOKEN_SYMBOL)
    @jakarta.annotation.Nullable
    private String tokenSymbol;

    public static final String SERIALIZED_NAME_ASSET_TYPE = "assetType";

    @SerializedName(SERIALIZED_NAME_ASSET_TYPE)
    @jakarta.annotation.Nullable
    private Integer assetType;

    public SearchRwaTokenResponseDataInnerAssetsInner() {}

    public SearchRwaTokenResponseDataInnerAssetsInner platformId(
            @jakarta.annotation.Nullable String platformId) {
        this.platformId = platformId;
        return this;
    }

    /**
     * Unique platform identifier.
     *
     * @return platformId
     */
    @jakarta.annotation.Nullable
    public String getPlatformId() {
        return platformId;
    }

    public void setPlatformId(@jakarta.annotation.Nullable String platformId) {
        this.platformId = platformId;
    }

    public SearchRwaTokenResponseDataInnerAssetsInner binanceChainId(
            @jakarta.annotation.Nullable String binanceChainId) {
        this.binanceChainId = binanceChainId;
        return this;
    }

    /**
     * Unique chain identifier (e.g. \&quot;1\&quot;&#x3D;Ethereum, \&quot;56\&quot;&#x3D;BSC,
     * \&quot;CT_501\&quot;&#x3D;Solana).
     *
     * @return binanceChainId
     */
    @jakarta.annotation.Nullable
    public String getBinanceChainId() {
        return binanceChainId;
    }

    public void setBinanceChainId(@jakarta.annotation.Nullable String binanceChainId) {
        this.binanceChainId = binanceChainId;
    }

    public SearchRwaTokenResponseDataInnerAssetsInner tokenContractAddress(
            @jakarta.annotation.Nullable String tokenContractAddress) {
        this.tokenContractAddress = tokenContractAddress;
        return this;
    }

    /**
     * Token contract address.
     *
     * @return tokenContractAddress
     */
    @jakarta.annotation.Nullable
    public String getTokenContractAddress() {
        return tokenContractAddress;
    }

    public void setTokenContractAddress(@jakarta.annotation.Nullable String tokenContractAddress) {
        this.tokenContractAddress = tokenContractAddress;
    }

    public SearchRwaTokenResponseDataInnerAssetsInner tokenSymbol(
            @jakarta.annotation.Nullable String tokenSymbol) {
        this.tokenSymbol = tokenSymbol;
        return this;
    }

    /**
     * Token symbol.
     *
     * @return tokenSymbol
     */
    @jakarta.annotation.Nullable
    public String getTokenSymbol() {
        return tokenSymbol;
    }

    public void setTokenSymbol(@jakarta.annotation.Nullable String tokenSymbol) {
        this.tokenSymbol = tokenSymbol;
    }

    public SearchRwaTokenResponseDataInnerAssetsInner assetType(
            @jakarta.annotation.Nullable Integer assetType) {
        this.assetType = assetType;
        return this;
    }

    /**
     * Asset type. 1&#x3D;Stock, 2&#x3D;Pre-IPO, 3&#x3D;ETF.
     *
     * @return assetType
     */
    @jakarta.annotation.Nullable
    public Integer getAssetType() {
        return assetType;
    }

    public void setAssetType(@jakarta.annotation.Nullable Integer assetType) {
        this.assetType = assetType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SearchRwaTokenResponseDataInnerAssetsInner searchRwaTokenResponseDataInnerAssetsInner =
                (SearchRwaTokenResponseDataInnerAssetsInner) o;
        return Objects.equals(
                        this.platformId, searchRwaTokenResponseDataInnerAssetsInner.platformId)
                && Objects.equals(
                        this.binanceChainId,
                        searchRwaTokenResponseDataInnerAssetsInner.binanceChainId)
                && Objects.equals(
                        this.tokenContractAddress,
                        searchRwaTokenResponseDataInnerAssetsInner.tokenContractAddress)
                && Objects.equals(
                        this.tokenSymbol, searchRwaTokenResponseDataInnerAssetsInner.tokenSymbol)
                && Objects.equals(
                        this.assetType, searchRwaTokenResponseDataInnerAssetsInner.assetType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                platformId, binanceChainId, tokenContractAddress, tokenSymbol, assetType);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SearchRwaTokenResponseDataInnerAssetsInner {\n");
        sb.append("		platformId: ").append(toIndentedString(platformId)).append("\n");
        sb.append("		binanceChainId: ").append(toIndentedString(binanceChainId)).append("\n");
        sb.append("		tokenContractAddress: ")
                .append(toIndentedString(tokenContractAddress))
                .append("\n");
        sb.append("		tokenSymbol: ").append(toIndentedString(tokenSymbol)).append("\n");
        sb.append("		assetType: ").append(toIndentedString(assetType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object platformIdValue = getPlatformId();
        String platformIdValueAsString = "";
        platformIdValueAsString = platformIdValue.toString();
        sb.append("platformId=").append(urlEncode(platformIdValueAsString)).append("");
        Object binanceChainIdValue = getBinanceChainId();
        String binanceChainIdValueAsString = "";
        binanceChainIdValueAsString = binanceChainIdValue.toString();
        sb.append("binanceChainId=").append(urlEncode(binanceChainIdValueAsString)).append("");
        Object tokenContractAddressValue = getTokenContractAddress();
        String tokenContractAddressValueAsString = "";
        tokenContractAddressValueAsString = tokenContractAddressValue.toString();
        sb.append("tokenContractAddress=")
                .append(urlEncode(tokenContractAddressValueAsString))
                .append("");
        Object tokenSymbolValue = getTokenSymbol();
        String tokenSymbolValueAsString = "";
        tokenSymbolValueAsString = tokenSymbolValue.toString();
        sb.append("tokenSymbol=").append(urlEncode(tokenSymbolValueAsString)).append("");
        Object assetTypeValue = getAssetType();
        String assetTypeValueAsString = "";
        assetTypeValueAsString = assetTypeValue.toString();
        sb.append("assetType=").append(urlEncode(assetTypeValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("platformId");
        openapiFields.add("binanceChainId");
        openapiFields.add("tokenContractAddress");
        openapiFields.add("tokenSymbol");
        openapiFields.add("assetType");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     SearchRwaTokenResponseDataInnerAssetsInner
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!SearchRwaTokenResponseDataInnerAssetsInner.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in"
                                    + " SearchRwaTokenResponseDataInnerAssetsInner is not found in"
                                    + " the empty JSON string",
                                SearchRwaTokenResponseDataInnerAssetsInner.openapiRequiredFields
                                        .toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("platformId") != null && !jsonObj.get("platformId").isJsonNull())
                && !jsonObj.get("platformId").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `platformId` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("platformId").toString()));
        }
        if ((jsonObj.get("binanceChainId") != null && !jsonObj.get("binanceChainId").isJsonNull())
                && !jsonObj.get("binanceChainId").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `binanceChainId` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("binanceChainId").toString()));
        }
        if ((jsonObj.get("tokenContractAddress") != null
                        && !jsonObj.get("tokenContractAddress").isJsonNull())
                && !jsonObj.get("tokenContractAddress").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `tokenContractAddress` to be a primitive type in"
                                    + " the JSON string but got `%s`",
                            jsonObj.get("tokenContractAddress").toString()));
        }
        if ((jsonObj.get("tokenSymbol") != null && !jsonObj.get("tokenSymbol").isJsonNull())
                && !jsonObj.get("tokenSymbol").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `tokenSymbol` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("tokenSymbol").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!SearchRwaTokenResponseDataInnerAssetsInner.class.isAssignableFrom(
                    type.getRawType())) {
                return null; // this class only serializes
                // 'SearchRwaTokenResponseDataInnerAssetsInner' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<SearchRwaTokenResponseDataInnerAssetsInner> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(SearchRwaTokenResponseDataInnerAssetsInner.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<SearchRwaTokenResponseDataInnerAssetsInner>() {
                        @Override
                        public void write(
                                JsonWriter out, SearchRwaTokenResponseDataInnerAssetsInner value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public SearchRwaTokenResponseDataInnerAssetsInner read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of SearchRwaTokenResponseDataInnerAssetsInner given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of SearchRwaTokenResponseDataInnerAssetsInner
     * @throws IOException if the JSON string is invalid with respect to
     *     SearchRwaTokenResponseDataInnerAssetsInner
     */
    public static SearchRwaTokenResponseDataInnerAssetsInner fromJson(String jsonString)
            throws IOException {
        return JSON.getGson()
                .fromJson(jsonString, SearchRwaTokenResponseDataInnerAssetsInner.class);
    }

    /**
     * Convert an instance of SearchRwaTokenResponseDataInnerAssetsInner to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
