/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Objects;
import org.hibernate.validator.constraints.*;

/** SimulateTransactionsRequest */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class SimulateTransactionsRequest {
    public static final String SERIALIZED_NAME_BINANCE_CHAIN_ID = "binanceChainId";

    @SerializedName(SERIALIZED_NAME_BINANCE_CHAIN_ID)
    @jakarta.annotation.Nonnull
    private String binanceChainId;

    public static final String SERIALIZED_NAME_EVM_TX = "evmTx";

    @SerializedName(SERIALIZED_NAME_EVM_TX)
    @jakarta.annotation.Nullable
    private SimulateTransactionsRequestEvmTx evmTx;

    public static final String SERIALIZED_NAME_SOL_TX = "solTx";

    @SerializedName(SERIALIZED_NAME_SOL_TX)
    @jakarta.annotation.Nullable
    private SimulateTransactionsRequestSolTx solTx;

    public SimulateTransactionsRequest() {}

    public SimulateTransactionsRequest binanceChainId(
            @jakarta.annotation.Nonnull String binanceChainId) {
        this.binanceChainId = binanceChainId;
        return this;
    }

    /**
     * Unique chain identifier (e.g. \&quot;1\&quot;&#x3D;Ethereum, \&quot;56\&quot;&#x3D;BSC,
     * \&quot;CT_501\&quot;&#x3D;Solana).
     *
     * @return binanceChainId
     */
    @jakarta.annotation.Nonnull
    @NotNull
    public String getBinanceChainId() {
        return binanceChainId;
    }

    public void setBinanceChainId(@jakarta.annotation.Nonnull String binanceChainId) {
        this.binanceChainId = binanceChainId;
    }

    public SimulateTransactionsRequest evmTx(
            @jakarta.annotation.Nullable SimulateTransactionsRequestEvmTx evmTx) {
        this.evmTx = evmTx;
        return this;
    }

    /**
     * Get evmTx
     *
     * @return evmTx
     */
    @jakarta.annotation.Nullable
    @Valid
    public SimulateTransactionsRequestEvmTx getEvmTx() {
        return evmTx;
    }

    public void setEvmTx(@jakarta.annotation.Nullable SimulateTransactionsRequestEvmTx evmTx) {
        this.evmTx = evmTx;
    }

    public SimulateTransactionsRequest solTx(
            @jakarta.annotation.Nullable SimulateTransactionsRequestSolTx solTx) {
        this.solTx = solTx;
        return this;
    }

    /**
     * Get solTx
     *
     * @return solTx
     */
    @jakarta.annotation.Nullable
    @Valid
    public SimulateTransactionsRequestSolTx getSolTx() {
        return solTx;
    }

    public void setSolTx(@jakarta.annotation.Nullable SimulateTransactionsRequestSolTx solTx) {
        this.solTx = solTx;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SimulateTransactionsRequest simulateTransactionsRequest = (SimulateTransactionsRequest) o;
        return Objects.equals(this.binanceChainId, simulateTransactionsRequest.binanceChainId)
                && Objects.equals(this.evmTx, simulateTransactionsRequest.evmTx)
                && Objects.equals(this.solTx, simulateTransactionsRequest.solTx);
    }

    @Override
    public int hashCode() {
        return Objects.hash(binanceChainId, evmTx, solTx);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SimulateTransactionsRequest {\n");
        sb.append("		binanceChainId: ").append(toIndentedString(binanceChainId)).append("\n");
        sb.append("		evmTx: ").append(toIndentedString(evmTx)).append("\n");
        sb.append("		solTx: ").append(toIndentedString(solTx)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object binanceChainIdValue = getBinanceChainId();
        String binanceChainIdValueAsString = "";
        binanceChainIdValueAsString = binanceChainIdValue.toString();
        sb.append("binanceChainId=").append(urlEncode(binanceChainIdValueAsString)).append("");
        Object evmTxValue = getEvmTx();
        String evmTxValueAsString = "";
        evmTxValueAsString = evmTxValue.toString();
        sb.append("evmTx=").append(urlEncode(evmTxValueAsString)).append("");
        Object solTxValue = getSolTx();
        String solTxValueAsString = "";
        solTxValueAsString = solTxValue.toString();
        sb.append("solTx=").append(urlEncode(solTxValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("binanceChainId");
        openapiFields.add("evmTx");
        openapiFields.add("solTx");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("binanceChainId");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     SimulateTransactionsRequest
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!SimulateTransactionsRequest.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in SimulateTransactionsRequest is not"
                                        + " found in the empty JSON string",
                                SimulateTransactionsRequest.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : SimulateTransactionsRequest.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("binanceChainId").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `binanceChainId` to be a primitive type in the JSON"
                                    + " string but got `%s`",
                            jsonObj.get("binanceChainId").toString()));
        }
        // validate the optional field `evmTx`
        if (jsonObj.get("evmTx") != null && !jsonObj.get("evmTx").isJsonNull()) {
            SimulateTransactionsRequestEvmTx.validateJsonElement(jsonObj.get("evmTx"));
        }
        // validate the optional field `solTx`
        if (jsonObj.get("solTx") != null && !jsonObj.get("solTx").isJsonNull()) {
            SimulateTransactionsRequestSolTx.validateJsonElement(jsonObj.get("solTx"));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!SimulateTransactionsRequest.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'SimulateTransactionsRequest' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<SimulateTransactionsRequest> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(SimulateTransactionsRequest.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<SimulateTransactionsRequest>() {
                        @Override
                        public void write(JsonWriter out, SimulateTransactionsRequest value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public SimulateTransactionsRequest read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of SimulateTransactionsRequest given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of SimulateTransactionsRequest
     * @throws IOException if the JSON string is invalid with respect to SimulateTransactionsRequest
     */
    public static SimulateTransactionsRequest fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, SimulateTransactionsRequest.class);
    }

    /**
     * Convert an instance of SimulateTransactionsRequest to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
