/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import org.hibernate.validator.constraints.*;

/** Gets or Sets tagFilter */
@JsonAdapter(TagFilter.Adapter.class)
public enum TagFilter {
    TAG_FILTER_1(1),

    TAG_FILTER_2(2),

    TAG_FILTER_3(3),

    TAG_FILTER_4(4),

    TAG_FILTER_5(5),

    TAG_FILTER_6(6),

    TAG_FILTER_7(7);

    private Integer value;

    TagFilter(Integer value) {
        this.value = value;
    }

    public Integer getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static TagFilter fromValue(Integer value) {
        for (TagFilter b : TagFilter.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TagFilter> {
        @Override
        public void write(final JsonWriter jsonWriter, final TagFilter enumeration)
                throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public TagFilter read(final JsonReader jsonReader) throws IOException {
            Integer value = jsonReader.nextInt();
            return TagFilter.fromValue(value);
        }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        Integer value = jsonElement.getAsInt();
        TagFilter.fromValue(value);
    }
}
