/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, and transaction APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;
import org.hibernate.validator.constraints.*;
import org.openapitools.jackson.nullable.JsonNullable;

/** TagInfo */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class TagInfo {
    public static final String SERIALIZED_NAME_IS_RECOGNIZED = "isRecognized";

    @SerializedName(SERIALIZED_NAME_IS_RECOGNIZED)
    @jakarta.annotation.Nullable
    private Boolean isRecognized;

    public TagInfo() {}

    public TagInfo isRecognized(@jakarta.annotation.Nullable Boolean isRecognized) {
        this.isRecognized = isRecognized;
        return this;
    }

    /**
     * True indicates the token is listed on major centralized exchanges or widely recognized by the
     * community.
     *
     * @return isRecognized
     */
    @jakarta.annotation.Nullable
    public Boolean getIsRecognized() {
        return isRecognized;
    }

    public void setIsRecognized(@jakarta.annotation.Nullable Boolean isRecognized) {
        this.isRecognized = isRecognized;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TagInfo tagInfo = (TagInfo) o;
        return Objects.equals(this.isRecognized, tagInfo.isRecognized);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b
                || (a != null
                        && b != null
                        && a.isPresent()
                        && b.isPresent()
                        && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode() {
        return Objects.hash(isRecognized);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TagInfo {\n");
        sb.append("		isRecognized: ").append(toIndentedString(isRecognized)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object isRecognizedValue = getIsRecognized();
        String isRecognizedValueAsString = "";
        isRecognizedValueAsString = isRecognizedValue.toString();
        sb.append("isRecognized=").append(urlEncode(isRecognizedValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("isRecognized");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to TagInfo
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!TagInfo.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in TagInfo is not found in the empty JSON"
                                        + " string",
                                TagInfo.openapiRequiredFields.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!TagInfo.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'TagInfo' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<TagInfo> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(TagInfo.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<TagInfo>() {
                        @Override
                        public void write(JsonWriter out, TagInfo value) throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public TagInfo read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of TagInfo given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of TagInfo
     * @throws IOException if the JSON string is invalid with respect to TagInfo
     */
    public static TagInfo fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, TagInfo.class);
    }

    /**
     * Convert an instance of TagInfo to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
