/*
 * Binance Web3 API
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.rest.model;

import com.binance.connector.client.web3_wallet.rest.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.hibernate.validator.constraints.*;

/** VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions {
    public static final String SERIALIZED_NAME_BAZAAR = "bazaar";

    @SerializedName(SERIALIZED_NAME_BAZAAR)
    @jakarta.annotation.Nullable
    private VerifyB402PaymentV2RequestBodyPaymentPayloadExtensionsBazaar bazaar;

    public VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions() {}

    public VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions bazaar(
            @jakarta.annotation.Nullable
                    VerifyB402PaymentV2RequestBodyPaymentPayloadExtensionsBazaar bazaar) {
        this.bazaar = bazaar;
        return this;
    }

    /**
     * Get bazaar
     *
     * @return bazaar
     */
    @jakarta.annotation.Nullable
    @Valid
    public VerifyB402PaymentV2RequestBodyPaymentPayloadExtensionsBazaar getBazaar() {
        return bazaar;
    }

    public void setBazaar(
            @jakarta.annotation.Nullable
                    VerifyB402PaymentV2RequestBodyPaymentPayloadExtensionsBazaar bazaar) {
        this.bazaar = bazaar;
    }

    /**
     * A container for additional, undeclared properties. This is a holder for any undeclared
     * properties as specified with the 'additionalProperties' keyword in the OAS document.
     */
    private Map<String, Object> additionalProperties;

    /**
     * Set the additional (undeclared) property with the specified name and value. If the property
     * does not already exist, create it otherwise replace it.
     *
     * @param key name of the property
     * @param value value of the property
     * @return the VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions instance itself
     */
    public VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions putAdditionalProperty(
            String key, Object value) {
        if (this.additionalProperties == null) {
            this.additionalProperties = new HashMap<String, Object>();
        }
        this.additionalProperties.put(key, value);
        return this;
    }

    /**
     * Return the additional (undeclared) property.
     *
     * @return a map of objects
     */
    public Map<String, Object> getAdditionalProperties() {
        return additionalProperties;
    }

    /**
     * Return the additional (undeclared) property with the specified name.
     *
     * @param key name of the property
     * @return an object
     */
    public Object getAdditionalProperty(String key) {
        if (this.additionalProperties == null) {
            return null;
        }
        return this.additionalProperties.get(key);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions
                verifyB402PaymentV2RequestBodyPaymentPayloadExtensions =
                        (VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions) o;
        return Objects.equals(
                        this.bazaar, verifyB402PaymentV2RequestBodyPaymentPayloadExtensions.bazaar)
                && Objects.equals(
                        this.additionalProperties,
                        verifyB402PaymentV2RequestBodyPaymentPayloadExtensions
                                .additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bazaar, additionalProperties);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions {\n");
        sb.append("		bazaar: ").append(toIndentedString(bazaar)).append("\n");
        sb.append("		additionalProperties: ")
                .append(toIndentedString(additionalProperties))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();

        Object bazaarValue = getBazaar();
        String bazaarValueAsString = "";
        bazaarValueAsString = bazaarValue.toString();
        sb.append("bazaar=").append(urlEncode(bazaarValueAsString)).append("");
        return sb.toString();
    }

    public static String urlEncode(String s) {
        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(StandardCharsets.UTF_8.name() + " is unsupported", e);
        }
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("bazaar");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (!jsonElement.isJsonObject()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected json element to be a object type in the JSON string but got"
                                    + " `%s`",
                            jsonElement.toString()));
        }

        Map<String, JsonElement> map = jsonElement.getAsJsonObject().asMap();
        // validate map items
        for (JsonElement element : map.values()) {}
        if (jsonElement == null) {
            if (!VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in"
                                    + " VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions is"
                                    + " not found in the empty JSON string",
                                VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions
                                        .openapiRequiredFields
                                        .toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the optional field `bazaar`
        if (jsonObj.get("bazaar") != null && !jsonObj.get("bazaar").isJsonNull()) {
            VerifyB402PaymentV2RequestBodyPaymentPayloadExtensionsBazaar.validateJsonElement(
                    jsonObj.get("bazaar"));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions.class.isAssignableFrom(
                    type.getRawType())) {
                return null; // this class only serializes
                // 'VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions> thisAdapter =
                    gson.getDelegateAdapter(
                            this,
                            TypeToken.get(
                                    VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions>() {
                        @Override
                        public void write(
                                JsonWriter out,
                                VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions read(
                                JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            JsonObject jsonObj = jsonElement.getAsJsonObject();
                            // store additional fields in the deserialized instance
                            VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions instance =
                                    thisAdapter.fromJsonTree(jsonObj);
                            for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
                                if (!openapiFields.contains(entry.getKey())) {
                                    if (entry.getValue().isJsonPrimitive()) { // primitive type
                                        if (entry.getValue().getAsJsonPrimitive().isString())
                                            instance.putAdditionalProperty(
                                                    entry.getKey(), entry.getValue().getAsString());
                                        else if (entry.getValue().getAsJsonPrimitive().isNumber())
                                            instance.putAdditionalProperty(
                                                    entry.getKey(), entry.getValue().getAsNumber());
                                        else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                                            instance.putAdditionalProperty(
                                                    entry.getKey(),
                                                    entry.getValue().getAsBoolean());
                                        else
                                            throw new IllegalArgumentException(
                                                    String.format(
                                                            "The field `%s` has unknown primitive"
                                                                    + " type. Value: %s",
                                                            entry.getKey(),
                                                            entry.getValue().toString()));
                                    } else if (entry.getValue().isJsonArray()) {
                                        instance.putAdditionalProperty(
                                                entry.getKey(),
                                                gson.fromJson(entry.getValue(), List.class));
                                    } else { // JSON object
                                        instance.putAdditionalProperty(
                                                entry.getKey(),
                                                gson.fromJson(entry.getValue(), HashMap.class));
                                    }
                                }
                            }
                            return instance;
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions given an JSON
     * string
     *
     * @param jsonString JSON string
     * @return An instance of VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions
     * @throws IOException if the JSON string is invalid with respect to
     *     VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions
     */
    public static VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions fromJson(String jsonString)
            throws IOException {
        return JSON.getGson()
                .fromJson(jsonString, VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions.class);
    }

    /**
     * Convert an instance of VerifyB402PaymentV2RequestBodyPaymentPayloadExtensions to an JSON
     * string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
