/*
 * Binance Web3 WebSocket Streams
 * Real-time on-chain data streaming over WebSocket for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.binance.connector.client.web3_wallet.websocket.stream.model;

import com.binance.connector.client.common.websocket.dtos.BaseDTO;
import com.binance.connector.client.web3_wallet.websocket.stream.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import jakarta.validation.constraints.*;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeMap;
import java.util.stream.Collectors;
import org.hibernate.validator.constraints.*;

/** CandlestickStreamRequest */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class CandlestickStreamRequest extends BaseDTO {
    public static final String SERIALIZED_NAME_ID = "id";

    @SerializedName(SERIALIZED_NAME_ID)
    @jakarta.annotation.Nullable
    private String id;

    public static final String SERIALIZED_NAME_BAR = "bar";

    @SerializedName(SERIALIZED_NAME_BAR)
    @jakarta.annotation.Nullable
    private String bar;

    public static final String SERIALIZED_NAME_CHAIN_ID = "chainId";

    @SerializedName(SERIALIZED_NAME_CHAIN_ID)
    @jakarta.annotation.Nullable
    private String chainId;

    public static final String SERIALIZED_NAME_CONTRACT_ADDRESS = "contractAddress";

    @SerializedName(SERIALIZED_NAME_CONTRACT_ADDRESS)
    @jakarta.annotation.Nullable
    private String contractAddress;

    public CandlestickStreamRequest() {}

    public CandlestickStreamRequest id(@jakarta.annotation.Nullable String id) {
        this.id = id;
        return this;
    }

    /**
     * Unique WebSocket request ID.
     *
     * @return id
     */
    @jakarta.annotation.Nullable
    public String getId() {
        return id;
    }

    public void setId(@jakarta.annotation.Nullable String id) {
        this.id = id;
    }

    public CandlestickStreamRequest bar(@jakarta.annotation.Nullable String bar) {
        this.bar = bar;
        return this;
    }

    /**
     * K-line interval. Enum: 1s, 5s, 30s, 1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d,
     * 1w, 1M.
     *
     * @return bar
     */
    @jakarta.annotation.Nullable
    public String getBar() {
        return bar;
    }

    public void setBar(@jakarta.annotation.Nullable String bar) {
        this.bar = bar;
    }

    public CandlestickStreamRequest chainId(@jakarta.annotation.Nullable String chainId) {
        this.chainId = chainId;
        return this;
    }

    /**
     * Chain identifier, e.g. \&quot;1\&quot;&#x3D;Ethereum, \&quot;56\&quot;&#x3D;BSC,
     * \&quot;CT_501\&quot;&#x3D;Solana. Full supported-chain list: same as the
     * [\&quot;supported/chain\&quot;](/catalog/web3-wallet/api/rest-api/general-data#get-supported-chains)
     * endpoint.
     *
     * @return chainId
     */
    @jakarta.annotation.Nullable
    public String getChainId() {
        return chainId;
    }

    public void setChainId(@jakarta.annotation.Nullable String chainId) {
        this.chainId = chainId;
    }

    public CandlestickStreamRequest contractAddress(
            @jakarta.annotation.Nullable String contractAddress) {
        this.contractAddress = contractAddress;
        return this;
    }

    /**
     * Token contract address.
     *
     * @return contractAddress
     */
    @jakarta.annotation.Nullable
    public String getContractAddress() {
        return contractAddress;
    }

    public void setContractAddress(@jakarta.annotation.Nullable String contractAddress) {
        this.contractAddress = contractAddress;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CandlestickStreamRequest candlestickStreamRequest = (CandlestickStreamRequest) o;
        return Objects.equals(this.id, candlestickStreamRequest.id)
                && Objects.equals(this.bar, candlestickStreamRequest.bar)
                && Objects.equals(this.chainId, candlestickStreamRequest.chainId)
                && Objects.equals(this.contractAddress, candlestickStreamRequest.contractAddress);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, bar, chainId, contractAddress);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CandlestickStreamRequest {\n");
        sb.append("		id: ").append(toIndentedString(id)).append("\n");
        sb.append("		bar: ").append(toIndentedString(bar)).append("\n");
        sb.append("		chainId: ").append(toIndentedString(chainId)).append("\n");
        sb.append("		contractAddress: ").append(toIndentedString(contractAddress)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    public String toUrlQueryString() {
        StringBuilder sb = new StringBuilder();
        Map<String, String> valMap = new TreeMap<String, String>();
        valMap.put("apiKey", getApiKey());
        String idValue = getId();
        if (idValue != null) {
            String idValueAsString = idValue.toString();
            valMap.put("id", idValueAsString);
        }
        String barValue = getBar();
        if (barValue != null) {
            String barValueAsString = barValue.toString();
            valMap.put("bar", barValueAsString);
        }
        String chainIdValue = getChainId();
        if (chainIdValue != null) {
            String chainIdValueAsString = chainIdValue.toString();
            valMap.put("chainId", chainIdValueAsString);
        }
        String contractAddressValue = getContractAddress();
        if (contractAddressValue != null) {
            String contractAddressValueAsString = contractAddressValue.toString();
            valMap.put("contractAddress", contractAddressValueAsString);
        }

        valMap.put("timestamp", getTimestamp());
        return asciiEncode(
                valMap.keySet().stream()
                        .map(key -> key + "=" + valMap.get(key))
                        .collect(Collectors.joining("&")));
    }

    public Map<String, Object> toMap() {
        Map<String, Object> valMap = new TreeMap<String, Object>();
        valMap.put("apiKey", getApiKey());
        Object idValue = getId();
        if (idValue != null) {
            valMap.put("id", idValue);
        }
        Object barValue = getBar();
        if (barValue != null) {
            valMap.put("bar", barValue);
        }
        Object chainIdValue = getChainId();
        if (chainIdValue != null) {
            valMap.put("chainId", chainIdValue);
        }
        Object contractAddressValue = getContractAddress();
        if (contractAddressValue != null) {
            valMap.put("contractAddress", contractAddressValue);
        }

        valMap.put("timestamp", getTimestamp());
        return valMap;
    }

    public static String asciiEncode(String s) {
        return new String(s.getBytes(), StandardCharsets.US_ASCII);
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n		");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("id");
        openapiFields.add("bar");
        openapiFields.add("chainId");
        openapiFields.add("contractAddress");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to CandlestickStreamRequest
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!CandlestickStreamRequest.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in CandlestickStreamRequest is not found"
                                        + " in the empty JSON string",
                                CandlestickStreamRequest.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!CandlestickStreamRequest.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                        + " `CandlestickStreamRequest` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull())
                && !jsonObj.get("id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `id` to be a primitive type in the JSON string but"
                                    + " got `%s`",
                            jsonObj.get("id").toString()));
        }
        if ((jsonObj.get("bar") != null && !jsonObj.get("bar").isJsonNull())
                && !jsonObj.get("bar").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `bar` to be a primitive type in the JSON string but"
                                    + " got `%s`",
                            jsonObj.get("bar").toString()));
        }
        if ((jsonObj.get("chainId") != null && !jsonObj.get("chainId").isJsonNull())
                && !jsonObj.get("chainId").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `chainId` to be a primitive type in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("chainId").toString()));
        }
        if ((jsonObj.get("contractAddress") != null && !jsonObj.get("contractAddress").isJsonNull())
                && !jsonObj.get("contractAddress").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `contractAddress` to be a primitive type in the"
                                    + " JSON string but got `%s`",
                            jsonObj.get("contractAddress").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!CandlestickStreamRequest.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'CandlestickStreamRequest' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<CandlestickStreamRequest> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(CandlestickStreamRequest.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<CandlestickStreamRequest>() {
                        @Override
                        public void write(JsonWriter out, CandlestickStreamRequest value)
                                throws IOException {
                            JsonElement obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public CandlestickStreamRequest read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            // validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of CandlestickStreamRequest given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of CandlestickStreamRequest
     * @throws IOException if the JSON string is invalid with respect to CandlestickStreamRequest
     */
    public static CandlestickStreamRequest fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, CandlestickStreamRequest.class);
    }

    /**
     * Convert an instance of CandlestickStreamRequest to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
